"""Scene definitions for the Hedged Requests teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Hedged Requests',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Hedged Requests pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] If a call has not answered after a short wait, send the same call to a second copy of the service. [[slnc 300]] Use whichever answer comes first. [[slnc 300]] And cancel the other. [[slnc 600]] Think of phoning a shop to ask if something is in stock. [[slnc 300]] Nobody picks up after a few rings. [[slnc 300]] So you call their other branch too. [[slnc 300]] Whichever answers first gets your question, and you hang up on the other. [[slnc 700]] In this video, the domain is an online shop's product page. [[slnc 300]] It asks a price service for each price. [[slnc 300]] And there are several copies of that service, called replicas. [[slnc 500]] By the end, you will hear why the average hides slow calls. [[slnc 300]] How a second call after fifty milliseconds fixes them. [[slnc 300]] Why not to send two calls every time. [[slnc 300]] And which calls must never be hedged."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The product page asks for prices.', '', 'Most answers: 20 ms.', '', '1 call in 33 hits a paused', 'replica: 1 second.'],
         narration='Here is the scenario. [[slnc 400]] The product page asks the price service for each price. [[slnc 500]] Most answers take twenty milliseconds. [[slnc 500]] But now and then a replica pauses, for example to clean up memory. [[slnc 300]] About one call in thirty-three then takes a whole second.'),
    dict(key='03-act-1', kind='console', title='Act One — One call, and a slow tail',
         body='ONE. One call, and a slow tail.\n  median 20 ms\n  99th percentile 1000 ms',
         narration='First demo: one call per price. [[slnc 400]] We look up a thousand prices. [[slnc 500]] Half the answers take twenty milliseconds or less. [[slnc 300]] But about one call in thirty-three lands on a paused replica. [[slnc 300]] That call takes a whole second. [[slnc 600]] So the slowest one percent of calls take a full second. [[slnc 300]] And the product page waits for them.'),
    dict(key='04-act-2', kind='console', title='Act Two — Hedge after 50 ms',
         body='TWO. Hedge after 50 ms.\n  99th percentile 70 ms, worst 70 ms\n  extra calls: 31 of 1000 (3%)',
         narration='Second demo: hedge after fifty milliseconds. [[slnc 400]] Fifty milliseconds is longer than a normal call ever takes. [[slnc 600]] If there is no answer by then, the client asks a second replica. [[slnc 300]] Whichever answers first, wins. [[slnc 600]] The slowest calls now take seventy milliseconds. [[slnc 300]] Fifty waiting, and twenty for the backup. [[slnc 500]] And only three percent of calls needed a second call.'),
    dict(key='05-act-3', kind='console', title='Act Three — Hedge at once',
         body='THREE. Hedge at once.\n  99th percentile 20 ms\n  extra calls: 1000 of 1000 (100%)',
         narration='Third demo: why wait at all? [[slnc 400]] Send every request to two replicas at once. [[slnc 600]] Now the slowest calls take only twenty milliseconds. [[slnc 300]] But every request is sent twice. [[slnc 300]] The price service does double the work. [[slnc 600]] Twice the load, to save fifty milliseconds on a few calls. [[slnc 300]] Waiting first is the better deal.'),
    dict(key='06-act-4', kind='console', title='Act Four — A real race',
         body="FOUR. A real race.\n  answer from replica B\n  time: under 0.5 s\n  replica A's call cancelled",
         narration="Fourth demo: a real race, with real threads. [[slnc 400]] Replica A is paused. [[slnc 300]] It would take a whole second. [[slnc 300]] Replica B answers in twenty milliseconds. [[slnc 600]] The hedger asks A, and waits fifty milliseconds. [[slnc 300]] No answer, so it asks B too. [[slnc 500]] B's answer comes back in well under half a second. [[slnc 500]] Then the hedger cancels the call to A. [[slnc 300]] So A stops working on an answer nobody needs."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  never hedge "place order"\n  cap hedges at a few percent',
         narration='Fifth demo: the bill. [[slnc 400]] Hedging sends the same request twice. [[slnc 300]] So only hedge calls that are safe to repeat. [[slnc 500]] Reading a price, is fine. [[slnc 300]] Placing an order, is not. [[slnc 300]] The customer could be charged twice. [[slnc 600]] And if every replica is slow because they are all overloaded, extra calls make things worse. [[slnc 300]] So keep hedges to a few percent of requests.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Call one replica.', '', 'No answer after a short delay?', 'Call another.', '', 'First answer wins; cancel the other.'],
         narration="Let's name the pattern. [[slnc 400]] Call one replica. [[slnc 500]] If there is no answer after a short delay, call a second replica with the same request. [[slnc 500]] The first answer wins. [[slnc 300]] And the other call is cancelled."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Replica: one copy of the price service', 'Hedger: waits, asks again, takes the first', 'LatencyModel: measures the slow tail'],
         narration='Here is who does what. [[slnc 400]] A replica is one copy of the price service. [[slnc 500]] The hedger makes the call. [[slnc 300]] It waits fifty milliseconds, asks a second replica if needed, takes the first answer, and cancels the other. [[slnc 500]] And the latency model measures a thousand calls, so we can compare the slowest ones.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Google\'s "The Tail at Scale"', 'gRPC hedging policy', 'Cassandra speculative retry', 'CompletableFuture.anyOf'],
         narration='You have probably met this pattern already. [[slnc 400]] Google made it famous, in a paper called The Tail at Scale. [[slnc 500]] gRPC can hedge calls, with a setting per method. [[slnc 300]] And Cassandra calls it speculative retry. [[slnc 500]] In Java, racing futures with any-of is the same idea.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Several replicas, rare slow calls.', '', 'Only calls safe to repeat.', 'Wait before hedging.', 'Cancel the loser.', 'Cap the hedges.'],
         narration='So, when should you use it? [[slnc 400]] When a service has several replicas, and slow calls are rare. [[slnc 500]] Only hedge calls that are safe to repeat. [[slnc 300]] Wait a little before hedging. [[slnc 300]] Cancel the loser. [[slnc 300]] And cap how many hedges you send.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a hedge budget', 'of 5%.'],
         narration="That's the Hedged Requests pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] When one copy is slow, ask another, and keep the first answer. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a budget, so hedges stop once they reach five percent of calls. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Hedged Requests Pattern  ·  Java 21', 'poster': {'headline': [('HEDGED', 'text'), ('REQUESTS', 'text')], 'before': {'code': 'wait for replica A', 'note': '1 in 33 pages waits 1 s', 'tag': 'BEFORE'}, 'after': {'code': 'after 50 ms: ask B too', 'note': 'worst case 70 ms', 'tag': 'AFTER'}, 'taglines': [("Don't wait on the slow one", 'gold')]}, 'highlight': {}}
