"""Scene definitions for the Token Authentication with Spring Security teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Token Authentication with Spring Security',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Token Authentication, built with Spring Security, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] After you sign in, you are given a signed token that says who you are, and until when. [[slnc 300]] Any server holding the key can trust it, without looking anything up. [[slnc 500]] Spring Security is the open-source security framework most Java web applications use, and it checks these tokens for you. [[slnc 600]] Think of a festival wristband. [[slnc 300]] Checked once at the gate. [[slnc 300]] Then any steward can glance at it, and let you in. [[slnc 700]] In this video, the domain is an online shop's website, running as two server instances. [[slnc 500]] By the end, you will hear why sessions fail across servers. [[slnc 300]] How Spring Security issues and checks tokens. [[slnc 300]] And what signing out, and a stolen key, mean."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Two server instances.', '', "Sessions in each one's memory.", '', 'The other server:', 'please sign in.'],
         narration="Here is the scenario. [[slnc 400]] The shop's website runs as two server instances. [[slnc 500]] Each remembered signed-in customers in its own memory. [[slnc 500]] A request that reached the other server was asked to sign in again."),
    dict(key='03-act-1', kind='console', title='Act One — Sessions on one server',
         body="ONE. Sessions on one server.\n  server A: 200 ana's cart\n  server B: 401 please sign in",
         narration="First demo: sessions kept in one server's memory. [[slnc 400]] Two copies of the shop's server are running, A and B. [[slnc 600]] Ana signs in on server A. [[slnc 300]] A remembers Ana in its own memory. [[slnc 500]] Server A shows Ana's cart. [[slnc 300]] Server B has never heard of Ana. [[slnc 300]] Please sign in."),
    dict(key='04-act-2', kind='console', title='Act Two — A token from Spring Security',
         body='TWO. A token from Spring Security.\n  POST /token: a JWT for ana\n  A: 200, B: 200',
         narration="Second demo: a signed token from Spring Security. [[slnc 400]] Ana signs in once, with a password. [[slnc 300]] Ana gets back a token, signed with the shop's secret. [[slnc 600]] It says who the customer is, and when it expires, in fifteen minutes. [[slnc 500]] Server A accepts it. [[slnc 300]] So does server B. [[slnc 300]] Nothing is shared between them but the secret."),
    dict(key='05-act-3', kind='console', title='Act Three — Forged and expired',
         body='THREE. Forged and expired.\n  edited to ben: 401 Invalid signature\n  expired: 401 Jwt expired',
         narration='Third demo: forged and expired tokens. [[slnc 400]] Someone edits the token to say Ben. [[slnc 300]] Spring Security refuses it, before any shop code runs. [[slnc 300]] Invalid signature. [[slnc 600]] A token that expired two minutes ago. [[slnc 300]] Refused. [[slnc 300]] Token expired.'),
    dict(key='06-act-4', kind='console', title='Act Four — Signing out early',
         body="FOUR. Signing out early.\n  A: 401 revoked\n  B: 200 ana's cart",
         narration='Fourth demo: signing out early. [[slnc 400]] Ana signs out, on server A. [[slnc 300]] A adds that token to its revoked list. [[slnc 600]] Server A now refuses the token. [[slnc 500]] Server B has its own list. [[slnc 300]] It still accepts it. [[slnc 600]] Keep tokens short-lived. [[slnc 300]] And share any revoked list.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body="FIVE. The bill.\n  payload readable: sub=ana\n  stolen secret: 200 ben's cart",
         narration="Fifth demo: the bill. [[slnc 400]] Anyone can read what the token says. [[slnc 300]] So never put secrets in it. [[slnc 600]] And everything rests on the shop's secret. [[slnc 300]] Someone who steals it signs a token for Ben. [[slnc 300]] Server A accepts it. [[slnc 600]] Keep the key in a secrets manager, and change it regularly."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Spring Security',
         body=['Sign in once: JwtEncoder.', '', 'Every request: the resource', 'server checks the JWT.', '', 'Add validators as needed.'],
         narration="Let's name the pattern, in Spring Security's words. [[slnc 400]] Sign in once, and a JWT encoder issues the token. [[slnc 500]] On every request, the resource server support checks it. [[slnc 500]] And extra rules, like a revoked list, are added as validators."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShopApp: security configuration', 'ShopController: token, cart, sign-out', 'JwtDecoder: signature, expiry, revoked'],
         narration="Here is who does what. [[slnc 400]] Shop app holds the security configuration, and issues tokens. [[slnc 500]] The shop controller has the sign-in, the cart, and sign-out. [[slnc 500]] And the decoder checks each token's signature, expiry, and the revoked list."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['oauth2ResourceServer in Spring', 'Keycloak, Auth0, Okta tokens', 'Bearer headers'],
         narration="You have probably met this already. [[slnc 400]] Spring configurations with a resource server, and JWT. [[slnc 500]] Tokens from identity providers such as Keycloak, Auth0 and Okta. [[slnc 500]] And bearer tokens, in any browser's developer tools."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Several instances or services.', '', 'Short-lived tokens.', 'Clock skew set on purpose.', 'Shared revocation.', 'Guard the key.'],
         narration='So, when should you use it? [[slnc 400]] Whenever several instances or services must recognise the same customer. [[slnc 500]] Keep tokens short-lived. [[slnc 300]] Set the clock allowance on purpose. [[slnc 300]] Share revocation. [[slnc 300]] And guard the signing key.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Switch to', 'an RSA key pair.'],
         narration="That's Token Authentication, with Spring Security. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Sign in once, carry signed proof, and let the framework check it on every request. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Switch to a key pair, so services can check tokens without being able to sign them. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Token Authentication with Spring Security Pattern  ·  Java 21', 'poster': {'headline': [('TOKEN AUTHENTICATION', 'text'), ('WITH SPRING SECURITY', 'text')], 'before': {'code': 'session on server A', 'note': 'server B: please sign in', 'tag': 'BEFORE'}, 'after': {'code': 'oauth2ResourceServer(jwt)', 'note': 'any instance checks the token', 'tag': 'AFTER'}, 'taglines': [('JWTs, checked for you', 'gold')]}, 'highlight': {}}
