package com.jk.explore.idempotentconsumer;

/**
 * A message as it arrives from the broker.
 *
 * The field that matters is the first one. The {@code messageId} was generated by whoever
 * wrote the message and never changes, not even when the same message is delivered a second
 * time, and that single fact is what makes this whole pattern possible. A duplicate is not a
 * message that looks similar — it is a message with an id you have seen before.
 *
 * <p>If a message has no stable id, there is nothing to deduplicate on, and the first job is
 * to get one added at the sending end.
 */
public record Message(String messageId, String type, String orderId, Money total) {

    @Override
    public String toString() {
        return type + "(" + orderId + ", " + total + ")";
    }
}
