"""Scene definitions for the Guaranteed Delivery with RabbitMQ teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Guaranteed Delivery with RabbitMQ',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Guaranteed Delivery pattern, with a real RabbitMQ broker, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Guaranteed delivery means a message, once accepted, is never lost. [[slnc 300]] Not when the program crashes. [[slnc 300]] Not when the broker restarts. [[slnc 500]] RabbitMQ is an open-source message broker, a separate program that holds messages, and it can give that guarantee if you ask for it correctly. [[slnc 600]] Think of recorded delivery at the post office. [[slnc 300]] You get a receipt when you hand the letter over. [[slnc 300]] And it is signed for at the other end. [[slnc 700]] In this video, the domain is an online shop's order confirmation emails. [[slnc 500]] By the end, you will hear which RabbitMQ settings make the guarantee. [[slnc 300]] What happens when one is missing. [[slnc 300]] And why a guaranteed message can still arrive twice."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Confirmation emails wait on a queue.', '', 'The broker restarted.', '', '10 emails vanished.'],
         narration="Here is the scenario. [[slnc 400]] The shop's confirmation emails wait on a queue, while the email provider is slow. [[slnc 500]] The broker restarted, for an update. [[slnc 500]] Ten emails vanished. [[slnc 300]] Ten customers never heard that their order was received."),
    dict(key='03-act-1', kind='console', title='Act One — Durable queue, transient messages',
         body='ONE. Durable queue, transient messages.\n  before restart: waiting 10\n  after restart: waiting 0',
         narration='First demo: a durable queue, but messages that are not persistent. [[slnc 400]] The queue itself is written to disk. [[slnc 300]] The messages are not. [[slnc 600]] Ten emails are waiting. [[slnc 300]] The broker restarts. [[slnc 500]] The queue is still there. [[slnc 300]] It is empty. [[slnc 600]] A durable queue is not enough. [[slnc 300]] Each message must be marked persistent too.'),
    dict(key='04-act-2', kind='console', title='Act Two — Persistent and confirmed',
         body='TWO. Persistent and confirmed.\n  each send confirmed after storing\n  after restart: waiting 10',
         narration='Second demo: persistent messages, and publisher confirms. [[slnc 400]] Each email is now marked persistent. [[slnc 300]] And the sender waits for the broker to confirm it is stored. [[slnc 600]] The broker restarts. [[slnc 500]] All ten emails are still waiting.'),
    dict(key='05-act-3', kind='console', title='Act Three — Acknowledged after sending',
         body='THREE. Acknowledged after sending.\n  6 sent and acked; 4 waiting\n  10 of 10, each once',
         narration='Third demo: acknowledged after sending. [[slnc 400]] The email sender tells the broker each email is done, only after sending it. [[slnc 600]] It sends six, and stops. [[slnc 300]] Four are still waiting. [[slnc 500]] A new sender takes the rest. [[slnc 300]] Ten of ten, each sent once.'),
    dict(key='06-act-4', kind='console', title='Act Four — A crash before the acknowledgement',
         body='FOUR. A crash before the acknowledgement.\n  MAIL-11 redelivered\n  customer gets it 2 times',
         narration='Fourth demo: a crash before the acknowledgement. [[slnc 400]] The sender sends email eleven. [[slnc 300]] Then it dies, before saying it is done. [[slnc 600]] The broker puts the email back on the queue. [[slnc 300]] The next sender gets it again. [[slnc 300]] Marked as redelivered. [[slnc 500]] The customer receives it twice. [[slnc 500]] Guaranteed delivery means at least once. [[slnc 300]] The redelivered mark lets a receiver check first.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  a disk write and a confirm per email\n  one more system to run',
         narration='Fifth demo: the bill. [[slnc 400]] Every email now waits for a disk write, and a confirm, before checkout moves on. [[slnc 600]] And the broker is one more system to run, back up, and watch. [[slnc 300]] One broker is still one disk. [[slnc 300]] Production copies queues across several brokers.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in RabbitMQ',
         body=['A durable queue.', 'Persistent messages.', 'Publisher confirms.', 'Acknowledge after the work.'],
         narration="Let's name the pattern, in RabbitMQ's words. [[slnc 400]] A durable queue, which survives a restart. [[slnc 300]] Persistent messages, written to disk. [[slnc 500]] Publisher confirms, so the sender knows each message is stored. [[slnc 300]] And acknowledgements, sent only after the work is done."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Broker: RabbitMQ in a container', 'Outbox: sends, waits for confirms', 'EmailSender: sends, then acks', 'Poll: waits for real conditions'],
         narration='Here is who does what. [[slnc 400]] The broker class starts RabbitMQ in a container, and can restart it. [[slnc 500]] The outbox sends each email, and waits for the confirm. [[slnc 500]] The email sender sends each email, and then acknowledges it. [[slnc 300]] And poll waits for real conditions, never a fixed time.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['RabbitMQ confirms and acks', 'Kafka acks=all', 'Amazon SQS delete after processing'],
         narration="You have probably met this already. [[slnc 400]] RabbitMQ's confirms and acknowledgements. [[slnc 500]] Kafka, which waits for every copy of a message to be stored. [[slnc 500]] And Amazon SQS, where a message stays until the receiver deletes it."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Messages someone would miss:', 'orders, payments, emails.', '', 'All four settings.', 'Expect duplicates.', 'Replicate in production.'],
         narration='So, when should you use it? [[slnc 400]] For messages someone would miss. [[slnc 300]] Orders, payments, confirmations. [[slnc 500]] Use all four settings. [[slnc 300]] Expect duplicates, and make receivers cope. [[slnc 300]] And copy queues across brokers in production.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Skip redelivered', 'emails already sent.'],
         narration="That's Guaranteed Delivery, with RabbitMQ. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Store it, confirm it, and acknowledge it only when the work is done. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts the broker for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make the sender skip a redelivered email it has already sent. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Guaranteed Delivery with RabbitMQ Pattern  ·  Java 21', 'poster': {'headline': [('GUARANTEED DELIVERY', 'text'), ('WITH RABBITMQ', 'text')], 'before': {'code': 'messages not persistent', 'note': 'restart: 10 emails gone', 'tag': 'BEFORE'}, 'after': {'code': 'PERSISTENT + confirm + ack', 'note': 'restart: 10 still waiting', 'tag': 'AFTER'}, 'taglines': [('Persistent, confirmed, acknowledged', 'gold')]}, 'highlight': {}}
