"""Scene definitions for the Recipient List with Apache Camel teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Recipient List with Apache Camel',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Recipient List pattern, built with Apache Camel, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A recipient list works out, for each message, who should get it. [[slnc 300]] Then sends a copy to each of them, and to nobody else. [[slnc 500]] Apache Camel is an open-source library for moving messages, and it has this step built in. [[slnc 600]] Think of an office clerk who writes on each letter the names of the people it concerns. [[slnc 300]] The post room makes one copy per name. [[slnc 700]] In this video, the domain is an online shop, sending orders to its warehouses. [[slnc 500]] By the end, you will hear how Camel sends each order only where it is needed. [[slnc 300]] How rules add recipients. [[slnc 300]] And what happens when one recipient fails.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Orders went to every warehouse.', '', '5 orders x 4 warehouses', '= 20 deliveries.', '', 'Most were useless.'],
         narration='Here is the scenario. [[slnc 400]] The shop sent every order to every warehouse. [[slnc 500]] Five orders, four warehouses. [[slnc 300]] Twenty deliveries. [[slnc 500]] Most of them for items that warehouse did not even stock.'),
    dict(key='03-act-1', kind='console', title='Act One — Every order to every warehouse',
         body='ONE. Every order to every warehouse.\n  5 orders x 4 warehouses = 20 deliveries',
         narration="First demo: every order to every warehouse. [[slnc 400]] Camel's multicast sends a copy of each order to all four warehouses. [[slnc 600]] Five orders, four warehouses. [[slnc 300]] Twenty deliveries. [[slnc 300]] Most of them for items that warehouse does not even stock."),
    dict(key='04-act-2', kind='console', title='Act Two — A recipient list',
         body='TWO. A recipient list.\n  ORD-1 -> north, big-items\n  ORD-3 -> cold-store\n  deliveries: 10',
         narration='Second demo: a recipient list. [[slnc 400]] For each order, Camel asks the routing table who should get it. [[slnc 600]] O R D one holds kitchen items and furniture. [[slnc 300]] It goes to the north warehouse, and the big-items warehouse. [[slnc 500]] O R D three holds chilled food. [[slnc 300]] It goes to the cold store only. [[slnc 500]] Ten deliveries in all, instead of twenty.'),
    dict(key='05-act-3', kind='console', title='Act Three — Rules add recipients',
         body='THREE. Rules add recipients.\n  ORD-4 -> big-items, cold-store, fraud-review\n  ORD-2 -> north, gift-wrap',
         narration='Third demo: rules add recipients. [[slnc 400]] O R D four is worth six hundred and fifty pounds. [[slnc 300]] Over five hundred. [[slnc 300]] So fraud review gets a copy too. [[slnc 600]] O R D two is a gift. [[slnc 300]] So gift wrap gets a copy. [[slnc 500]] Camel did not change. [[slnc 300]] The table just returned more names.'),
    dict(key='06-act-4', kind='console', title='Act Four — The table changes while running',
         body='FOUR. The table changes while running.\n  ORD-5 -> south, cold-store\n  no route changed',
         narration='Fourth demo: the table changes while the shop runs. [[slnc 400]] The north warehouse closes for stocktake. [[slnc 300]] Kitchen items now come from south. [[slnc 600]] O R D five now reaches south, and the cold store. [[slnc 500]] No route was changed. [[slnc 300]] Nothing was restarted.'),
    dict(key='07-act-5', kind='console', title='Act Five — One recipient fails',
         body='FIVE. One recipient fails.\n  Camel reports: big-items is unreachable\n  ORD-1 still reached [south]',
         narration="Fifth demo: the bill. [[slnc 400]] The big-items warehouse cannot be reached. [[slnc 600]] O R D one is sent. [[slnc 300]] The south warehouse gets its copy. [[slnc 300]] Big items fails. [[slnc 500]] Camel reports the failure. [[slnc 300]] But half the order is already out. [[slnc 600]] Retrying, or undoing the half that went out, is still the shop's job."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Camel',
         body=['recipientList() asks a table', 'for each message.', '', 'The table returns addresses.', '', 'Camel sends one copy to each.'],
         narration="Let's name the pattern, in Camel's words. [[slnc 400]] The recipient list step asks a routing table, for each message. [[slnc 500]] The table returns a list of addresses. [[slnc 500]] And Camel sends one copy to each address."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShopRoutes: the routes', 'RoutingTable: who gets what', 'Warehouses: the destinations', 'Order: the message'],
         narration="Here is who does what. [[slnc 400]] Shop routes holds the routes. [[slnc 500]] The routing table decides who gets each order. [[slnc 300]] That part is plain Java, because it is the shop's business. [[slnc 500]] The warehouses are the destinations. [[slnc 300]] And the order is the message."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel recipientList()', 'Spring Integration routers', 'Email To and Cc', 'Warehouse order splitting'],
         narration="You have probably met this already. [[slnc 400]] Camel's recipient list, and Spring Integration's recipient list router. [[slnc 500]] The To and Cc lines of an email, chosen for each message. [[slnc 500]] And order systems that split each order across warehouses."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Who needs a message depends', 'on what is in it.', '', 'Keep the table in plain code.', 'Plan for a failed recipient.'],
         narration='So, when should you use it? [[slnc 400]] When who needs a message depends on what is in it. [[slnc 500]] Keep the routing table in plain code. [[slnc 300]] And decide in advance what happens when one recipient fails.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Send failed', 'copies to a retry route.'],
         narration="That's the Recipient List, with Apache Camel. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Work out who needs each message, and send it only to them. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Send failed copies to a retry route, instead of failing the whole order. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Recipient List with Apache Camel Pattern  ·  Java 21', 'poster': {'headline': [('RECIPIENT LIST', 'text'), ('WITH CAMEL', 'text')], 'before': {'code': 'multicast() to all 4', 'note': '20 deliveries', 'tag': 'BEFORE'}, 'after': {'code': 'recipientList(method(table))', 'note': 'only where needed: 10', 'tag': 'AFTER'}, 'taglines': [('Only where it is needed', 'gold')]}, 'highlight': {}}
