"""Scene definitions for the Entity teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Entity',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Entity pattern, from domain-driven design, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] An entity is something defined by who it is, not by its current details. [[slnc 300]] It gets an identity that never changes. [[slnc 300]] Its details can change, and it is still the same thing. [[slnc 600]] Think of a car. [[slnc 300]] Over the years it gets a new colour, new plates, and a new owner. [[slnc 300]] It is still the same car, because its chassis number, stamped in at the factory, never changes. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Its customers change their emails, earn points, and sometimes share a name with someone else. [[slnc 500]] By the end, you will hear how comparing customers by their values goes wrong. [[slnc 300]] How an identity fixes it. [[slnc 300]] How look-alikes stay apart. [[slnc 300]] And what equality does not tell you.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Customers change their email.', 'They earn points.', 'Some share a name and an email.', '', 'Customers were records,', 'compared by every field.'],
         narration='Here is the scenario. [[slnc 400]] Customers change their email. [[slnc 300]] They earn loyalty points. [[slnc 300]] Some share a name, and even an email, with someone in their family. [[slnc 600]] The shop kept customers as records. [[slnc 300]] Two records are equal when every field is equal.'),
    dict(key='03-act-1', kind='console', title='Act One — Defined by values',
         body='ONE. Defined by values.\n  old and new records equal: false\n  her orders by the new record: null\n  mailing list: 2, both Priya',
         narration='First demo: a customer defined by its values. [[slnc 400]] The customer is a record, compared by every field: name, email, and points. [[slnc 600]] Priya changes her email. [[slnc 300]] Now the old record and the new one are not equal. [[slnc 500]] Her orders were stored under the old record. [[slnc 300]] Looked up with the new one: nothing found. [[slnc 500]] And the mailing list now has two customers. [[slnc 300]] Both of them are Priya.'),
    dict(key='04-act-2', kind='console', title='Act Two — Defined by identity',
         body='TWO. Defined by identity.\n  C-17 Priya <priya@new.example>\n  her orders: ORD-1, ORD-2\n  mailing list: 1',
         narration='Second demo: an entity, a customer defined by its identity. [[slnc 400]] The customer now has an ID, C 17, given when the account was opened. [[slnc 500]] Two customer objects are equal when their IDs are equal. [[slnc 300]] Nothing else is compared. [[slnc 600]] Priya changes her email. [[slnc 300]] She is still C 17. [[slnc 300]] Her orders are found. [[slnc 300]] And the mailing list holds one customer.'),
    dict(key='05-act-3', kind='console', title='Act Three — Look-alikes are different',
         body='THREE. Look-alikes are different.\n  as records, equal: true\n  as entities C-42 and C-43: false',
         narration='Third demo: two people who look the same are still two people. [[slnc 400]] A father and his son are both called Tom Reed. [[slnc 300]] They share a family email. [[slnc 600]] As records, they are equal. [[slnc 300]] The shop would mix up their orders. [[slnc 500]] As entities, they are C 42 and C 43. [[slnc 300]] Two different customers.'),
    dict(key='06-act-4', kind='console', title='Act Four — A life story',
         body='FOUR. A life story.\n  opened with priya@old.example\n  -> priya@new.example -> priya@work.example\n  one customer, 80 points, same ID',
         narration="Fourth demo: an entity has a life story. [[slnc 400]] Priya's account was opened with her old email. [[slnc 300]] Then she changed it. [[slnc 300]] Then she changed it again, to her work email. [[slnc 300]] She earned eighty points along the way. [[slnc 600]] Three emails. [[slnc 300]] One customer. [[slnc 300]] The ID never changed."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  cached copy equals live: true\n  but emails differ',
         narration='Fifth demo: the bill. [[slnc 400]] Equal is not the same as up to date. [[slnc 500]] A cached copy of Priya, and the live Priya, are equal. [[slnc 300]] They share the same ID. [[slnc 300]] But the copy has an old email, and the live one a new email. [[slnc 600]] And every entity needs an ID that is unique, and never reused.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Give it an identity, once.', '', 'Never change the identity.', '', 'Compare by identity only;', 'let everything else change.'],
         narration="Let's name the pattern. [[slnc 400]] Give each customer an identity when it is created. [[slnc 300]] A customer ID. [[slnc 500]] Never change it. [[slnc 500]] Compare customers by that identity only. [[slnc 300]] Everything else, the email, the points, is free to change."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['CustomerId: the identity', 'Customer: the entity', 'equals, hashCode: the ID only', 'CustomerRecord: the old way'],
         narration='Here is who does what. [[slnc 400]] Customer ID is the identity: a small value that never changes. [[slnc 500]] Customer is the entity. [[slnc 300]] It holds the ID, and details that change, and a history of those changes. [[slnc 500]] Its equals and hash code look at the ID only. [[slnc 300]] And customer record is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['JPA @Entity with @Id', 'Database primary keys', 'Order numbers, account numbers', 'equals over the id field'],
         narration='You have probably met this pattern already. [[slnc 400]] J P A entities have an ID field. [[slnc 300]] Database tables have a primary key. [[slnc 500]] Order numbers, account numbers, and parcel tracking numbers are all identities of entities. [[slnc 500]] And any equals method that compares only an ID is treating its class as an entity.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Things followed one by one', 'through time: customers,', 'orders, parcels.', '', 'Everything else: values.'],
         narration='So, when should you use it? [[slnc 400]] For things the business follows one by one, through time. [[slnc 300]] Customers, orders, parcels. [[slnc 500]] For things where only the value matters, such as an amount of money or an address, use a value object instead. [[slnc 300]] Ten pounds is ten pounds, whichever coins.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Make Order an entity', 'with its own ID.'],
         narration="That's the Entity pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Some things are who they are, not what they currently look like. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make the order an entity, with its own order ID. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Entity Pattern  ·  Java 21', 'poster': {'headline': [('ENTITY', 'text')], 'before': {'code': 'equals: every field', 'note': 'new email, new person', 'tag': 'BEFORE'}, 'after': {'code': 'equals: same id', 'note': 'C-17 for life', 'tag': 'AFTER'}, 'taglines': [('Same thing, even when it changes', 'gold')]}, 'highlight': {}}
