"""Scene definitions for the Page Controller with Spring MVC teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Page Controller with Spring MVC',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Page Controller pattern, with Spring MVC, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A page controller gives each page of a web application its own controller. [[slnc 300]] It reads that page's input, does that page's work, and handles that page's errors. [[slnc 500]] Spring MVC is the open-source web framework most Java applications use. [[slnc 600]] Think of a department store, with a counter for each department. [[slnc 300]] Each counter answers its own questions. [[slnc 300]] The front doors, where bags are checked, are shared. [[slnc 700]] In this video, the domain is an online shop's pages: product, basket, reviews and checkout. [[slnc 500]] By the end, you will hear why one handler for every page breaks. [[slnc 300]] How Spring finds a controller for each page. [[slnc 300]] And where checks every page needs should live."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['One handler served every page.', '', 'Basket code ran for every page.', '', 'Each new page edited', 'the shared handler.'],
         narration='Here is the scenario. [[slnc 400]] One handler served every page of the shop. [[slnc 500]] Code added for the basket ran for every page, and the product page crashed. [[slnc 500]] And each new page meant editing the one handler everyone shared.'),
    dict(key='03-act-1', kind='console', title='Act One — One handler for every page',
         body='ONE. One handler for every page.\n  /old/basket: 200\n  /old/product: 500',
         narration='First demo: one handler for every page. [[slnc 400]] The basket works. [[slnc 600]] But the code that reads the quantity was added at the top, for the basket. [[slnc 300]] It runs for every page. [[slnc 500]] The product page has no quantity. [[slnc 300]] It crashes, with a server error.'),
    dict(key='04-act-2', kind='console', title='Act Two — A controller per page',
         body='TWO. A controller per page.\n  /product: 200 steel kettle, £30.00\n  /basket: 200 basket: 2 x MUG-1',
         narration='Second demo: a controller for each page. [[slnc 400]] The product page has its own class. [[slnc 300]] So does the basket. [[slnc 600]] The kettle costs thirty pounds. [[slnc 300]] The basket holds two mugs. [[slnc 500]] Neither page knows about the other.'),
    dict(key='05-act-3', kind='console', title='Act Three — Input checked by Spring',
         body='THREE. Input checked by Spring.\n  SOFA-9: 404\n  qty=two: 400',
         narration="Third demo: each page's input, checked by Spring. [[slnc 400]] An unknown product. [[slnc 300]] Not found. [[slnc 600]] A quantity written as the word two. [[slnc 300]] Bad request. [[slnc 300]] Spring could not turn it into a number. [[slnc 300]] The basket page wrote no code for that."),
    dict(key='06-act-4', kind='console', title='Act Four — A new page',
         body='FOUR. A new page.\n  /reviews: 200, 4.5 stars',
         narration='Fourth demo: a new page. [[slnc 400]] Reviews are added as one new class. [[slnc 600]] Spring finds it by its annotation. [[slnc 300]] Four and a half stars, from twelve customers. [[slnc 500]] No other page was touched.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill, and an interceptor',
         body='FIVE. The bill, and an interceptor.\n  /checkout, logged out: 200\n  with interceptor: 401',
         narration="Fifth demo: the bill. [[slnc 400]] Some checks every page needs. [[slnc 300]] The checkout page's author forgot the login check. [[slnc 300]] Anyone can see it. [[slnc 600]] Spring has a place for shared checks, called an interceptor. [[slnc 300]] It is registered once, for the basket and the checkout. [[slnc 500]] Not logged in. [[slnc 300]] Please log in. [[slnc 300]] Logged in. [[slnc 300]] The checkout page."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Spring MVC',
         body=['@RestController per page.', '@GetMapping for its path.', '', 'Spring converts the input.', '', 'An interceptor for shared checks.'],
         narration="Let's name the pattern, in Spring's words. [[slnc 400]] A rest controller for each page, with a get mapping for its path. [[slnc 500]] Spring converts each page's input, and answers bad request when it cannot. [[slnc 500]] And an interceptor holds the checks many pages share."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ProductController, BasketController', 'ReviewsController, CheckoutController', 'LoginInterceptor: the shared check', 'OldFrontHandler: the old way'],
         narration='Here is who does what. [[slnc 400]] Product, basket, reviews and checkout each have their own controller. [[slnc 500]] The login interceptor checks login, before the pages that need it. [[slnc 500]] And the old front handler is the old way, one handler for everything.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Spring @Controller classes', 'PHP, JSP, Razor Pages', 'Django and Rails controllers'],
         narration='You have probably met this already. [[slnc 400]] Spring controller classes. [[slnc 500]] PHP files, Java server pages, and Razor pages, one file per page. [[slnc 500]] And the controllers of Django and Rails.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Pages with their own input,', 'logic and errors.', '', 'Let Spring check input.', 'Shared checks in one place.'],
         narration='So, when should you use it? [[slnc 400]] When pages grow their own input, logic and errors. [[slnc 500]] Let Spring check the input. [[slnc 300]] And put every shared check in one place, never in each page.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a', 'wishlist page.'],
         narration="That's the Page Controller, with Spring MVC. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Each page its own controller, and every shared check in one place. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a wishlist page, as a new controller. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Page Controller with Spring MVC Pattern  ·  Java 21', 'poster': {'headline': [('PAGE CONTROLLER', 'text'), ('WITH SPRING MVC', 'text')], 'before': {'code': 'one handler, every page', 'note': 'product page: 500', 'tag': 'BEFORE'}, 'after': {'code': '@GetMapping("/product")', 'note': 'one controller per page', 'tag': 'AFTER'}, 'taglines': [('A controller per page', 'gold')]}, 'highlight': {}}
