"""Scene definitions for the Space-Based Architecture with Hazelcast teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Space-Based Architecture with Hazelcast',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Space-Based Architecture, built with Hazelcast, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] In a space-based design, the data lives in the memory of the processing units themselves. [[slnc 300]] So busy moments never wait for a database. [[slnc 300]] The database is written later, in the background. [[slnc 500]] Hazelcast is an open-source in-memory data grid: several programs that share data as one. [[slnc 600]] Think of market stalls sharing one stock of goods. [[slnc 300]] Each item is looked after by one stall, with a partner keeping a note in case it closes. [[slnc 300]] The warehouse ledger is updated once an hour. [[slnc 700]] In this video, the domain is an online shop's flash sale of kettles. [[slnc 500]] By the end, you will hear why the database was the bottleneck. [[slnc 300]] How a real grid holds the stock. [[slnc 300]] How it sells the last kettle only once. [[slnc 300]] And what happens when a unit crashes."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A flash sale: hundreds of', 'kettle orders a second.', '', 'Every order wrote to the database.', '', 'More servers, same queue.'],
         narration='Here is the scenario. [[slnc 400]] A flash sale sends hundreds of kettle orders a second. [[slnc 500]] Every order wrote the stock to the database, one at a time. [[slnc 500]] More app servers only made more of them wait in the same queue.'),
    dict(key='03-act-1', kind='console', title='Act One — One database for everyone',
         body='ONE. One database for everyone.\n  300 orders: over 1.4 s',
         narration='First demo: one database for everyone. [[slnc 400]] Every order writes the stock to the database, one at a time. [[slnc 600]] Three hundred kettle orders take more than one and a half seconds. [[slnc 500]] More app servers would not help. [[slnc 300]] They would only queue for the same database.'),
    dict(key='04-act-2', kind='console', title='Act Two — Stock in the grid',
         body='TWO. Stock in the grid.\n  cluster formed: 3 members\n  300 orders: under 1 s, 0 database writes',
         narration='Second demo: the stock lives in the grid. [[slnc 400]] Three Hazelcast members start, and form a cluster. [[slnc 600]] The stock is held in their memory. [[slnc 500]] Three hundred orders, spread over the three units, take less than a second. [[slnc 300]] Not one of them waits for the database.'),
    dict(key='05-act-3', kind='console', title='Act Three — One grid, not three copies',
         body='THREE. One grid, not three copies.\n  stock on each unit: 700, 700, 700',
         narration='Third demo: one grid, not three copies. [[slnc 400]] Every unit reads the same stock. [[slnc 300]] Seven hundred. [[slnc 600]] Each item has one owner in the grid. [[slnc 300]] With a backup copy on another member. [[slnc 300]] Every unit asks the owner.'),
    dict(key='06-act-4', kind='console', title='Act Four — Write-behind',
         body='FOUR. Write-behind.\n  database: 700, after at most 3 writes',
         narration='Fourth demo: the database catches up, in the background. [[slnc 400]] Hazelcast writes the database a little later. [[slnc 300]] And only the latest value. [[slnc 600]] Three hundred sales become at most three database writes. [[slnc 300]] The database now says seven hundred. [[slnc 500]] No customer waited for any of them.'),
    dict(key='07-act-5', kind='console', title='Act Five — The last kettle, a crash, and the bill',
         body='FIVE. The last kettle, a crash, and the bill.\n  last kettle: sold 1 of 2; stock 0\n  unit 3 crashes: stock still 700\n  memory, a cluster, write-behind risk',
         narration="Fifth demo: the last kettle, and a crash. [[slnc 400]] One kettle is left. [[slnc 300]] Two customers try for it, on two units, at the same moment. [[slnc 600]] The sale runs on the member that owns the kettle, one at a time. [[slnc 300]] One succeeds. [[slnc 300]] The other is refused. [[slnc 600]] Then unit three crashes. [[slnc 300]] Its backup copies take over. [[slnc 300]] Nothing is lost. [[slnc 600]] The bill. [[slnc 300]] Data in every unit's memory. [[slnc 300]] A cluster to run. [[slnc 300]] And if the whole grid stops before the database is written, the latest sales are gone."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Hazelcast',
         body=["Data in the grid's memory.", 'One owner per key, one backup.', '', 'Changes run on the owner.', 'The database written behind.'],
         narration="Let's name the pattern, in Hazelcast's words. [[slnc 400]] The data lives in the grid's memory. [[slnc 300]] Each item has one owner, and one backup. [[slnc 500]] Changes run on the owner, one at a time. [[slnc 500]] And the database is written behind, in the background."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Grid: three Hazelcast members', 'SellOne: the sale, run on the owner', 'StockStore: writes the database later', 'SlowDatabase: the old bottleneck'],
         narration='Here is who does what. [[slnc 400]] The grid is three Hazelcast members, the processing units. [[slnc 500]] Sell one is the sale, run on the member that owns the item. [[slnc 500]] The stock store writes the database later. [[slnc 300]] And the slow database is the old bottleneck.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Hazelcast, Ignite, Coherence', 'Ticket and trading systems', 'Caches with write-behind'],
         narration='You have probably met this already. [[slnc 400]] Data grids such as Hazelcast, Apache Ignite, and Oracle Coherence. [[slnc 500]] Ticket booking and trading systems, which keep their busiest data in a grid. [[slnc 500]] And caches that write to a database behind the scenes.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Bursts a database cannot absorb.', '', 'Entry processors for changes.', 'At least one backup.', 'Write-behind trades durability.'],
         narration='So, when should you use it? [[slnc 400]] For bursts of load that a single database cannot absorb. [[slnc 500]] Change data with entry processors. [[slnc 300]] Keep at least one backup. [[slnc 300]] And remember that writing behind trades durability for speed.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Set backups', 'to 0 and crash a unit.'],
         narration="That's Space-Based Architecture, with Hazelcast. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Keep the busy data in a grid, change it where it lives, and write the database behind. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Set the backup count to zero, and crash a unit. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Space-Based Architecture with Hazelcast Pattern  ·  Java 21', 'poster': {'headline': [('SPACE-BASED', 'text'), ('WITH HAZELCAST', 'text')], 'before': {'code': 'every order -> database', 'note': '300 orders: over 1.4 s', 'tag': 'BEFORE'}, 'after': {'code': 'executeOnKey(sku, SellOne)', 'note': 'under 1 s, last kettle sold once', 'tag': 'AFTER'}, 'taglines': [('A real data grid', 'gold')]}, 'highlight': {}}
