"""Scene definitions for the Routing Slip teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Routing Slip',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Routing Slip pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] With a routing slip, the steps a message needs are worked out once, when it arrives. [[slnc 300]] The list is attached to the message. [[slnc 300]] Each step does its work, and passes the message to the next step on the list. [[slnc 600]] Think of the circulation slip clipped to a magazine in an office. [[slnc 300]] Pass to Anna, then Ben, then Carl. [[slnc 300]] Each person reads it, crosses their name off, and passes it on. [[slnc 300]] Nobody needs to know the whole list. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Its orders need different steps: gift wrap for gifts, age checks for knives, customs for orders abroad. [[slnc 500]] By the end, you will hear what a fixed pipeline wastes. [[slnc 300]] How routing slips fix it. [[slnc 300]] How to add a step. [[slnc 300]] And what a slip cannot do.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['validate, age check, customs,', 'charge, gift wrap, pack.', '', 'Most orders need only some.', '', 'Every order went through all six.'],
         narration='Here is the scenario. [[slnc 400]] The shop has six processing steps. [[slnc 300]] Validate, age check, customs, charge, gift wrap, and pack. [[slnc 600]] Most orders need only some of them. [[slnc 500]] But every order went through all six, one after another.'),
    dict(key='03-act-1', kind='console', title='Act One — One fixed pipeline',
         body='ONE. One fixed pipeline.\n  4 orders x 6 steps = 24 visits\n  15 did any work',
         narration='First demo: one fixed pipeline, for every order. [[slnc 400]] Six steps. [[slnc 300]] Validate, age check, customs, charge, gift wrap, and pack. [[slnc 600]] Four orders go through all six. [[slnc 300]] Twenty-four visits. [[slnc 300]] Only fifteen did any work. [[slnc 500]] A UK order needs no customs. [[slnc 300]] A plain order needs no gift wrap. [[slnc 300]] So every step starts by asking: does this even apply to me?'),
    dict(key='04-act-2', kind='console', title='Act Two — Routing slips',
         body='TWO. Routing slips.\n  ORD-1: validate, charge, pack\n  ORD-2: + gift-wrap\n  ORD-3: + age-check; ORD-4: + customs',
         narration='Second demo: a routing slip. [[slnc 400]] As each order enters, its route is worked out once, and attached to it. [[slnc 600]] Order one is a plain UK order: validate, charge, pack. [[slnc 300]] Order two is a gift: gift wrap is added. [[slnc 300]] Order three is age restricted: an age check is added. [[slnc 300]] Order four is going to France: customs is added.'),
    dict(key='05-act-3', kind='console', title='Act Three — Steps pass it on',
         body='THREE. Steps pass it on.\n  15 visits, every one doing work\n  ORD-2: validate, charge, gift-wrap, pack',
         narration='Third demo: each step does its job, and passes the order to the next name on the slip. [[slnc 400]] Order two goes: validate, charge, gift wrap, pack. [[slnc 600]] Fifteen visits in all. [[slnc 300]] Every one does work. [[slnc 500]] And no step knows which step comes after it.'),
    dict(key='06-act-4', kind='console', title='Act Four — A new step',
         body='FOUR. A new step.\n  ORD-4: validate, customs, fraud-check,\n         charge, pack\n  ORD-1: unchanged',
         narration="Fourth demo: a new step. [[slnc 400]] Orders over five hundred pounds now need a fraud check. [[slnc 500]] One rule is added, where the slips are written. [[slnc 300]] Order four is worth six hundred and twenty pounds, so its slip gains a fraud check, before charge. [[slnc 500]] Order one's slip is unchanged. [[slnc 300]] No step was changed at all."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  ORD-5 stopped at age-check\n  still on the slip: [charge, pack]\n  cannot re-route: use a process manager',
         narration='Fifth demo: the bill. [[slnc 400]] The route is fixed when the order sets off. [[slnc 500]] Order five, a kitchen knife, fails its age check. [[slnc 300]] The route stops there, with charge and pack still on the slip. [[slnc 600]] It cannot choose a new route, such as: ask for ID, then carry on. [[slnc 300]] That needs a process manager.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['When a message enters:', 'write its list of steps.', '', 'Attach the list to the message.', '', 'Each step: do the work, pass to', 'the next step on the list.'],
         narration="Let's name the pattern. [[slnc 400]] When a message enters, write down the list of steps it needs. [[slnc 500]] Attach the list to the message. [[slnc 300]] That is its routing slip. [[slnc 500]] Each step does its work, and passes the message to the next step on the slip. [[slnc 300]] No step needs to know what comes after it."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['RoutingSlip: writes slips, runs steps', 'OrderMessage: carries its slip', 'Steps: one job each', 'FixedPipeline: the old way'],
         narration="Here is who does what. [[slnc 400]] The routing slip class writes each order's slip, and runs its steps in turn. [[slnc 500]] The order message carries its slip, and a record of where it has been. [[slnc 500]] The steps each do one job. [[slnc 300]] And the fixed pipeline is the old way, kept for comparison."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel routingSlip', 'Approval workflows with a list', 'of approvers', 'Office circulation slips'],
         narration='You have probably met this pattern already. [[slnc 400]] Apache Camel has a routing slip step. [[slnc 500]] Approval workflows often attach a list of approvers to a document. [[slnc 500]] And offices have used circulation slips for as long as there have been offices.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Different messages, different', 'but predictable steps.', '', 'Slip rules in one place.', '', 'Route must change on the way?', 'Use a process manager.'],
         narration='So, when should you use it? [[slnc 400]] When different messages need different, but predictable, sequences of steps. [[slnc 500]] Keep the rules that write slips in one place. [[slnc 300]] Keep the steps independent. [[slnc 500]] And when the route must change, depending on what happens along the way, use a process manager instead.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a loyalty-points', 'step.'],
         narration="That's the Routing Slip pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let each message carry its own route, and each step just pass it on. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a loyalty points step, for registered customers only. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Routing Slip Pattern  ·  Java 21', 'poster': {'headline': [('ROUTING', 'text'), ('SLIP', 'text')], 'before': {'code': '6 steps for every order', 'note': '24 visits, 15 useful', 'tag': 'BEFORE'}, 'after': {'code': '[validate, charge, pack]', 'note': 'only its own steps', 'tag': 'AFTER'}, 'taglines': [('The message carries its own route', 'gold')]}, 'highlight': {}}
