"""Scene definitions for the Scheduler teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Scheduler',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Scheduler pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] When many threads wait for one shared resource, a scheduler decides whose turn comes next. [[slnc 300]] It follows a policy, such as most urgent first. [[slnc 300]] And the policy can be swapped, without touching anything else. [[slnc 600]] Think of the triage nurse in a hospital's emergency department. [[slnc 300]] Patients are not seen in the order they walked in. [[slnc 300]] The nurse decides, by urgency. [[slnc 300]] And someone who has waited a very long time is eventually moved up. [[slnc 700]] In this video, the domain is an online shop's warehouse. [[slnc 300]] Six packing stations share one label printer. [[slnc 300]] Express orders must catch the afternoon van. [[slnc 500]] By the end, you will hear why a lock alone serves the wrong job first. [[slnc 300]] How a scheduler fixes it. [[slnc 300]] How to swap the policy. [[slnc 300]] And how to make sure nobody waits for ever."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['One label printer.', 'Six packing stations.', '', 'Express orders must catch', 'the afternoon van.', '', 'A fair lock guarded the printer.'],
         narration='Here is the scenario. [[slnc 400]] The warehouse has one label printer, and six packing stations. [[slnc 500]] Some orders are express, and must catch the afternoon van. [[slnc 500]] The printer was guarded by a fair lock. [[slnc 300]] A fair lock serves whoever arrived first.'),
    dict(key='03-act-1', kind='console', title='Act One — A fair lock',
         body='ONE. A fair lock.\n  printed: STD-1, STD-2, STD-3,\n           EXP-1, EXP-2, EXP-3',
         narration='First demo: a fair lock, first come, first served. [[slnc 400]] The printer is busy with a bulk job. [[slnc 300]] Three standard jobs arrive. [[slnc 300]] Then three express jobs. [[slnc 600]] The lock serves them in the order they arrived. [[slnc 300]] Standard one, two, three. [[slnc 300]] Then express one, two, three. [[slnc 500]] The express orders waited behind every standard order, and may miss the van.'),
    dict(key='04-act-2', kind='console', title='Act Two — Express first',
         body='TWO. Express first.\n  printed: EXP-1, EXP-2, EXP-3,\n           STD-1, STD-2, STD-3',
         narration='Second demo: a scheduler, with an express-first policy. [[slnc 400]] Each station asks the scheduler for its turn, and waits. [[slnc 500]] When the printer is free, the policy chooses who goes next. [[slnc 600]] Express one, two, three. [[slnc 300]] Then standard one, two, three.'),
    dict(key='05-act-3', kind='console', title='Act Three — A replaceable policy',
         body='THREE. A replaceable policy.\n  smallest first:\n  STD-2, EXP-2, STD-3, EXP-3, EXP-1, STD-1',
         narration='Third demo: the policy is replaceable. [[slnc 400]] Swap in a different rule: smallest job first. [[slnc 500]] The jobs with the fewest labels print first, whatever their type. [[slnc 500]] One line changed. [[slnc 300]] The stations and the printer did not.'),
    dict(key='06-act-4', kind='console', title='Act Four — Nobody waits for ever',
         body='FOUR. Nobody waits for ever.\n  express only: STD-1 printed last\n  promote after 3: STD-1 printed 4th',
         narration='Fourth demo: nobody waits for ever. [[slnc 400]] One standard job arrives. [[slnc 300]] Then a rush of five express jobs. [[slnc 600]] With express first alone, the standard job goes last. [[slnc 300]] In a longer rush, it would never print. [[slnc 500]] Now add a rule: a job overtaken three times moves to the front. [[slnc 300]] The standard job prints fourth.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  lock, list, wake, check: every job\n  every priority needs a guard',
         narration="Fifth demo: the bill. [[slnc 400]] Someone has to decide, every time. [[slnc 300]] Each job takes the scheduler's lock, joins its list, and is woken to check whether it is next. [[slnc 600]] And every priority rule needs a guard, so the jobs it does not favour are never starved."),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Threads ask the scheduler for a turn.', '', 'When the resource is free,', 'the policy picks who is next.', '', 'Age long waiters so nobody', 'starves.'],
         narration="Let's name the pattern. [[slnc 400]] Each thread asks the scheduler for its turn, and waits. [[slnc 500]] When the resource is free, the policy picks who goes next. [[slnc 300]] The policy is a simple rule, kept in one place. [[slnc 500]] And long waiters are aged, so nobody is starved."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Scheduler: enter, done, the waiting list', 'Policy: a comparator', 'PrintJob: express or not, size, age', 'Printer: the shared resource', 'Fair lock: the old way'],
         narration='Here is who does what. [[slnc 400]] The scheduler keeps the waiting list. [[slnc 300]] Stations call enter, and done. [[slnc 500]] The policy is a comparator: express first, or smallest first. [[slnc 500]] A print job knows if it is express, how many labels it has, and how often it has been overtaken. [[slnc 500]] The printer is the shared resource. [[slnc 300]] And the fair lock is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Operating system CPU schedulers', 'PriorityBlockingQueue + a worker', 'Print queues, build servers', 'Kubernetes pod priority'],
         narration='You have probably met this pattern already. [[slnc 400]] Your operating system schedules which program runs on the processor next. [[slnc 500]] A priority blocking queue in front of one worker thread does the same job. [[slnc 500]] Print queues and build servers schedule their jobs. [[slnc 300]] And Kubernetes schedules containers by priority.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['The order of access matters,', 'and may change.', '', 'Policy in one comparator.', 'Age long waiters.', '', 'Callers need not wait? A priority queue.'],
         narration='So, when should you use it? [[slnc 400]] When the order of access to a shared resource matters, and may change. [[slnc 500]] Keep the policy in one comparator. [[slnc 300]] Age long waiters, so nobody starves. [[slnc 500]] And when callers do not need to wait for their turn, a priority queue and one worker thread is simpler.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a deadline', 'policy.'],
         narration="That's the Scheduler pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let a policy decide who goes next, and make sure nobody waits for ever. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Give each job a deadline, and print the one closest to its deadline first. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Scheduler Pattern  ·  Java 21', 'poster': {'headline': [('SCHEDULER', 'text')], 'before': {'code': 'new ReentrantLock(true)', 'note': 'express printed last', 'tag': 'BEFORE'}, 'after': {'code': 'scheduler.enter(job)', 'note': 'express first, nobody starves', 'tag': 'AFTER'}, 'taglines': [('A policy decides who goes next', 'gold')]}, 'highlight': {}}
