"""Scene definitions for the Recipient List teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Recipient List',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Recipient List pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A recipient list works out, for each message, exactly which destinations need it. [[slnc 300]] Then it sends a copy to each of them, and to no one else. [[slnc 600]] Think of an office post room. [[slnc 300]] A letter about a supplier contract arrives. [[slnc 300]] The routing sheet says: contracts to legal, prices to accounts, and big amounts to the finance director too. [[slnc 300]] One copy each, and nobody else is bothered. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] It ships from four warehouses, each handling different kinds of product. [[slnc 500]] By the end, you will hear what sending everything everywhere costs. [[slnc 300]] How a recipient list fixes it. [[slnc 300]] How rules and tables change the list. [[slnc 300]] And what happens when one recipient is down.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['north: kitchen items', 'big-items: furniture', 'cold-store: chilled food', 'south: a spare', '', 'Every order went to all four.'],
         narration='Here is the scenario. [[slnc 400]] The shop has four warehouses. [[slnc 300]] North handles kitchen items. [[slnc 300]] Big-items handles furniture. [[slnc 300]] The cold store handles chilled food. [[slnc 300]] And south is a spare. [[slnc 600]] One order can contain items for several of them. [[slnc 300]] So every order was sent to all four.'),
    dict(key='03-act-1', kind='console', title='Act One — Everything everywhere',
         body='ONE. Everything everywhere.\n  5 orders x 4 warehouses = 20 deliveries\n  8 of them needed',
         narration='First demo: every order sent to every warehouse. [[slnc 400]] Five orders, four warehouses. [[slnc 300]] Twenty deliveries. [[slnc 600]] Only eight were needed. [[slnc 500]] Every warehouse sorts through orders it has nothing to do with.'),
    dict(key='04-act-2', kind='console', title='Act Two — A recipient list',
         body='TWO. A recipient list.\n  ORD-1 [kitchen, furniture] -> north, big-items\n  ORD-3 [chilled] -> cold-store\n  deliveries: 8',
         narration='Second demo: a recipient list. [[slnc 400]] For each order, the list looks at what is in it, and works out who needs it. [[slnc 600]] Order one has kitchen items and furniture. [[slnc 300]] It goes to north, and big-items. [[slnc 300]] Order three is chilled food. [[slnc 300]] It goes to the cold store. [[slnc 600]] Eight deliveries. [[slnc 300]] Exactly the ones needed.'),
    dict(key='05-act-3', kind='console', title='Act Three — Rules add recipients',
         body='THREE. Rules add recipients.\n  ORD-4 (£650) -> big-items, cold-store,\n                  fraud-review\n  ORD-2 (gift) -> north, gift-wrap',
         narration='Third demo: rules can add recipients. [[slnc 400]] Orders over five hundred pounds also go to fraud review. [[slnc 300]] Gift orders also go to gift wrap. [[slnc 600]] Order four is worth six hundred and fifty pounds. [[slnc 300]] It goes to big-items, the cold store, and fraud review. [[slnc 500]] Order two is a gift. [[slnc 300]] It goes to north, and gift wrap.'),
    dict(key='06-act-4', kind='console', title='Act Four — A changed table',
         body='FOUR. A changed table.\n  kitchen -> south (north closed)\n  ORD-5 -> south, cold-store',
         narration='Fourth demo: the table changes while the shop runs. [[slnc 400]] North closes for a stocktake. [[slnc 300]] Kitchen items now come from south. [[slnc 600]] Order five goes to south, and the cold store. [[slnc 500]] Checkout was not changed at all.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  ORD-1 reached [south]\n  failed [big-items]: half an order',
         narration='Fifth demo: the bill. [[slnc 400]] The big-items warehouse is unreachable. [[slnc 500]] Order one reaches south, but not big-items. [[slnc 300]] Half the order is out. [[slnc 600]] The recipient list must retry, or undo. [[slnc 300]] And it must know every destination, and what each one does.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['For each message, build the list', 'of destinations that need it:', '', 'from its contents, a table,', 'and rules.', '', 'Send one copy to each.'],
         narration="Let's name the pattern. [[slnc 400]] For each message, build the list of destinations that need it. [[slnc 500]] The list comes from what the message contains, from a table, and from rules. [[slnc 500]] Then send one copy to each destination on the list. [[slnc 300]] And the sender never needs to know who they are."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['RecipientList: table, rules, send', 'Order: categories, value, gift', 'Inboxes: the destinations'],
         narration='Here is who does what. [[slnc 400]] The recipient list holds a table from category to warehouse, and a list of rules. [[slnc 300]] It works out the list, and sends. [[slnc 500]] An order carries its categories, its value, and whether it is a gift. [[slnc 500]] And the inboxes stand in for the warehouses and services that receive the copies.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel recipientList', 'Orders split across', 'fulfilment centres', 'The To and Cc lines of an email'],
         narration='You have probably met this pattern already. [[slnc 400]] Apache Camel has a recipient list step. [[slnc 500]] Large shops split each order across the fulfilment centres that stock its items. [[slnc 500]] And every email you send has a recipient list, chosen for that message.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['A different set of destinations', 'for each message.', '', 'One destination? A router.', 'Everyone? Publish-subscribe.', '', 'Plan for half-sent messages.'],
         narration='So, when should you use it? [[slnc 400]] When each message needs a different set of destinations. [[slnc 500]] If every message has exactly one destination, use a content-based router. [[slnc 300]] If everyone needs everything, use publish-subscribe. [[slnc 500]] And plan for what happens when a message reaches some recipients, but not all.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Retry failed', 'recipients once.'],
         narration="That's the Recipient List pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Work out who needs each message, and send it to exactly them. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Retry a failed recipient once, then send the order to a problem list. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Recipient List Pattern  ·  Java 21', 'poster': {'headline': [('RECIPIENT', 'text'), ('LIST', 'text')], 'before': {'code': 'send to all 4 warehouses', 'note': '20 deliveries, 8 needed', 'tag': 'BEFORE'}, 'after': {'code': 'recipientsFor(order)', 'note': '8 deliveries, all needed', 'tag': 'AFTER'}, 'taglines': [('Send it to exactly who needs it', 'gold')]}, 'highlight': {}}
