"""Scene definitions for the Valet Key with Amazon S3 teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Valet Key with Amazon S3',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Valet Key pattern, with Amazon S3 presigned addresses, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A valet key gives a client permission to do one thing, directly, for a short time. [[slnc 300]] Without the client ever holding the real credentials. [[slnc 500]] Amazon S3 is cloud object storage, and its presigned addresses are exactly such keys. [[slnc 600]] Think of a hotel valet key. [[slnc 300]] It starts the car, but does not open the boot. [[slnc 300]] And the valet has it only for the evening. [[slnc 700]] In this video, the domain is an online shop's review photos. [[slnc 500]] By the end, you will hear how photos stop passing through the shop's server. [[slnc 300]] What a signed address allows, and refuses. [[slnc 300]] And what happens when one leaks."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Customers add photos to reviews.', '', 'Every photo went through', "the shop's app server.", '', '10 photos: 40 MB carried.'],
         narration="Here is the scenario. [[slnc 400]] Customers add photos to their reviews. [[slnc 500]] Every photo went through the shop's app server, on its way to storage. [[slnc 500]] Ten photos meant forty megabytes carried, by a server that only needed to say where each photo goes."),
    dict(key='03-act-1', kind='console', title='Act One — Through the app server',
         body='ONE. Through the app server.\n  app server carried 40 MB',
         narration="First demo: photos carried through the shop's app server. [[slnc 400]] Ten customers each upload a two megabyte photo. [[slnc 600]] Every byte comes in to the app server. [[slnc 300]] And goes out again, to storage. [[slnc 500]] Forty megabytes through a server that only needed to say where the photo goes."),
    dict(key='04-act-2', kind='console', title='Act Two — A presigned URL',
         body='TWO. A presigned URL.\n  PUT via presigned URL: HTTP 200\n  app carried under 2 KB',
         narration="Second demo: a valet key, as an S3 presigned address. [[slnc 400]] The shop signs a web address. [[slnc 300]] It allows one upload, of one photo, of exactly this size, for five minutes. [[slnc 600]] The customer's browser uploads straight to S3. [[slnc 300]] Accepted. [[slnc 300]] Two million bytes stored. [[slnc 500]] The app server carried only the address."),
    dict(key='05-act-3', kind='console', title='Act Three — That, and nothing else',
         body='THREE. That, and nothing else.\n  read with it: 403\n  edited to R-3: 403\n  6 MB body: 403\n  unsigned: 200 on LocalStack only',
         narration='Third demo: the key allows that, and nothing else. [[slnc 400]] Use it to read the photo. [[slnc 300]] Refused. [[slnc 500]] Edit it to point at another review. [[slnc 300]] Refused. [[slnc 500]] Send a six megabyte file with it. [[slnc 300]] Refused, because the size was signed. [[slnc 600]] One honest note. [[slnc 300]] An upload with no key at all gets through here, because this local stand-in for S3 does not check permissions. [[slnc 300]] Real S3 refuses it.'),
    dict(key='06-act-4', kind='console', title='Act Four — The key runs out',
         body='FOUR. The key runs out.\n  1 s key after 2 s: 403',
         narration='Fourth demo: the key runs out. [[slnc 400]] A key valid for one second is used after two. [[slnc 500]] Refused.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  stranger with the key: 200',
         narration='Fifth demo: the bill. [[slnc 400]] A valid address is pasted into a public chat. [[slnc 300]] A stranger uses it. [[slnc 300]] Accepted. [[slnc 600]] Whoever holds the key can use it, until it expires. [[slnc 500]] Keep keys short-lived and narrow. [[slnc 300]] Keep them out of logs. [[slnc 300]] And sign with credentials you can revoke.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in S3',
         body=['The shop signs a URL:', 'one method, one object,', 'one size, a few minutes.', '', 'The client uses it directly.', 'S3 checks the signature.'],
         narration="Let's name the pattern, in S3's words. [[slnc 400]] The shop signs an address. [[slnc 300]] One method, one object, one size, for a few minutes. [[slnc 500]] The client uses it directly. [[slnc 300]] And S3 checks the signature against exactly what is asked."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Storage: signs URLs with the AWS SDK', 'Browser: uses only the URL', 'LocalStack: plays S3 locally'],
         narration="Here is who does what. [[slnc 400]] The storage class signs addresses with the AWS SDK's presigner. [[slnc 500]] The browser uses only the address. [[slnc 500]] And LocalStack plays Amazon S3, on your own machine."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['S3 presigned URLs', 'Google Cloud signed URLs', 'Azure SAS tokens', 'Expiring download links'],
         narration="You have probably met this already. [[slnc 400]] S3 presigned addresses. [[slnc 300]] Google Cloud's signed addresses. [[slnc 300]] Azure's shared access signatures. [[slnc 500]] And every download link in an email that stops working after a day."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Large files the app need not see.', '', 'Sign method, object, size.', 'Short lifetimes.', 'Out of logs.', 'Test on the real service.'],
         narration='So, when should you use it? [[slnc 400]] For large uploads and downloads the app never needs to see. [[slnc 500]] Sign the method, object and size. [[slnc 300]] Keep lifetimes short. [[slnc 300]] Keep addresses out of logs. [[slnc 300]] And test permissions on the real service.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Sign a', '1-minute download link.'],
         narration="That's the Valet Key, with Amazon S3. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Sign exactly one permission, for a short time, and let the storage check it. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts LocalStack for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Sign a download address for the photo, valid for one minute. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Valet Key with Amazon S3 Pattern  ·  Java 21', 'poster': {'headline': [('VALET KEY', 'text'), ('WITH AMAZON S3', 'text')], 'before': {'code': 'photos through the app', 'note': '40 MB carried', 'tag': 'BEFORE'}, 'after': {'code': 'presignPutObject(...)', 'note': 'browser to S3, app carries 2 KB', 'tag': 'AFTER'}, 'taglines': [('Presigned URLs, for real', 'gold')]}, 'highlight': {}}
