"""Scene definitions for the Process Manager with Apache Camel teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Process Manager with Apache Camel',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Process Manager pattern, built with Apache Camel's saga step, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A process manager runs a journey of several steps, from one place. [[slnc 300]] It decides each next step, and makes sure every journey ends in a known state. [[slnc 500]] Apache Camel is an open-source library for moving messages. [[slnc 300]] Its saga step runs such journeys, and undoes earlier steps when a later one fails. [[slnc 600]] Think of a travel agent booking a flight, a hotel, and a car. [[slnc 300]] The agent notes how to cancel each booking. [[slnc 300]] If the car fails, the agent cancels the hotel and the flight, and rings the customer. [[slnc 700]] In this video, the domain is an online shop's orders, which reserve stock, take payment, and ship. [[slnc 500]] By the end, you will hear how a declined card stranded stock. [[slnc 300]] How a saga owns each journey. [[slnc 300]] How Camel runs the undo steps. [[slnc 300]] And what a saga costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Reserve stock, take payment, ship.', '', 'Each step handed on to the next.', '', 'A declined card left', 'a kettle reserved for ever.'],
         narration='Here is the scenario. [[slnc 400]] Each order reserves stock, takes payment, and ships. [[slnc 500]] Each step simply handed on to the next. [[slnc 500]] When a card was declined, the kettle reserved for it was never given back.'),
    dict(key='03-act-1', kind='console', title='Act One — Steps hand on to each other',
         body='ONE. Steps hand on to each other.\n  ORD-3 declined: stopped at payments\n  kettles: 1 of 3',
         narration="First demo: each step hands on to the next. [[slnc 400]] Reserve stock, then take payment, then ship. [[slnc 600]] Order one is shipped. [[slnc 500]] Order three's card is declined. [[slnc 300]] The chain stops at payments. [[slnc 300]] But its kettle is never given back. [[slnc 600]] One kettle left, of three. [[slnc 300]] Though only one was shipped. [[slnc 300]] And nothing knows where order three is."),
    dict(key='04-act-2', kind='console', title='Act Two — A saga',
         body='TWO. A saga.\n  ORD-1: RESERVED, PAID, SHIPPED\n  -> DONE',
         narration="Second demo: a saga runs each order's journey. [[slnc 400]] One route owns the whole journey. [[slnc 600]] Order one is reserved at the main warehouse. [[slnc 300]] Paid. [[slnc 300]] Shipped. [[slnc 500]] When the journey ends well, Camel calls the completion route. [[slnc 300]] Order one is marked done."),
    dict(key='05-act-3', kind='console', title='Act Three — A branch',
         body='THREE. A branch.\n  main OUT_OF_STOCK, partner RESERVED\n  -> DONE',
         narration='Third demo: the journey branches. [[slnc 400]] Order two is for a teapot. [[slnc 300]] The main warehouse has none. [[slnc 600]] So the reserve step asks the partner warehouse. [[slnc 300]] It has two. [[slnc 500]] Payment and shipping go ahead. [[slnc 300]] Done.'),
    dict(key='06-act-4', kind='console', title='Act Four — Camel runs the undo steps',
         body='FOUR. Camel runs the undo steps.\n  DECLINED -> main RELEASED\n  CANCELLED; kettles 2 of 3\n  email: your card was declined',
         narration='Fourth demo: the card is declined, and Camel runs the undo steps. [[slnc 400]] When the reserve step joined the saga, it named how to undo itself. [[slnc 600]] The card is declined. [[slnc 300]] So Camel calls the undo step. [[slnc 300]] The kettle goes back to the warehouse. [[slnc 500]] Then Camel calls the cancellation route. [[slnc 300]] The order is marked cancelled. [[slnc 300]] The customer gets an email. [[slnc 500]] Two kettles of three remain, as they should.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  ORD-1 DONE, ORD-2 DONE, ORD-3 CANCELLED\n  an undo for every step\n  in memory: lost on restart',
         narration='Fifth demo: the bill. [[slnc 400]] The shop can now say where every order is. [[slnc 600]] But every step that changes something needs an undo step, written by someone. [[slnc 300]] And undoing is not the same as never having happened. [[slnc 600]] And this saga service keeps its notes in memory. [[slnc 300]] A restart forgets every journey. [[slnc 300]] Production needs a coordinator that keeps them safe.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Camel',
         body=['saga(): one route owns the journey.', '', 'Each step names its undo.', '', 'Camel calls the undo steps,', 'then completion or cancellation.'],
         narration="Let's name the pattern, in Camel's words. [[slnc 400]] The saga step makes one route own the whole journey. [[slnc 500]] Each step that changes something names its undo step. [[slnc 500]] When a step fails, Camel calls the undo steps, then the cancellation route. [[slnc 300]] When all goes well, the completion route."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShopRoutes: the saga and its routes', 'Services: reserve, pay, ship, release', 'InMemorySagaService: tracks sagas', 'Order: the message'],
         narration='Here is who does what. [[slnc 400]] Shop routes declares the saga, and its completion and undo routes. [[slnc 500]] The services do the work. [[slnc 300]] Reserve, pay, ship, and release. [[slnc 500]] The saga service keeps track of each journey while the program runs. [[slnc 300]] And the order is the message.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel Saga with an LRA coordinator', 'Temporal and Axon', 'Travel bookings'],
         narration="You have probably met this already. [[slnc 400]] Camel's saga, often with a separate coordinator service. [[slnc 500]] Workflow engines, such as Temporal and Axon. [[slnc 500]] And every travel booking, where a failed step cancels the earlier ones."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['A journey across services,', 'each changing something.', '', 'An undo for every step.', 'A durable coordinator', 'in production.'],
         narration='So, when should you use it? [[slnc 400]] When a journey crosses several services, and each one changes something. [[slnc 500]] Write an undo for every step. [[slnc 300]] Remember that undo is not rewind. [[slnc 300]] And use a durable coordinator in production.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add an undo', 'step for shipping.'],
         narration="That's the Process Manager, with Apache Camel's saga. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] One place owns the journey, and every step knows how to undo itself. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add an undo step for shipping, that books a return label. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Process Manager with Apache Camel Pattern  ·  Java 21', 'poster': {'headline': [('PROCESS MANAGER', 'text'), ('WITH CAMEL', 'text')], 'before': {'code': 'reserve -> pay -> ship', 'note': 'declined: kettle stranded', 'tag': 'BEFORE'}, 'after': {'code': 'saga().compensation(...)', 'note': 'declined: kettle released', 'tag': 'AFTER'}, 'taglines': [('A saga runs each journey', 'gold')]}, 'highlight': {}}
