"""Scene definitions for the Lenses for Immutable Updates teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Lenses for Immutable Updates',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Lenses, for updating immutable data, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Immutable objects can never be changed, only replaced. [[slnc 300]] A lens is a pair of functions for one part of such an object. [[slnc 300]] One reads the part. [[slnc 300]] The other returns a new object, with the part replaced. [[slnc 300]] And lenses can be joined, to reach deep inside. [[slnc 600]] Think of a set of nesting dolls, glued shut. [[slnc 300]] To change the smallest doll, you must make new outer dolls around a new inner one. [[slnc 300]] A lens is a tool that does that for you. [[slnc 700]] In this video, the domain is an online shop's orders. [[slnc 300]] An order holds a customer, who holds a delivery address. [[slnc 500]] By the end, you will hear how rebuilding by hand went wrong. [[slnc 300]] How one lens works. [[slnc 300]] How lenses join. [[slnc 300]] And what they cost."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Orders are immutable records:', 'order, customer, address.', '', 'Changing a postcode rebuilt', 'all three by hand.'],
         narration='Here is the scenario. [[slnc 400]] The shop keeps orders as immutable records, three levels deep. [[slnc 300]] An order, holding a customer, holding an address. [[slnc 500]] When a customer corrected a postcode, the code rebuilt all three, by hand. [[slnc 500]] And in one place, the street and city were swapped.'),
    dict(key='03-act-1', kind='console', title='Act One — Rebuilding by hand',
         body='ONE. Rebuilding by hand.\n  3 constructors for one field\n  street=Leeds, city=1 High Street',
         narration='First demo: changing one field of an immutable order, by hand. [[slnc 400]] Immutable means the order can never be changed. [[slnc 300]] Only replaced. [[slnc 600]] To change the postcode, the code builds a new address. [[slnc 300]] Then a new customer around it. [[slnc 300]] Then a new order around that. [[slnc 600]] Street and city are both text. [[slnc 300]] And here they were passed the wrong way round. [[slnc 500]] Nothing complained. [[slnc 300]] The parcel is addressed to street Leeds, city one High Street.'),
    dict(key='04-act-2', kind='console', title='Act Two — One lens',
         body='TWO. One lens.\n  get: LS1 4AP\n  set: new address, LS2 7HY\n  original unchanged',
         narration='Second demo: a lens. [[slnc 400]] A lens is a pair of functions, for one part of an object. [[slnc 300]] Get reads the part. [[slnc 300]] Set returns a new object, with that part replaced. [[slnc 600]] The postcode lens reads, L S one, four A P. [[slnc 500]] Set it to L S two, seven H Y. [[slnc 300]] A new address comes back. [[slnc 500]] And the original address is unchanged.'),
    dict(key='05-act-3', kind='console', title='Act Three — Lenses join',
         body='THREE. Lenses join.\n  ORDER_POSTCODE.set: LS2 7HY\n  old order: LS1 4AP',
         narration='Third demo: lenses join together. [[slnc 400]] One lens goes from the order to the customer. [[slnc 300]] The next, from the customer to the address. [[slnc 300]] The next, from the address to the postcode. [[slnc 600]] Joined, they make one lens, from the order straight to the postcode. [[slnc 500]] Setting the postcode of a whole order is now one line. [[slnc 300]] All three levels are rebuilt correctly, every time. [[slnc 500]] And the old order still has the old postcode.'),
    dict(key='06-act-4', kind='console', title='Act Four — Change with a function',
         body='FOUR. Change with a function.\n  modify(upper): LS2 7HY\n  city + postcode: York, YO1 7HH',
         narration='Fourth demo: change a part with a function. [[slnc 400]] The customer typed the postcode in lower case. [[slnc 600]] Modify applies a function to just that part. [[slnc 300]] Upper case. [[slnc 300]] Now it is L S two, seven H Y. [[slnc 600]] And lenses can be used together. [[slnc 300]] A city lens, and a postcode lens. [[slnc 300]] The delivery moves to York. [[slnc 300]] The street is untouched.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  4 lenses written by hand\n  lines shared, not copied: true',
         narration='Fifth demo: the bill. [[slnc 400]] Lenses are code to write. [[slnc 300]] Four of them, by hand, for three levels. [[slnc 300]] Java has no built-in way to make them. [[slnc 600]] Each change makes three new objects. [[slnc 300]] But the parts that did not change are shared, not copied. [[slnc 300]] The new order holds the very same list of lines. [[slnc 600]] And for one or two flat records, a small with method is simpler.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['A lens: get and set', 'for one part.', '', 'Set returns a new whole.', '', 'Lenses join to reach deep.'],
         narration="Let's name the pattern. [[slnc 400]] A lens has a get and a set, for one part of an object. [[slnc 500]] Set returns a new whole, and leaves the old one alone. [[slnc 500]] And lenses join, to reach deep inside."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Lens: get, set, modify, andThen', 'ADDRESS_POSTCODE: one field', 'ORDER_POSTCODE: three joined', 'Order, Customer, Address: the data'],
         narration='Here is who does what. [[slnc 400]] A lens has get, set, modify, and and-then. [[slnc 500]] The address postcode lens focuses on one field. [[slnc 300]] The order postcode lens is three lenses joined. [[slnc 500]] And the order, customer, and address records are the data.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Monocle in Scala', 'Arrow Optics in Kotlin', 'Immer in JavaScript', 'Lombok @With'],
         narration='You have probably met this pattern already. [[slnc 400]] Scala has a lens library called Monocle. [[slnc 300]] Kotlin has Arrow Optics. [[slnc 500]] JavaScript developers use Immer for the same job. [[slnc 500]] And Lombok can generate with methods, the simple, one-level version.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Deeply nested immutable data.', '', 'One lens per field.', 'Join for deep paths.', 'Test the three laws.', 'Flat? Use a with method.'],
         narration='So, when should you use it? [[slnc 400]] For immutable data, nested several levels deep. [[slnc 500]] Write one small lens per field. [[slnc 300]] Join them for deep paths. [[slnc 300]] Test the three lens laws. [[slnc 300]] And for flat data, a simple with method is enough.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a lens', "for the customer's name."],
         narration="That's Lenses for immutable updates. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] A lens gets and sets one part, and lenses join to reach deep inside. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a lens for the customer's name, and join it to the order. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Lenses for Immutable Updates Pattern  ·  Java 21', 'poster': {'headline': [('LENSES', 'text')], 'before': {'code': 'new Order(..., new Customer(...))', 'note': 'street and city swapped', 'tag': 'BEFORE'}, 'after': {'code': 'ORDER_POSTCODE.set(order, p)', 'note': 'one line, old order intact', 'tag': 'AFTER'}, 'taglines': [('Change deep inside, safely', 'gold')]}, 'highlight': {}}
