"""Scene definitions for the Resequencer teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Resequencer',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Resequencer pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] When numbered messages can arrive out of order, a resequencer holds the early ones. [[slnc 300]] It releases each sequence strictly in order. [[slnc 300]] And it has a limit, so a lost message cannot block everything for ever. [[slnc 600]] Think of a long letter sent in five numbered envelopes, delivered in a muddle. [[slnc 300]] You read envelope one, put three aside, and wait for two. [[slnc 300]] And if three is lost for good, at some point you read on without it. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Its order page shows status updates: placed, paid, packed, shipped, and delivered. [[slnc 500]] By the end, you will hear what goes wrong when updates are applied as they arrive. [[slnc 300]] How a resequencer fixes it. [[slnc 300]] How it handles many orders. [[slnc 300]] And what a lost message costs.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['PLACED, PAID, PACKED,', 'SHIPPED, DELIVERED.', '', 'Updates pass through parallel', 'workers, and arrive in a muddle.'],
         narration='Here is the scenario. [[slnc 400]] Each order goes through five statuses. [[slnc 300]] Placed, paid, packed, shipped, delivered. [[slnc 600]] The updates pass through several workers, running in parallel. [[slnc 300]] So they reach the order page in a muddle. [[slnc 500]] Each update carries a number, one to five.'),
    dict(key='03-act-1', kind='console', title='Act One — Applied as they arrive',
         body='ONE. Applied as they arrive.\n  arrival: #1, #3, #2, #5, #4\n  saw: PLACED, PACKED, PAID, DELIVERED, SHIPPED\n  final: SHIPPED, but it was DELIVERED',
         narration="First demo: status updates applied as they arrive. [[slnc 400]] Five updates for Priya's order. [[slnc 300]] Placed, paid, packed, shipped, delivered. [[slnc 600]] They arrive in a muddle: one, three, two, five, four. [[slnc 500]] The page shows each as it comes. [[slnc 300]] Packed before paid. [[slnc 300]] Delivered, then shipped. [[slnc 500]] The page ends on shipped. [[slnc 300]] But the parcel was delivered."),
    dict(key='04-act-2', kind='console', title='Act Two — A resequencer',
         body='TWO. A resequencer.\n  saw: PLACED, PAID, PACKED, SHIPPED, DELIVERED\n  final: DELIVERED',
         narration='Second demo: a resequencer puts them back in order. [[slnc 400]] It sits in front of the page. [[slnc 300]] It only passes on the next number it expects. [[slnc 600]] The customer now sees: placed, paid, packed, shipped, delivered. [[slnc 500]] The page ends on delivered.'),
    dict(key='05-act-3', kind='console', title='Act Three — Hold and release',
         body='THREE. Hold and release.\n  received #3; holding [3]\n  released #2, then #3\n  received #5; holding [5]; released #4, #5',
         narration='Third demo: early messages wait, and late ones release them. [[slnc 400]] Number one is released at once. [[slnc 500]] Number three arrives early. [[slnc 300]] It is held. [[slnc 500]] Number two arrives. [[slnc 300]] It is released, and so is the three that was waiting. [[slnc 500]] Number five is held, until four arrives. [[slnc 300]] Then both go through.'),
    dict(key='06-act-4', kind='console', title='Act Four — One sequence per order',
         body='FOUR. One sequence per order.\n  ORD-3 PLACED, ORD-2 PLACED, ORD-2 PAID,\n  ORD-3 PAID, ORD-3 PACKED',
         narration="Fourth demo: each order has its own sequence. [[slnc 400]] Updates for two orders arrive, all mixed together. [[slnc 600]] Each order's updates are released in that order's own sequence. [[slnc 300]] Neither order waits for the other."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  #3 lost: held #4, page says PAID\n  limit reached: skip #3, page DELIVERED',
         narration="Fifth demo: the bill. [[slnc 400]] Another order's update number three is lost. [[slnc 500]] Number four arrives, and is held. [[slnc 300]] The page still says paid. [[slnc 500]] Number five arrives. [[slnc 300]] Now two are waiting, the limit. [[slnc 300]] The resequencer gives up on three, and releases four and five. [[slnc 600]] The page says delivered. [[slnc 300]] Packed was never shown. [[slnc 300]] And without a limit, the page would have waited for ever."),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Number the messages.', '', 'Release only the next number', 'expected; hold early ones.', '', 'One sequence per order.', 'A limit for gaps.'],
         narration="Let's name the pattern. [[slnc 400]] Number each message, per order. [[slnc 500]] Release only the number that is expected next. [[slnc 300]] Hold anything that arrives early. [[slnc 500]] Keep a separate sequence for each order. [[slnc 300]] And set a limit, for gaps that will never fill."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['StatusUpdate: order, number, status', 'Resequencer: expected numbers, held updates', 'OrderPage: shows the status'],
         narration='Here is who does what. [[slnc 400]] A status update carries the order, its number, and the status. [[slnc 500]] The resequencer keeps, for each order, the next number it expects, and the updates it is holding. [[slnc 500]] And the order page shows whatever it is given.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel resequence', 'TCP packet sequence numbers', 'Kafka: order per partition key'],
         narration="You have probably met this pattern already. [[slnc 400]] Apache Camel has a resequence step. [[slnc 500]] The internet's T C P protocol puts packets back in order, using sequence numbers. [[slnc 500]] And Kafka keeps messages in order per key, which is one way to avoid needing a resequencer."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Order matters, and delivery', 'does not keep it.', '', 'Number per key. Bound the buffer.', 'Plan for gaps.', '', 'Can the transport keep order?', 'Use that.'],
         narration='So, when should you use it? [[slnc 400]] When order matters, and delivery does not keep it. [[slnc 500]] Number messages per key. [[slnc 300]] Put a limit on the buffer. [[slnc 300]] And decide what to do about gaps. [[slnc 500]] And if you can choose a transport that keeps order per key, prefer that.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Give up on a gap', 'after two seconds.'],
         narration="That's the Resequencer pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Hold what comes early, release in order, and never wait for ever. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Give up on a gap after two seconds, instead of after two held messages. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Resequencer Pattern  ·  Java 21', 'poster': {'headline': [('RESEQUENCER', 'text')], 'before': {'code': '#1, #3, #2, #5, #4', 'note': 'ends on SHIPPED', 'tag': 'BEFORE'}, 'after': {'code': '#1, #2, #3, #4, #5', 'note': 'ends on DELIVERED', 'tag': 'AFTER'}, 'taglines': [('Put the messages back in order', 'gold')]}, 'highlight': {}}
