"""Scene definitions for the Page Controller teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Page Controller',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Page Controller pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A page controller is a small class for one page of a web site. [[slnc 300]] It reads that page's input, decides what to do, and sends the reply. [[slnc 300]] Every page gets its own. [[slnc 600]] Think of a department store with a separate desk for each service. [[slnc 300]] A returns desk, a gift-wrapping desk, a café till. [[slnc 300]] Each knows only its own job. [[slnc 300]] But a store-wide rule has to be taught at every desk. [[slnc 700]] In this video, the domain is an online shop's web site. [[slnc 300]] It has a product page, a basket, and a checkout, served by a real web server running on the same computer. [[slnc 500]] By the end, you will hear how one handler for every page lets changes leak. [[slnc 300]] How page controllers fix it. [[slnc 300]] How to add a page. [[slnc 300]] And the check that gets forgotten."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['/product: show a product.', '/basket: add to the basket.', '/checkout: pay.', '', 'All served by one handler,', 'in one long method.'],
         narration="Here is the scenario. [[slnc 400]] The shop's web site has three addresses. [[slnc 300]] Product shows a product. [[slnc 300]] Basket adds something to the basket. [[slnc 300]] Checkout takes payment. [[slnc 600]] All three were served by one handler. [[slnc 300]] One long method, that looked at the address and chose what to do."),
    dict(key='03-act-1', kind='console', title='Act One — One handler for every page',
         body='ONE. One handler for every page.\n  /basket?add=MUG-1&qty=2  -> 200\n  /product?sku=KETTLE-1   -> 500\n    NumberFormatException',
         narration='First demo: one handler for every page. [[slnc 400]] The product page, the basket, and every other address go through one long method. [[slnc 500]] Someone added a line at the top, to read the quantity, for the basket. [[slnc 500]] The basket works: two mugs. [[slnc 500]] But the product page has no quantity. [[slnc 300]] It now fails with a server error. [[slnc 300]] A change for one page broke another.'),
    dict(key='04-act-2', kind='console', title='Act Two — A controller per page',
         body='TWO. A controller per page.\n  /product?sku=KETTLE-1   -> 200\n    steel kettle, £30.00\n  /basket?add=MUG-1&qty=2 -> 200',
         narration='Second demo: a page controller for each page. [[slnc 400]] The product page has its own small class. [[slnc 300]] So does the basket. [[slnc 300]] So does checkout. [[slnc 500]] The web server sends each address to its controller. [[slnc 500]] The product page shows the steel kettle, thirty pounds. [[slnc 300]] The basket takes two mugs. [[slnc 300]] Both work.'),
    dict(key='05-act-3', kind='console', title='Act Three — Errors stay on their page',
         body='THREE. Errors stay on their page.\n  /product?sku=SOFA-9 -> 404\n  /basket ... qty=two -> 400\n  /product?sku=MUG-1  -> 200',
         narration='Third demo: each page handles its own input, and its own errors. [[slnc 400]] A customer asks for a product that does not exist. [[slnc 300]] The product page answers four oh four: no such product. [[slnc 500]] Someone types the word two as a quantity. [[slnc 300]] The basket answers four hundred: quantity must be a number. [[slnc 500]] And the product page for the mug still works.'),
    dict(key='06-act-4', kind='console', title='Act Four — A new page',
         body='FOUR. A new page.\n  /reviews?sku=KETTLE-1 -> 200\n    4.5 stars from 12 customers',
         narration='Fourth demo: a new page is a new class, and one line. [[slnc 400]] The shop adds a reviews page. [[slnc 300]] One new controller, and one line telling the server about it. [[slnc 500]] The reviews page answers: four point five stars, from twelve customers. [[slnc 300]] No other controller was touched.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  /basket, not logged in   -> 401\n  /checkout, not logged in -> 200\n  checkout forgot the login check',
         narration="Fifth demo: the bill. [[slnc 400]] Checks that every page needs are written in every controller. [[slnc 500]] A visitor who is not logged in opens the basket. [[slnc 300]] Four oh one: please log in. [[slnc 500]] The same visitor opens checkout. [[slnc 300]] Two hundred: pay with the card on file. [[slnc 300]] Checkout's author forgot the login check. [[slnc 600]] The Front Controller pattern exists to fix exactly this."),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['One small controller per page.', '', 'It reads its own input,', 'makes its own decisions,', 'sends its own reply.', '', 'The server maps address -> controller.'],
         narration="Let's name the pattern. [[slnc 400]] Give each page its own small controller. [[slnc 500]] The controller reads that page's input. [[slnc 300]] It makes that page's decisions. [[slnc 300]] And it sends that page's reply. [[slnc 500]] The web server keeps a simple map: this address goes to that controller."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['HttpServer: address -> controller', 'ProductController: /product', 'BasketController: /basket', 'CheckoutController: /checkout', 'OneHandler: the old way'],
         narration="Here is who does what. [[slnc 400]] The JDK's built-in web server maps each address to a controller. [[slnc 500]] Product controller serves the product page. [[slnc 300]] Basket controller serves the basket, and checks the login. [[slnc 300]] Checkout controller serves checkout. [[slnc 500]] And one handler is the old way, kept for comparison."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['A JSP or PHP file per page', 'One servlet per URL', 'Spring MVC @Controller classes', 'HttpServer.createContext'],
         narration='You have probably met this pattern already. [[slnc 400]] Classic web sites with one JSP or PHP file per page are page controllers. [[slnc 500]] So are servlets mapped one per address. [[slnc 500]] And Spring M V C controller classes, with a method for each page, are the modern form.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Simple sites with mostly', 'independent pages.', '', 'Many shared checks?', 'Use a Front Controller', 'or filters.'],
         narration='So, when should you use it? [[slnc 400]] For simple sites, where the pages are mostly independent. [[slnc 500]] As soon as many pages share checks, logging, or layout, move those into a front controller, or into filters. [[slnc 300]] Then they run for every page, and cannot be forgotten.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add the missing', 'login check to checkout.'],
         narration="That's the Page Controller pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] One small controller per page, and each page looks after itself. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add the missing login check to checkout, and a test that proves it. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Page Controller Pattern  ·  Java 21', 'poster': {'headline': [('PAGE', 'text'), ('CONTROLLER', 'text')], 'before': {'code': 'if (path.equals(...))', 'note': 'one change broke a page', 'tag': 'BEFORE'}, 'after': {'code': '/basket -> BasketController', 'note': 'each page on its own', 'tag': 'AFTER'}, 'taglines': [('One controller per page', 'gold')]}, 'highlight': {}}
