"""Scene definitions for the Sharding teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Sharding',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Sharding pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Sharding splits one large set of data across several databases, called shards. [[slnc 300]] Each row goes to a shard chosen from a key, such as the customer number. [[slnc 300]] So each database holds, and serves, only its share. [[slnc 600]] Think of a doctor's surgery that has outgrown one filing cabinet. [[slnc 300]] The records are split into three cabinets: A to H, I to P, and Q to Z. [[slnc 300]] One patient's file is in one cabinet. [[slnc 300]] But a fourth cabinet means refiling many folders. [[slnc 700]] In this video, the domain is an online shop, on Black Friday. [[slnc 300]] Orders arrive faster than one database can take them. [[slnc 500]] By the end, you will hear how shards share the load. [[slnc 300]] Which questions are easy, and which are not. [[slnc 300]] And what adding a shard costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['One database for every order.', 'It takes 1,000 orders a minute.', '', 'Black Friday: 2,500 a minute.'],
         narration='Here is the scenario. [[slnc 400]] Every order is saved in one database. [[slnc 300]] It can take a thousand new orders a minute. [[slnc 600]] On Black Friday, two and a half thousand arrive every minute.'),
    dict(key='03-act-1', kind='console', title='Act One — One database',
         body='ONE. One database.\n  2500 orders a minute; limit 1000\n  waiting every minute: 1500',
         narration='First demo: one database for every order. [[slnc 400]] It can take one thousand new orders a minute. [[slnc 500]] On Black Friday, two and a half thousand arrive, every minute. [[slnc 500]] Fifteen hundred are left waiting, every minute. [[slnc 300]] And the queue keeps growing.'),
    dict(key='04-act-2', kind='console', title='Act Two — Three shards',
         body='TWO. Three shards.\n  shard-0: 833; shard-1: 834; shard-2: 833\n  all within their limit\n  customer 17 -> shard-2',
         narration="Second demo: three shards, split by customer number. [[slnc 400]] Each order goes to one of three databases. [[slnc 300]] Which one is worked out from the customer's number alone. [[slnc 600]] The two and a half thousand orders split into three shares of about eight hundred and thirty. [[slnc 300]] Each is within its database's limit. [[slnc 500]] Customer seventeen always lives on shard two."),
    dict(key='05-act-3', kind='console', title='Act Three — One customer, one shard',
         body="THREE. One customer, one shard.\n  customer 17's orders: [ORD-17]\n  shards asked: 1",
         narration="Third demo: a question about one customer asks one shard. [[slnc 400]] Where are customer seventeen's orders? [[slnc 300]] The router knows: shard two. [[slnc 500]] Only one shard is asked."),
    dict(key='06-act-4', kind='console', title='Act Four — Everyone, every shard',
         body='FOUR. Everyone, every shard.\n  over £500: 25 found\n  shards asked: 3, answers merged',
         narration='Fourth demo: a question about everyone asks every shard. [[slnc 400]] Which orders this minute were over five hundred pounds? [[slnc 500]] There is no single place to look. [[slnc 300]] All three shards are asked, and their answers are merged. [[slnc 300]] Twenty-five orders.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  4 shards: 1874 of 2500 customers move\n  a busy customer: one hot shard',
         narration='Fifth demo: the bill. [[slnc 400]] The shop grows, and adds a fourth shard. [[slnc 500]] With the same simple rule, now the customer number modulo four, one thousand eight hundred and seventy-four of the two and a half thousand customers belong on a different shard. [[slnc 300]] All their orders must be copied across. [[slnc 600]] And one very busy customer still lands entirely on one shard.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Several databases: shards.', '', "A shard key picks each row's shard.", '', 'One key: one shard.', 'Everyone: every shard, merged.'],
         narration="Let's name the pattern. [[slnc 400]] Use several databases, called shards. [[slnc 500]] A shard key, here the customer number, decides which shard each order goes to. [[slnc 500]] A question about one customer asks one shard. [[slnc 300]] A question about everyone asks every shard, and merges the answers."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShardedOrders: the router', 'OrderDatabase: one shard', 'Order: the data, with its key'],
         narration='Here is who does what. [[slnc 400]] Sharded orders is the router. [[slnc 300]] It works out the shard from the customer number, and asks the right database. [[slnc 500]] An order database is one shard, with its own limit. [[slnc 500]] And an order carries the customer number, its shard key.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['MongoDB, Elasticsearch shards', 'Cassandra and DynamoDB partitions', 'Vitess, Citus', 'Consistent hashing'],
         narration='You have probably met this pattern already. [[slnc 400]] MongoDB and Elasticsearch split data into shards. [[slnc 300]] Cassandra and DynamoDB split it into partitions, by a partition key. [[slnc 500]] Vitess and Citus shard MySQL and Postgres. [[slnc 300]] And consistent hashing is the trick that moves less data when shards are added.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Only when one database', 'truly cannot cope.', '', 'A key that spreads load and', 'matches common questions.', '', 'Plan for adding shards.'],
         narration='So, when should you use it? [[slnc 400]] Only when one database truly cannot cope, after a bigger server, caching, and read copies. [[slnc 500]] Choose a key that spreads the load evenly, and matches your most common questions. [[slnc 500]] And plan, from day one, for adding shards.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a fourth shard', 'with a lookup table.'],
         narration="That's the Sharding pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Split the data by a key, and each database carries only its share. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a fourth shard using a lookup table, so only new customers go there. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Sharding Pattern  ·  Java 21', 'poster': {'headline': [('SHARDING', 'text')], 'before': {'code': 'one database', 'note': '1,500 orders waiting a minute', 'tag': 'BEFORE'}, 'after': {'code': 'customer % 3', 'note': 'three shares, each within limits', 'tag': 'AFTER'}, 'taglines': [('Split the data, split the load', 'gold')]}, 'highlight': {}}
