"""Scene definitions for the Priority Queue with RabbitMQ teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Priority Queue with RabbitMQ',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Priority Queue pattern, with a real RabbitMQ broker, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] In a priority queue, urgent messages overtake routine ones. [[slnc 300]] However long the routine ones have been waiting. [[slnc 500]] RabbitMQ is an open-source message broker, and it can make a queue a priority queue. [[slnc 600]] Think of the fast-track lane at airport security. [[slnc 300]] Passengers with a tight connection skip the queue. [[slnc 300]] But nobody can overtake someone already in the scanner. [[slnc 700]] In this video, the domain is an online shop's warehouse, where same-day orders must catch the courier's van. [[slnc 500]] By the end, you will hear how RabbitMQ puts same-day orders first. [[slnc 300]] Why a setting called prefetch can undo it. [[slnc 300]] And why routine orders need a share kept for them."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Pickers take 10 orders a minute.', '', 'Same-day orders must reach', 'the van by 9:05.', '', '100 standard came first.'],
         narration='Here is the scenario. [[slnc 400]] The warehouse pickers take ten orders a minute, from a queue. [[slnc 500]] Same-day orders must be picked before the van leaves, at five past nine. [[slnc 500]] On a busy morning, a hundred standard orders came first.'),
    dict(key='03-act-1', kind='console', title='Act One — First in, first out',
         body='ONE. First in, first out.\n  last same-day picked at 9:11\n  van left at 9:05',
         narration="First demo: an ordinary queue, first in, first out. [[slnc 400]] A hundred standard orders arrive, then five same-day orders. [[slnc 600]] The pickers take ten a minute, from nine o'clock. [[slnc 500]] The last same-day order is picked at eleven minutes past. [[slnc 300]] The van left at five past."),
    dict(key='04-act-2', kind='console', title='Act Two — A priority queue',
         body='TWO. A priority queue.\n  all 5 same-day by 9:01',
         narration='Second demo: a RabbitMQ priority queue. [[slnc 400]] The queue is declared with priorities from zero to ten. [[slnc 300]] Same-day orders are sent with priority nine. [[slnc 600]] RabbitMQ hands out the highest priority first. [[slnc 500]] All five same-day orders are picked by one minute past nine.'),
    dict(key='05-act-3', kind='console', title='Act Three — A flood',
         body='THREE. A flood.\n  1000 ahead: same-day by 9:01',
         narration='Third demo: a flood of standard orders. [[slnc 400]] A thousand standard orders are waiting first. [[slnc 600]] The same-day orders overtake them all. [[slnc 300]] Still picked by one minute past nine.'),
    dict(key='06-act-4', kind='console', title='Act Four — Only what is still waiting',
         body='FOUR. Only what is still waiting.\n  no limit: same-day at 101 to 105\n  prefetch 1: next is SAME-1',
         narration="Fourth demo: priority only reorders what is still waiting. [[slnc 400]] A picker's handheld subscribes with no limit. [[slnc 300]] RabbitMQ pushes all hundred standard orders to it, at once. [[slnc 600]] Then the same-day orders arrive. [[slnc 300]] They join the back of the handheld. [[slnc 300]] Positions one hundred and one, to one hundred and five. [[slnc 600]] With a prefetch of one, only one order sits in the handheld. [[slnc 300]] And the next one handed out is same-day."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill: starvation',
         body='FIVE. The bill: starvation.\n  strict priority: 0 of 20 standard\n  own queue, 2 a minute: 20 of 20',
         narration='Fifth demo: the bill. [[slnc 400]] Twelve same-day orders arrive every minute. [[slnc 300]] The pickers can do ten. [[slnc 600]] With strict priority, standard orders are never picked. [[slnc 300]] Zero of twenty, in ten minutes. [[slnc 600]] RabbitMQ keeps no share for routine work. [[slnc 300]] So the shop builds one. [[slnc 300]] Standard orders on their own queue, with two picks a minute kept for them. [[slnc 300]] All twenty are picked.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in RabbitMQ',
         body=['Declare the queue with', 'x-max-priority.', '', 'Send each message with', 'a priority.', '', 'Keep prefetch small.'],
         narration="Let's name the pattern, in RabbitMQ's words. [[slnc 400]] Declare the queue with a maximum priority. [[slnc 500]] Send each message with its priority. [[slnc 500]] And keep the prefetch small, so messages stay on the queue, where priority can reorder them."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Warehouse: queues and pickers', 'Broker: RabbitMQ in a container', 'Poll: waits for real conditions'],
         narration='Here is who does what. [[slnc 400]] The warehouse class declares the queues, places orders, and picks ten a minute. [[slnc 500]] The broker class runs RabbitMQ in a container. [[slnc 300]] And poll waits for real conditions.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['RabbitMQ priority queues', 'High and low SQS queues', 'Triage, fast-track lanes'],
         narration="You have probably met this already. [[slnc 400]] RabbitMQ's priority queues. [[slnc 500]] Separate high and low priority queues, on cloud services. [[slnc 500]] And hospital triage, and airport fast-track lanes."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Some work has a real,', 'earlier deadline.', '', 'Small prefetch.', 'Few priority levels.', 'Build a reserved share.'],
         narration='So, when should you use it? [[slnc 400]] When some work has a real, earlier deadline. [[slnc 500]] Keep prefetch small. [[slnc 300]] Use few priority levels. [[slnc 300]] And build a reserved share for routine work yourself.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Try', 'prefetch 10.'],
         narration="That's the Priority Queue, with RabbitMQ. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Urgent first, but only for what is still waiting, and never at the cost of everything else. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts the broker for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Try a prefetch of ten, and find where the same-day orders land. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Priority Queue with RabbitMQ Pattern  ·  Java 21', 'poster': {'headline': [('PRIORITY QUEUE', 'text'), ('WITH RABBITMQ', 'text')], 'before': {'code': 'first in, first out', 'note': 'same-day at 9:11: van gone', 'tag': 'BEFORE'}, 'after': {'code': 'x-max-priority: 10', 'note': 'same-day by 9:01', 'tag': 'AFTER'}, 'taglines': [('Urgent first, and its limits', 'gold')]}, 'highlight': {}}
