"""Scene definitions for the Backpressure with Project Reactor teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Backpressure with Project Reactor',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Backpressure pattern, built with Project Reactor, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Backpressure lets a slow consumer tell a fast producer how much it can take. [[slnc 300]] So work does not pile up in between. [[slnc 500]] Project Reactor is an open-source library for streams of data, and every stream in it carries this demand. [[slnc 600]] Think of a kitchen where the chef calls, two more tickets, and the waiter hands over exactly two. [[slnc 300]] A waiter who ignores the chef is stopped before the rail overflows. [[slnc 700]] In this video, the domain is an online shop's search indexer, reading a supplier's product feed. [[slnc 500]] By the end, you will hear what Reactor does with a source that ignores demand. [[slnc 300]] How to ask in batches. [[slnc 300]] And how to keep only the latest update."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A supplier feed: 10,000 products,', 'as fast as it can.', '', 'The indexer: 1 ms each.', '', 'Stock levels by the thousand.'],
         narration="Here is the scenario. [[slnc 400]] A supplier's feed sends ten thousand products, as fast as it can. [[slnc 500]] The search indexer takes a millisecond for each. [[slnc 500]] And stock-level updates arrive by the thousand, though only the current one matters."),
    dict(key='03-act-1', kind='console', title='Act One — A source that ignores demand',
         body='ONE. A source that ignores demand.\n  queue holds 256\n  OverflowException: stream stopped',
         narration="First demo: a source that ignores demand. [[slnc 400]] The supplier's feed pushes ten thousand products, as fast as it can. [[slnc 300]] It ignores how many the indexer asked for. [[slnc 600]] The indexer's queue holds two hundred and fifty-six. [[slnc 500]] Reactor does not let the pile grow. [[slnc 300]] It stops the stream, with an overflow error. [[slnc 500]] Only part of the feed is indexed. [[slnc 300]] The rest is refused, not quietly piled up."),
    dict(key='04-act-2', kind='console', title='Act Two — Produce only what is asked',
         body='TWO. Produce only what is asked.\n  indexed 10000\n  never more than 10 outstanding',
         narration='Second demo: a feed that produces only what is asked for. [[slnc 400]] The indexer asks for ten products. [[slnc 300]] It indexes them. [[slnc 300]] Then it asks for ten more. [[slnc 600]] All ten thousand are indexed. [[slnc 300]] And never more than ten were waiting to be delivered.'),
    dict(key='05-act-3', kind='console', title='Act Three — limitRate',
         body='THREE. limitRate.\n  requests: [10, 8, 8, 8] ...',
         narration='Third demo: let Reactor do the asking. [[slnc 400]] The limit rate operator asks for ten. [[slnc 600]] Then, each time three-quarters have been used, it asks for eight more. [[slnc 500]] So the next batch is already on its way, and the indexer never waits.'),
    dict(key='06-act-4', kind='console', title='Act Four — Only the latest',
         body='FOUR. Only the latest.\n  1000 updates, asked twice: [1000, 1]',
         narration='Fourth demo: only the latest matters. [[slnc 400]] A thousand stock-level updates arrive, for one mug. [[slnc 600]] The shop asks for one, and later for one more. [[slnc 500]] It gets the first, a thousand. [[slnc 300]] And the latest, one. [[slnc 500]] Everything in between was dropped. [[slnc 300]] Only the current level matters.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  buffer, drop or latest: choose',
         narration='Fifth demo: the bill. [[slnc 400]] Every source must choose. [[slnc 600]] A source that can wait, like a database cursor, is simplest. [[slnc 500]] A source that cannot wait must buffer, which costs memory. [[slnc 300]] Or drop, or keep only the latest, which loses data. [[slnc 500]] Reactor makes you say which. [[slnc 300]] And a buffer with no limit just hides the pile.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Reactor',
         body=['Subscribers request items.', 'Sources send no more.', '', 'limitRate: ask in batches.', 'onBackpressure...: what to do', 'when nobody is asking.'],
         narration="Let's name the pattern, in Reactor's words. [[slnc 400]] Subscribers request items. [[slnc 300]] Sources send no more than requested. [[slnc 500]] Limit rate asks in batches, for you. [[slnc 500]] And the on backpressure operators say what to do with items produced while nobody is asking."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Flux: the feed', 'BaseSubscriber: the indexer, asking', 'limitRate: asking in batches', 'onBackpressureLatest: newest only'],
         narration='Here is who does what. [[slnc 400]] A flux is the feed, a stream of products. [[slnc 500]] A base subscriber is the indexer, asking for ten at a time. [[slnc 500]] Limit rate asks in batches for you. [[slnc 300]] And on backpressure latest keeps only the newest stock level.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Spring WebFlux', 'RxJava, Akka Streams, Kotlin Flow', 'java.util.concurrent.Flow'],
         narration='You have probably met this already. [[slnc 400]] Spring WebFlux is built on Reactor. [[slnc 500]] RxJava, Akka Streams, and Kotlin Flow share the same ideas. [[slnc 500]] And the JDK has the same interfaces, in its Flow class.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Streams between fast and', 'slow parts.', '', 'Prefer sources that can wait.', 'Bound or drop on purpose.'],
         narration='So, when should you use it? [[slnc 400]] Whenever data streams between fast and slow parts of a system. [[slnc 500]] Prefer sources that can wait. [[slnc 300]] And when one cannot, bound it, drop, or keep the latest, on purpose.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Try', 'onBackpressureDrop.'],
         narration="That's Backpressure, with Project Reactor. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let the consumer set the pace, and decide on purpose what happens when a source cannot wait. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Use on backpressure drop in the stock demo, and print what is dropped. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Backpressure with Project Reactor Pattern  ·  Java 21', 'poster': {'headline': [('BACKPRESSURE', 'text'), ('WITH REACTOR', 'text')], 'before': {'code': 'push 10000, ignore demand', 'note': 'OverflowException', 'tag': 'BEFORE'}, 'after': {'code': '.limitRate(10)', 'note': 'asked for 10, then 8', 'tag': 'AFTER'}, 'taglines': [('Demand is part of every stream', 'gold')]}, 'highlight': {}}
