"""Scene definitions for the Backpressure teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Backpressure',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Backpressure pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Backpressure lets a slow consumer tell a fast producer to slow down. [[slnc 300]] So the work waiting in between stays small, instead of filling memory. [[slnc 600]] Think of a busy restaurant. [[slnc 300]] If the waiters take orders faster than the chefs can cook, the ticket rail overflows. [[slnc 300]] A good kitchen tells the front of house to stop seating tables for a while. [[slnc 300]] The pressure travels back, from the kitchen to the door. [[slnc 700]] In this video, the domain is an online shop's search indexer. [[slnc 300]] It reads a supplier's product feed, which is much faster than the indexer. [[slnc 500]] By the end, you will hear how the waiting pile grows without limit. [[slnc 300]] Three ways to push back. [[slnc 300]] And what backpressure costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The supplier sends 1,000 products a second.', '', 'The indexer handles 100 a second.', '', 'The rest waits in memory.'],
         narration="Here is the scenario. [[slnc 400]] The shop's search indexer reads a supplier's product feed. [[slnc 500]] The supplier sends a thousand products a second. [[slnc 300]] The indexer can handle a hundred. [[slnc 500]] Everything it has not reached yet waits in memory."),
    dict(key='03-act-1', kind='console', title='Act One — No backpressure',
         body='ONE. No backpressure.\n  1000 a second in, 100 a second out\n  after 10 s: 9000 waiting in memory\n  growing by 900 a second',
         narration='First demo: no backpressure. [[slnc 400]] The supplier sends a thousand products a second. [[slnc 300]] The indexer handles a hundred. [[slnc 600]] Everything not yet indexed waits in memory. [[slnc 300]] After ten seconds, nine thousand products are waiting. [[slnc 300]] And the pile grows by nine hundred every second. [[slnc 600]] A bigger feed, and the service runs out of memory.'),
    dict(key='04-act-2', kind='console', title='Act Two — A bounded buffer',
         body='TWO. A bounded buffer.\n  buffer of 500: never more than 500 waiting\n  all 10000 indexed in 100 s',
         narration="Second demo: a bounded buffer. [[slnc 400]] The buffer holds at most five hundred products. [[slnc 300]] When it is full, the supplier waits. [[slnc 600]] Never more than five hundred are waiting. [[slnc 300]] All ten thousand are indexed, in a hundred seconds. [[slnc 500]] The supplier has been slowed to the indexer's pace."),
    dict(key='05-act-3', kind='console', title='Act Three — Ask for what you can handle',
         body='THREE. Ask for what you can handle.\n  indexer: request(10), index, request(10)\n  10000 indexed, at most 10 in flight',
         narration='Third demo: the consumer asks for what it can handle. [[slnc 400]] Java has this built in, in the Flow interfaces. [[slnc 600]] The indexer asks for ten products. [[slnc 300]] It indexes them. [[slnc 300]] Then it asks for ten more. [[slnc 500]] The supplier never sends anything that was not asked for. [[slnc 300]] All ten thousand are indexed. [[slnc 300]] And never more than ten are in flight.'),
    dict(key='06-act-4', kind='console', title='Act Four — Keep only the latest',
         body='FOUR. Keep only the latest.\n  1000 updates for 10 products\n  10 delivered, the latest for each',
         narration='Fourth demo: when only the latest value matters, drop the rest. [[slnc 400]] The warehouse sends a thousand stock-level updates, for ten products. [[slnc 600]] The shop only needs the current stock level. [[slnc 300]] So it keeps one pending value per product. [[slnc 300]] A newer one replaces the older one. [[slnc 500]] Only ten updates are delivered. [[slnc 300]] The latest for each product.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  feed took 100 s instead of 10\n  drop only when the latest is enough',
         narration="Fifth demo: the bill. [[slnc 400]] Backpressure does not make the work faster. [[slnc 300]] It moves the waiting upstream. [[slnc 600]] The supplier's feed took a hundred seconds, instead of ten. [[slnc 300]] So the supplier must cope with being slowed. [[slnc 600]] And dropping is only safe when the latest value is all that matters. [[slnc 300]] Never for orders, or payments."),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['The consumer controls the pace.', '', 'Bound every buffer.', 'Pull in batches.', 'Or keep only the latest.'],
         narration="Let's name the pattern. [[slnc 400]] The consumer controls the pace, not the producer. [[slnc 500]] There are three common ways. [[slnc 300]] Bound the buffer, so the producer waits when it is full. [[slnc 300]] Let the consumer ask for a batch at a time. [[slnc 300]] Or, when only the latest value matters, drop the older ones."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['PullPublisher: sends only on request', 'Indexer: asks for 10 at a time', 'Conflator: keeps the latest per product', 'FeedSimulation: unbounded vs bounded'],
         narration="Here is who does what. [[slnc 400]] The publisher is the supplier's feed. [[slnc 300]] It sends only as many products as it has been asked for. [[slnc 500]] The indexer is the subscriber. [[slnc 300]] It asks for ten, indexes them, then asks again. [[slnc 500]] The conflator keeps one pending stock level per product. [[slnc 300]] And the feed simulation compares an unbounded buffer with a bounded one."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['java.util.concurrent.Flow', 'Reactor, RxJava, Akka Streams', 'Bounded blocking queues', 'TCP flow control'],
         narration="You have probably met this pattern already. [[slnc 400]] Java's Flow interfaces are the Reactive Streams standard. [[slnc 500]] Reactor, RxJava and Akka Streams are all built on it. [[slnc 300]] A bounded blocking queue makes the producer wait when it is full. [[slnc 500]] And the network itself does it. [[slnc 300]] TCP slows the sender when the receiver cannot keep up."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['A fast source can outrun', 'a slow sink.', '', 'Bound every buffer.', 'Prefer pull.', 'Drop only stale data.'],
         narration='So, when should you use it? [[slnc 400]] Whenever a fast source can outrun a slow consumer for long. [[slnc 500]] Bound every buffer. [[slnc 300]] Prefer consumers that ask for work. [[slnc 300]] Drop only data where the latest value is enough. [[slnc 500]] And make sure the producer can cope with being slowed.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', "are in the repository. Try the JDK's", 'SubmissionPublisher.'],
         narration="That's the Backpressure pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let the slow side set the pace, or memory will set it for you. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Replace the hand-written publisher with the JDK's submission publisher. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Backpressure Pattern  ·  Java 21', 'poster': {'headline': [('BACK', 'text'), ('PRESSURE', 'text')], 'before': {'code': 'push everything', 'note': '9000 waiting and growing', 'tag': 'BEFORE'}, 'after': {'code': 'request(10)', 'note': 'at most 10 in flight', 'tag': 'AFTER'}, 'taglines': [('Only send what can be handled', 'gold')]}, 'highlight': {}}
