"""Scene definitions for the Reactor teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Reactor',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Reactor pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] In a reactor, one thread waits for events on many connections at once. [[slnc 300]] When something happens on a connection, the thread hands that event to a short piece of code called a handler. [[slnc 300]] No connection gets a thread of its own. [[slnc 600]] Think of one waiter looking after a whole restaurant. [[slnc 300]] They do not stand at one table while the guests read the menu. [[slnc 300]] They watch the room, and go to whichever table raises a hand. [[slnc 700]] In this video, the domain is an online shop's warehouse. [[slnc 300]] Its stock server has a hundred shop tills connected all day, asking short questions like: how many kettles are in stock? [[slnc 500]] By the end, you will hear why a thread per connection wastes threads. [[slnc 300]] How a reactor serves them all with one. [[slnc 300]] How handlers work. [[slnc 300]] And the one rule you must never break."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A warehouse stock server.', '', '100 shop tills connected all day,', 'asking short questions now and then.', '', 'One thread per connection.'],
         narration='Here is the scenario. [[slnc 400]] The warehouse runs a stock server. [[slnc 500]] A hundred shop tills stay connected all day. [[slnc 300]] Now and then, each asks a short question. [[slnc 300]] How many kettles? [[slnc 300]] What does a mug cost? [[slnc 600]] The server gave every connection its own thread.'),
    dict(key='03-act-1', kind='console', title='Act One — A thread per connection',
         body='ONE. A thread per connection.\n  100 tills: 100 threads, mostly idle\n  stock KETTLE-1: 4',
         narration='First demo: a thread for every connection. [[slnc 400]] A hundred shop tills connect to the stock server. [[slnc 300]] The server starts a thread for each one. [[slnc 600]] That is a hundred threads. [[slnc 300]] Almost all of them are idle, waiting for their till to ask something. [[slnc 300]] Each one still holds memory. [[slnc 500]] Till one asks: how many kettles are in stock? [[slnc 300]] Four.'),
    dict(key='04-act-2', kind='console', title='Act Two — One reactor thread',
         body='TWO. One reactor thread.\n  100 tills connect to the reactor\n  stock KETTLE-1: 4\n  threads running handlers: 1',
         narration='Second demo: a reactor. [[slnc 400]] One thread waits on every connection at once. [[slnc 500]] Java gives us a selector for this. [[slnc 300]] It sleeps until some connection is ready, then says which one. [[slnc 600]] A hundred tills connect. [[slnc 300]] Till one asks about kettles: four. [[slnc 500]] Threads running handlers: one.'),
    dict(key='05-act-3', kind='console', title='Act Three — A handler per event',
         body='THREE. A handler per event.\n  new connection -> accept handler\n  bytes arrive -> read handler\n  price MUG-1: 800',
         narration='Third demo: each kind of event has its handler. [[slnc 400]] When a new connection arrives, the accept handler registers it, so the selector will watch it. [[slnc 500]] When bytes arrive, the read handler answers the line. [[slnc 600]] Till two asks the price of a mug. [[slnc 300]] Eight hundred pence.'),
    dict(key='06-act-4', kind='console', title='Act Four — Every till, one thread',
         body='FOUR. Every till, one thread.\n  100 tills ask at once\n  100 correct answers\n  threads running handlers: still 1',
         narration='Fourth demo: every till is answered by the one thread. [[slnc 400]] All hundred tills ask at the same moment. [[slnc 500]] The selector reports whichever connections are ready. [[slnc 300]] The one thread answers them, one after another. [[slnc 600]] A hundred correct answers. [[slnc 300]] Still one thread.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body="FIVE. The bill.\n  till 2: 300 ms report\n  till 3's quick question: over 200 ms\n  handlers must never block",
         narration='Fifth demo: the bill. [[slnc 400]] Till two asks for a report. [[slnc 300]] Its handler takes three hundred milliseconds. [[slnc 500]] Meanwhile, till three asks a quick question. [[slnc 300]] It waits over two hundred milliseconds, for an answer that takes microseconds. [[slnc 600]] The only thread was busy. [[slnc 300]] Like the waiter who stopped to cook. [[slnc 300]] So handlers must never block, and slow work goes to another thread.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['One thread waits on every', 'connection at once: a selector.', '', 'Event ready? Dispatch it', 'to its handler.', '', 'Handlers must be quick.'],
         narration="Let's name the pattern. [[slnc 400]] One thread waits on every connection at once. [[slnc 300]] In Java, a selector does the waiting. [[slnc 500]] When a connection is ready, the thread dispatches the event to its handler. [[slnc 300]] A new connection, to the accept handler. [[slnc 300]] Arriving bytes, to the read handler. [[slnc 500]] And every handler must be quick."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Selector: which connection is ready', 'Reactor: the loop and dispatch', 'Accept, read: the handlers', 'StockCommands: the answers', 'ThreadPerConnection: the old way'],
         narration='Here is who does what. [[slnc 400]] The selector says which connections are ready. [[slnc 500]] The reactor runs the loop: wait, then dispatch. [[slnc 500]] The accept handler registers new tills. [[slnc 300]] The read handler answers their questions, using stock commands. [[slnc 500]] And thread per connection is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Java NIO Selector', 'Netty event loops', 'Node.js, Nginx, Redis', 'Spring WebFlux, Vert.x'],
         narration="You have probably met this pattern already. [[slnc 400]] Java's NIO selector is the reactor's building block. [[slnc 500]] Netty's event loops are reactors. [[slnc 300]] So are Node.js, Nginx, and Redis. [[slnc 500]] And Spring WebFlux and Vert.x are built on them."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Many mostly idle connections.', '', 'Keep handlers short.', 'Slow work: a thread pool.', '', 'A few dozen connections?', 'Virtual threads are simpler.'],
         narration="So, when should you use it? [[slnc 400]] For servers with many connections that are mostly idle. [[slnc 300]] Usually through Netty, or a framework built on it. [[slnc 500]] Keep handlers short. [[slnc 300]] Hand slow work to a thread pool. [[slnc 500]] And for a few dozen connections, Java's virtual threads give you a thread per connection without the cost."),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Hand the report', 'to a thread pool.'],
         narration="That's the Reactor pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] One thread watches every connection, and every handler must be quick. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Hand the slow report to a thread pool, so the other tills never wait. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Reactor Pattern  ·  Java 21', 'poster': {'headline': [('REACTOR', 'text')], 'before': {'code': 'new Thread(client)', 'note': '100 tills, 100 threads', 'tag': 'BEFORE'}, 'after': {'code': 'selector.select()', 'note': '100 tills, 1 thread', 'tag': 'AFTER'}, 'taglines': [('One thread, many connections', 'gold')]}, 'highlight': {}}
