"""Scene definitions for the Event-Carried State Transfer teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Event-Carried State Transfer',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Event-Carried State Transfer pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] When data changes, put the new data in the event itself. [[slnc 300]] Then each service that cares keeps its own copy. [[slnc 300]] And never has to call the owner back. [[slnc 600]] Think of moving house. [[slnc 300]] You could send friends a card saying, I have moved, ring me for the address. [[slnc 300]] Or you send a card with the new address on it. [[slnc 300]] Each friend writes it in their own address book, and can post you a letter even when you are not answering the phone. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] A customer service owns the addresses, and a shipping service prints delivery labels. [[slnc 500]] By the end, you will hear why thin events tie services together. [[slnc 300]] How carrying the address sets shipping free. [[slnc 300]] Why the copy is briefly out of date. [[slnc 300]] And how version numbers handle events arriving out of order.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Shipping prints delivery labels.', '', 'The customer service owns addresses.', '', 'Its event said only:', 'a customer changed.'],
         narration="Here is the scenario. [[slnc 400]] The shipping service prints delivery labels. [[slnc 500]] The customer service owns the customers' addresses. [[slnc 500]] Its event only said, a customer changed. [[slnc 300]] So shipping had to ask for the address, every time."),
    dict(key='03-act-1', kind='console', title='Act One — A thin event, and a call back',
         body='ONE. A thin event, and a call back.\n  100 labels, 100 calls\n  customer service down: 0 of 100',
         narration="First demo: a thin event, and a call back. [[slnc 400]] The customer service's event only says, a customer changed. [[slnc 500]] So the shipping service asks for the address, every time it prints a label. [[slnc 300]] A hundred labels mean a hundred calls. [[slnc 600]] Now the customer service goes down. [[slnc 300]] Not a single label can be printed."),
    dict(key='04-act-2', kind='console', title='Act Two — The event carries the address',
         body='TWO. The event carries the address.\n  100 labels, 0 calls\n  customer service down: 100 of 100',
         narration="Second demo: the event carries the address. [[slnc 400]] Now the event says, customer one's address is now this. [[slnc 500]] The shipping service writes it into its own copy. [[slnc 300]] It keeps ten addresses. [[slnc 600]] A hundred labels need no calls at all. [[slnc 300]] And with the customer service down, all hundred labels are still printed."),
    dict(key='05-act-3', kind='console', title='Act Three — The copy lags behind',
         body='THREE. The copy lags behind.\n  label now: Leeds\n  after the event: York',
         narration='Third demo: the copy lags behind. [[slnc 400]] A customer moves, from Leeds to York. [[slnc 300]] The event is still on its way. [[slnc 600]] A label printed now, still goes to Leeds. [[slnc 500]] Once the event arrives, labels go to York. [[slnc 500]] The copy is always a little behind the owner. [[slnc 300]] This is called eventual consistency.'),
    dict(key='06-act-4', kind='console', title='Act Four — Events out of order',
         body='FOUR. Events out of order.\n  without versions: Hull\n  with versions: Bristol',
         narration='Fourth demo: events can arrive in the wrong order. [[slnc 400]] A customer moves to Hull, then to Bristol. [[slnc 300]] But the Bristol event arrives first. [[slnc 600]] A copy that just takes the last event it received, ends up with Hull. [[slnc 300]] The older address. [[slnc 600]] So each event carries a version number. [[slnc 300]] The copy ignores anything older than what it has. [[slnc 300]] And it keeps Bristol.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  an address copy in every service\n  personal data in more places',
         narration="Fifth demo: the bill. [[slnc 400]] Every service that cares keeps its own copy. [[slnc 500]] Shipping, invoicing and marketing, each hold every customer's address. [[slnc 500]] The events are bigger. [[slnc 300]] The copies are briefly out of date. [[slnc 300]] And personal data now lives in many places. [[slnc 300]] Each must protect it, and delete it when asked."),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['The event carries the new data.', '', 'Listeners keep their own copy.', '', 'No calls back to the owner.'],
         narration="Let's name the pattern. [[slnc 400]] The event carries the new data, not just the news that something changed. [[slnc 500]] Each listening service keeps its own copy, of just the data it needs. [[slnc 500]] And it never calls the owner back."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['CustomerService: owns addresses', 'AddressChanged: carries the address', 'ReplicaShipping: keeps its own copy', 'CallbackShipping: the old way'],
         narration='Here is who does what. [[slnc 400]] The customer service owns the addresses, and publishes each change. [[slnc 500]] The address changed event carries the customer, the new address, and a version number. [[slnc 500]] The shipping service keeps its own copy, and prints labels from it. [[slnc 300]] The call-back version of shipping is the old way.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Kafka topics with full records', 'Change data capture', 'CQRS read models'],
         narration='You have probably met this pattern already. [[slnc 400]] Kafka topics that carry whole records, not just identifiers. [[slnc 500]] Change data capture tools, which publish every changed database row. [[slnc 500]] And the read side of CQRS, built from events.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Many services read the data often.', '', 'Include a version.', 'Accept brief staleness.', 'Copy only what you need.'],
         narration='So, when should you use it? [[slnc 400]] When many services read the same data often. [[slnc 300]] And must keep working when its owner is down. [[slnc 500]] Include a version in every event. [[slnc 300]] Accept that copies are briefly out of date. [[slnc 300]] And copy only the fields each service needs.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Handle a', 'customer deleted event.'],
         narration="That's the Event-Carried State Transfer pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Send the new data, not just the news. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a customer deleted event, and remove the copy when it arrives. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Event-Carried State Transfer Pattern  ·  Java 21', 'poster': {'headline': [('EVENT-CARRIED', 'text'), ('STATE TRANSFER', 'text')], 'before': {'code': 'CustomerChanged(id)', 'note': 'call back for every label', 'tag': 'BEFORE'}, 'after': {'code': 'AddressChanged(id, address)', 'note': 'labels print from a local copy', 'tag': 'AFTER'}, 'taglines': [('Put the data in the event', 'gold')]}, 'highlight': {}}
