"""Scene definitions for the Message Filter teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Message Filter',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Message Filter pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A message filter sits between a channel of messages and one receiver. [[slnc 300]] It checks each message against a rule, and passes on only the ones that match. [[slnc 300]] The sender and the receiver never know it is there. [[slnc 600]] Think of the spam filter on your email. [[slnc 300]] The world sends you everything. [[slnc 300]] The filter decides what reaches your inbox. [[slnc 300]] And a good one keeps the rest in a spam folder, just in case. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Every order is published on an orders channel. [[slnc 300]] A gift-wrap service and a loyalty service each care about only some of them. [[slnc 500]] By the end, you will hear what happens when everyone gets everything. [[slnc 300]] How filters fix it. [[slnc 300]] How to chain them. [[slnc 300]] And where dropped messages go.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Every order goes on one channel.', '', 'Gift-wrap: gift orders only.', 'Loyalty: registered customers,', 'orders over £50.'],
         narration='Here is the scenario. [[slnc 400]] Every order the shop takes is published on one orders channel. [[slnc 500]] The gift-wrap service only cares about gift orders. [[slnc 300]] The loyalty service only cares about registered customers who spend over fifty pounds. [[slnc 500]] But the channel gives every service every order.'),
    dict(key='03-act-1', kind='console', title='Act One — Everything to everyone',
         body='ONE. Everything to everyone.\n  handed 10 orders, wrapped ORD-2, ORD-4\n  8 opened and ignored',
         narration='First demo: every service is handed every order. [[slnc 400]] Ten orders are published. [[slnc 300]] The gift-wrap service receives all ten. [[slnc 600]] It opens each one, and checks: is this a gift? [[slnc 300]] Two are: orders two and four. [[slnc 500]] Eight deliveries it had to open, and ignore. [[slnc 300]] And every other service repeats its own checks.'),
    dict(key='04-act-2', kind='console', title='Act Two — A filter',
         body='TWO. A filter.\n  gift-wrap receives: ORD-2, ORD-4\n  the filter dropped 8',
         narration='Second demo: a message filter, in front of the gift-wrap service. [[slnc 400]] The filter has one rule: gift orders only. [[slnc 600]] The gift-wrap service now receives exactly two orders. [[slnc 300]] The filter dropped the other eight. [[slnc 500]] Checkout still sends every order. [[slnc 300]] It does not know the filter exists.'),
    dict(key='05-act-3', kind='console', title='Act Three — Chained filters',
         body='THREE. Chained filters.\n  loyalty receives: ORD-1, ORD-4, ORD-6\n  dropped: 3 guests, then 4 under £50',
         narration='Third demo: filters can be chained. [[slnc 400]] The loyalty service wants registered customers only. [[slnc 300]] And only orders over fifty pounds. [[slnc 600]] Two filters, one after the other. [[slnc 300]] The first drops three guest orders. [[slnc 300]] The second drops four small orders. [[slnc 500]] The loyalty service receives orders one, four, and six.'),
    dict(key='06-act-4', kind='console', title='Act Four — A changed rule',
         body='FOUR. A changed rule.\n  over £60: ORD-1, ORD-4\n  sender and receiver unchanged',
         narration="Fourth demo: the rule changes, and nothing else does. [[slnc 400]] The bonus threshold rises to sixty pounds. [[slnc 500]] Only the filter's rule changes. [[slnc 300]] The loyalty service now receives orders one and four. [[slnc 500]] Checkout and the loyalty service were not changed."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  15 messages dropped, none kept\n  count them, or keep them somewhere',
         narration='Fifth demo: the bill. [[slnc 400]] A dropped message is gone. [[slnc 300]] Fifteen messages were dropped by the filters in this demo. [[slnc 300]] None was kept anywhere. [[slnc 600]] If a rule is wrong, real orders vanish, with no error. [[slnc 500]] So count the drops, or send them somewhere to be checked, like a spam folder.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Between the channel and a receiver:', 'a filter with one rule.', '', 'Match: pass it on.', 'No match: drop it, and count it.', '', 'Filters can be chained.'],
         narration="Let's name the pattern. [[slnc 400]] Between the channel and a receiver, put a filter with one rule. [[slnc 500]] If a message matches, pass it on. [[slnc 300]] If not, drop it, and count it. [[slnc 500]] Filters can be chained, to combine rules. [[slnc 300]] And the sender and receiver stay exactly as they were."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Channel: every order to every subscriber', 'MessageFilter: a rule and a next step', 'Gift-wrap, loyalty: the receivers', 'OrderEvent: the message'],
         narration='Here is who does what. [[slnc 400]] The channel delivers every order to every subscriber. [[slnc 500]] A message filter is itself a subscriber. [[slnc 300]] It holds a rule, the next step to pass matches to, and a count of what it dropped. [[slnc 500]] The gift-wrap and loyalty services are the receivers. [[slnc 300]] And an order event is the message.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel filter, Spring Integration filter', 'Cloud subscription filters', 'Kafka Streams filter', 'Email rules and spam filters'],
         narration='You have probably met this pattern already. [[slnc 400]] Apache Camel and Spring Integration both have a filter step. [[slnc 500]] Cloud messaging services let each subscription have a filter. [[slnc 300]] Kafka Streams has one too. [[slnc 500]] And every email rule, and every spam filter, is a message filter.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Receivers on a shared channel', 'that want only some messages.', '', 'Small rules, chained.', 'Always count or keep the drops.'],
         narration='So, when should you use it? [[slnc 400]] When receivers on a shared channel want only some of the messages. [[slnc 500]] Keep each rule small, and chain them. [[slnc 300]] And always count, or keep, what you drop. [[slnc 500]] When many receivers want very different subsets, a content-based router may be clearer.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Keep dropped messages', 'in a discard channel.'],
         narration="That's the Message Filter pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let a filter decide what reaches each receiver, and never lose track of what it drops. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Send dropped messages to a discard channel, and print them. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Message Filter Pattern  ·  Java 21', 'poster': {'headline': [('MESSAGE', 'text'), ('FILTER', 'text')], 'before': {'code': 'if (!order.gift()) return;', 'note': 'in every receiver', 'tag': 'BEFORE'}, 'after': {'code': 'new MessageFilter(gift, next)', 'note': 'only what you want', 'tag': 'AFTER'}, 'taglines': [('Only the messages you want', 'gold')]}, 'highlight': {}}
