"""Scene definitions for the Message Filter with Apache Camel teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Message Filter with Apache Camel',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Message Filter pattern, built with Apache Camel, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A message filter sits in front of a receiver. [[slnc 300]] It lets through only the messages that receiver wants, and drops the rest. [[slnc 500]] Apache Camel is an open-source library for moving messages, and it has a filter step built in. [[slnc 600]] Think of a company post room. [[slnc 300]] Each department gives it a rule, such as, only letters marked gift wrap. [[slnc 300]] The post room applies the rules. [[slnc 300]] And a good one keeps a tray of letters nobody wanted. [[slnc 700]] In this video, the domain is an online shop, whose checkout announces every order to its services. [[slnc 500]] By the end, you will hear how a filter step works in Camel. [[slnc 300]] How to change a rule while everything runs. [[slnc 300]] And why a discard channel matters.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Checkout announces 10 orders.', '', 'Gift-wrap wants gift orders.', 'Loyalty wants registered', 'customers over £50.'],
         narration='Here is the scenario. [[slnc 400]] Checkout announces ten orders. [[slnc 500]] The gift-wrap service only wants gift orders. [[slnc 300]] The loyalty service only wants registered customers, spending over fifty pounds. [[slnc 500]] Without filters, each service was handed all ten.'),
    dict(key='03-act-1', kind='console', title='Act One — Every service gets every order',
         body='ONE. Every service gets every order.\n  gift-wrap handed 10 orders',
         narration='First demo: every service is handed every order. [[slnc 400]] Checkout sends each order to one place. [[slnc 300]] Camel copies it to every service. [[slnc 600]] The gift-wrap service is handed all ten orders. [[slnc 300]] It must open each one, to see if it is a gift.'),
    dict(key='04-act-2', kind='console', title='Act Two — A filter in front',
         body='TWO. A filter in front.\n  gift-wrap receives [ORD-2, ORD-4]\n  dropped 8',
         narration='Second demo: a filter in front of the gift-wrap service. [[slnc 400]] The rule is one short expression. [[slnc 300]] Is this order a gift? [[slnc 600]] Only two orders get through. [[slnc 300]] O R D two, and O R D four. [[slnc 300]] Eight are dropped. [[slnc 500]] Checkout was not changed. [[slnc 300]] It does not know the filter exists.'),
    dict(key='05-act-3', kind='console', title='Act Three — Two conditions',
         body='THREE. Two conditions.\n  loyalty receives [ORD-1, ORD-4, ORD-6]',
         narration='Third demo: a rule with two conditions. [[slnc 400]] The customer must be registered. [[slnc 300]] And the order must be over fifty pounds. [[slnc 600]] The loyalty service receives three orders. [[slnc 300]] O R D one, four, and six.'),
    dict(key='06-act-4', kind='console', title='Act Four — Change the rule while running',
         body='FOUR. Change the rule while running.\n  threshold £60: [ORD-1, ORD-4]\n  no restart',
         narration='Fourth demo: change the rule while everything keeps running. [[slnc 400]] The threshold is read from the settings, as each order passes. [[slnc 600]] It is raised to sixty pounds. [[slnc 300]] Now only O R D one and four get through. [[slnc 500]] No route was changed. [[slnc 300]] Nothing was restarted.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill, and a discard channel',
         body='FIVE. The bill, and a discard channel.\n  discard channel: 8 orders kept\n  rules checked only at run time',
         narration='Fifth demo: the bill. [[slnc 400]] A filter drops messages. [[slnc 300]] And a wrong rule drops them silently. [[slnc 600]] So rejected orders are sent to a discard channel instead. [[slnc 300]] Eight orders are kept there, and can be counted. [[slnc 600]] The costs. [[slnc 300]] Rules written in text, only checked when they run. [[slnc 300]] And more than ten library files, instead of none.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Camel',
         body=['filter(rule) in front', 'of each receiver.', '', 'Rules in the Simple language.', '', 'Rejects to a discard channel.'],
         narration="Let's name the pattern, in Camel's words. [[slnc 400]] A filter step, with a rule, in front of each receiver. [[slnc 500]] The rule is written in Camel's Simple language. [[slnc 500]] And rejected messages go to a discard channel, where they can be counted."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShopRoutes: the routes and rules', 'Rules: the changing threshold', 'OrderEvent: the message', 'Received: what each service got'],
         narration='Here is who does what. [[slnc 400]] Shop routes holds every route, and every rule. [[slnc 500]] Rules holds the threshold, which can change while the routes run. [[slnc 500]] Order event is the message. [[slnc 300]] And received records what each service was given.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel filter()', 'Spring Integration @Filter', 'JMS message selectors', 'Email rules'],
         narration="You have probably met this already. [[slnc 400]] Camel's filter step, and Spring Integration's filter. [[slnc 500]] Message selectors in Java messaging. [[slnc 500]] And the rules in your email, that sort or discard incoming mail."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Many services, same messages.', 'Rules that change.', '', 'Keep rules short.', 'Add a discard channel.'],
         narration='So, when should you use Camel for this? [[slnc 400]] When many services subscribe to the same messages, and the rules change. [[slnc 500]] Keep each rule short. [[slnc 300]] And add a discard channel, so nothing is lost without a trace.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a discard', 'channel to the gift filter.'],
         narration="That's the Message Filter, with Apache Camel. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Put a rule in front of each receiver, and keep what it rejects. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a discard channel to the gift-wrap filter too. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Message Filter with Apache Camel Pattern  ·  Java 21', 'poster': {'headline': [('MESSAGE FILTER', 'text'), ('WITH CAMEL', 'text')], 'before': {'code': 'every service gets 10 orders', 'note': 'each checks for itself', 'tag': 'BEFORE'}, 'after': {'code': 'filter(simple("${body.gift}"))', 'note': 'gift-wrap gets 2', 'tag': 'AFTER'}, 'taglines': [('A filter in front of each service', 'gold')]}, 'highlight': {}}
