"""Scene definitions for the Lock-Free Compare-and-Swap teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Lock-Free Compare-and-Swap',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Lock-Free Compare-and-Swap pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Compare-and-swap changes a shared value only if it still holds what you saw. [[slnc 300]] If someone else changed it first, you read it again, and try again. [[slnc 300]] Nobody ever waits for a lock. [[slnc 600]] Think of booking a concert seat online. [[slnc 300]] You pick seat twelve on the map. [[slnc 300]] When you press book, it is booked only if seat twelve is still free. [[slnc 300]] If someone beat you to it, you look at the map again, and pick another. [[slnc 700]] In this video, the domain is an online shop's flash sale. [[slnc 300]] A hundred kettles, and eight buyer threads racing to buy them. [[slnc 500]] By the end, you will hear how a shop sells more kettles than it has. [[slnc 300]] How a lock fixes it, slowly. [[slnc 300]] How compare-and-swap fixes it without a lock. [[slnc 300]] And its limits."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A flash sale: 100 kettles.', '', '8 buyer threads, each trying', 'to buy 50.', '', 'Read the count, check for fraud,', 'write the count minus one.'],
         narration='Here is the scenario. [[slnc 400]] A flash sale: a hundred kettles. [[slnc 500]] Eight buyer threads, each trying to buy fifty. [[slnc 500]] To buy one, a thread reads the stock count, runs a quick fraud check, and then writes back the count, minus one.'),
    dict(key='03-act-1', kind='console', title='Act One — Check, then act',
         body='ONE. Check, then act.\n  sold: more than 100, from a stock of 100\n  two buyers took the same kettle',
         narration='First demo: check, then act, with no protection. [[slnc 400]] A hundred kettles. [[slnc 300]] Eight buyer threads, each trying fifty times. [[slnc 600]] Each buyer reads the stock count, runs a quick fraud check, then writes back the count, minus one. [[slnc 500]] Two buyers read the same count at the same moment. [[slnc 300]] Both take the same kettle. [[slnc 500]] The shop sells more than a hundred kettles, from a stock of a hundred.'),
    dict(key='04-act-2', kind='console', title='Act Two — A lock',
         body='TWO. A lock.\n  kettles sold: 100; left: 0\n  everyone else waits in line',
         narration='Second demo: a lock, one buyer at a time. [[slnc 400]] Only the buyer holding the lock may look at the stock and take a kettle. [[slnc 500]] Exactly a hundred kettles sold. [[slnc 300]] None left. [[slnc 500]] Correct. [[slnc 300]] But every other buyer waits in line while one checks.'),
    dict(key='05-act-3', kind='console', title='Act Three — Compare-and-swap',
         body='THREE. Compare-and-swap.\n  kettles sold: 100; left: 0\n  no locks; losers look again',
         narration='Third demo: compare-and-swap. [[slnc 400]] Each buyer reads the count, and runs the fraud check. [[slnc 300]] Then it says: take one, but only if the count is still what I saw. [[slnc 600]] The processor does that in one indivisible step. [[slnc 500]] If another buyer got there first, the swap fails. [[slnc 300]] The buyer simply reads the count again, and retries. [[slnc 500]] Exactly a hundred sold. [[slnc 300]] None left. [[slnc 300]] And no thread ever waited for a lock.'),
    dict(key='06-act-4', kind='console', title='Act Four — The loop in one call',
         body='FOUR. The loop in one call.\n  getAndUpdate(s -> s > 0 ? s - 1 : s)\n  sold 100, left 0',
         narration="Fourth demo: the loop in one call. [[slnc 400]] Java's atomic integer has a method, get and update. [[slnc 300]] You give it a rule: if there is stock, take one. [[slnc 500]] It runs the compare-and-swap, and retries it for you. [[slnc 500]] A hundred sold. [[slnc 300]] None left."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  stock 99, buyers recorded 0\n  heavy contention: threads spin',
         narration='Fifth demo: the bill. [[slnc 400]] Compare-and-swap protects one value at a time. [[slnc 500]] A buyer takes a kettle. [[slnc 300]] Then its thread stops, before it records who bought it. [[slnc 500]] Stock says ninety-nine. [[slnc 300]] Buyers recorded: zero. [[slnc 300]] Two atomic values are not one atomic change. [[slnc 600]] And when many threads fight over one value, they keep retrying, instead of waiting quietly.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Read the value.', 'Work out the new one.', 'Swap it in only if it is unchanged.', '', 'Swap failed? Read again, retry.', '', 'No locks.'],
         narration="Let's name the pattern. [[slnc 400]] Read the value. [[slnc 300]] Work out the new value. [[slnc 500]] Then swap it in, but only if the value is still what you read. [[slnc 300]] The processor does that check and change as one indivisible step. [[slnc 500]] If the swap fails, someone else changed it. [[slnc 300]] Read again, and retry."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['AtomicInteger: the shared count', 'compareAndSet: swap if unchanged', 'CasStock: the retry loop', 'UnsafeStock, LockedStock:', 'the alternatives'],
         narration='Here is who does what. [[slnc 400]] An atomic integer holds the shared stock count. [[slnc 500]] Compare and set is the indivisible step: swap if unchanged. [[slnc 500]] CAS stock runs the retry loop. [[slnc 500]] And unsafe stock and locked stock are the alternatives, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['AtomicInteger, AtomicReference', 'ConcurrentHashMap', 'UPDATE ... WHERE version = 7', 'git push, rejected'],
         narration="You have probably met this pattern already. [[slnc 400]] Java's atomic integer, atomic long, and atomic reference. [[slnc 300]] And the concurrent hash map, which is built on them. [[slnc 500]] Databases do the same with a version column: update the row, only if its version is still seven. [[slnc 500]] And git refuses your push if the branch moved since you last pulled."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['One shared value: counters,', 'stock, flags, references.', '', 'Prefer updateAndGet.', 'Hot counters: LongAdder.', '', 'Several values together? A lock.'],
         narration='So, when should you use it? [[slnc 400]] For one shared value at a time: counters, stock levels, flags, references. [[slnc 500]] Prefer update and get, rather than writing your own loop. [[slnc 300]] For very busy counters, use long adder. [[slnc 500]] And when several values must change together, use a lock, or a database transaction.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Count the retries', 'with more buyers.'],
         narration="That's the Lock-Free Compare-and-Swap pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Change it only if it has not changed, and if it has, look again. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Count the retries with two, eight, and thirty-two buyers, and see how they grow. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Lock-Free Compare-and-Swap Pattern  ·  Java 21', 'poster': {'headline': [('COMPARE', 'text'), ('AND SWAP', 'text')], 'before': {'code': 'left = seen - 1', 'note': 'more than 100 sold', 'tag': 'BEFORE'}, 'after': {'code': 'compareAndSet(seen, seen - 1)', 'note': 'exactly 100, no locks', 'tag': 'AFTER'}, 'taglines': [("Change it only if it hasn't changed", 'gold')]}, 'highlight': {}}
