"""Scene definitions for the Gateway Offloading with Spring Cloud Gateway teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Gateway Offloading with Spring Cloud Gateway',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Gateway Offloading pattern, with Spring Cloud Gateway, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Many services need the same chores on every request. [[slnc 300]] Checking who the caller is, limiting how often they call, compressing the answer. [[slnc 300]] Gateway offloading moves those chores into the gateway in front of them. [[slnc 500]] Spring Cloud Gateway is an open-source gateway, built on Spring. [[slnc 600]] Think of an office reception desk. [[slnc 300]] Visitors sign in once at the front door. [[slnc 300]] The teams upstairs trust that anyone in the corridor was checked. [[slnc 700]] In this video, the domain is an online shop, with catalog, cart and orders services. [[slnc 500]] By the end, you will hear how three copies of a check drifted apart. [[slnc 300]] How one gateway filter replaces them. [[slnc 300]] And why there must be no side door.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Catalog, cart and orders.', '', 'Each checked the token itself.', '', 'Orders forgot expiry.'],
         narration="Here is the scenario. [[slnc 400]] The shop has three services. [[slnc 300]] Catalog, cart and orders. [[slnc 500]] Each one checked the customer's sign-in token itself. [[slnc 500]] The orders service forgot to check whether the token had expired."),
    dict(key='03-act-1', kind='console', title='Act One — Every service checks for itself',
         body='ONE. Every service checks for itself.\n  catalog, cart: 401 token expired\n  orders: 200 orders for ana',
         narration="First demo: every service checks the sign-in token itself. [[slnc 400]] The customer's token expired a minute ago. [[slnc 600]] The catalog service refuses it. [[slnc 300]] The cart service refuses it. [[slnc 300]] The orders service lets the customer in. [[slnc 600]] Its copy of the check forgot about expiry."),
    dict(key='04-act-2', kind='console', title='Act Two — One check at the gateway',
         body='TWO. One check at the gateway.\n  expired -> all three: 401\n  valid -> orders: 200',
         narration='Second demo: Spring Cloud Gateway checks the token, once. [[slnc 400]] A filter runs before any route. [[slnc 600]] The expired token is refused for all three services. [[slnc 500]] A valid token gets through. [[slnc 300]] The gateway tells the orders service who the customer is. [[slnc 500]] The services hold no sign-in code at all.'),
    dict(key='05-act-3', kind='console', title='Act Three — Rate limiting',
         body='THREE. Rate limiting.\n  8 requests: 5 passed, 3 refused (429)',
         narration='Third demo: rate limiting at the gateway. [[slnc 400]] Each customer may make five requests a minute. [[slnc 600]] Eight requests in a row. [[slnc 300]] Five pass. [[slnc 300]] Three are refused, with too many requests. [[slnc 500]] No service had to write a limiter.'),
    dict(key='06-act-4', kind='console', title='Act Four — Compression',
         body='FOUR. Compression.\n  catalog: 10093 bytes plain\n  gzip: under a fifth',
         narration="Fourth demo: compression at the gateway. [[slnc 400]] The catalog page is about ten thousand bytes. [[slnc 600]] Three settings on the gateway's server switch compression on. [[slnc 500]] The page arrives compressed, at under a fifth of its size. [[slnc 300]] The catalog service knows nothing about it."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body="FIVE. The bill.\n  via gateway, spoofed ben: ana's orders\n  straight to orders as ben: 200",
         narration="Fifth demo: the bill. [[slnc 400]] Through the gateway, a caller claims to be Ben. [[slnc 300]] The gateway removes the claim, and says Ana. [[slnc 600]] But straight to the orders service, the same claim is believed. [[slnc 300]] Ben's orders. [[slnc 600]] The services must be reachable only through the gateway. [[slnc 300]] And every request passes one more hop."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Spring Cloud Gateway',
         body=['Routes: one per service.', '', 'A global filter: sign-in,', 'limit, pass on the customer.', '', 'Server settings: compression.'],
         narration="Let's name the pattern, in Spring Cloud Gateway's words. [[slnc 400]] One route for each service. [[slnc 500]] A global filter, run before every route, checks sign-in, limits requests, and passes on who the customer is. [[slnc 500]] And server settings switch on compression."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['SignInFilter: the chores', 'GatewayApp: the routes', 'ShopService: the business', 'Tokens: the sign-in'],
         narration='Here is who does what. [[slnc 400]] The sign-in filter does the chores, for every route. [[slnc 500]] The gateway app holds the routes. [[slnc 500]] And each shop service just does its own business, trusting the gateway.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Spring Cloud Gateway filters', 'Kong, NGINX, Envoy plugins', 'Cloud API gateways'],
         narration='You have probably met this already. [[slnc 400]] Filters in Spring Cloud Gateway. [[slnc 500]] Authentication and rate-limit plugins in Kong, NGINX and Envoy. [[slnc 500]] And the gateways every cloud provider offers.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Many services, same chores.', '', 'Strip trusted headers.', 'Share limiter state.', 'No side doors.'],
         narration='So, when should you use it? [[slnc 400]] When many services need exactly the same chores. [[slnc 500]] Strip any header the services will trust. [[slnc 300]] Share rate-limit counts across gateways. [[slnc 300]] And leave no side doors.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Use the', 'Redis rate limiter.'],
         narration="That's Gateway Offloading, with Spring Cloud Gateway. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Do the shared chores once, at the door, and lock every other door. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Replace the in-memory limit with the gateway's own rate limiter, backed by Redis. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Gateway Offloading with Spring Cloud Gateway Pattern  ·  Java 21', 'poster': {'headline': [('GATEWAY OFFLOADING', 'text'), ('WITH SPRING CLOUD', 'text')], 'before': {'code': '3 services, 3 token checks', 'note': 'orders forgot expiry', 'tag': 'BEFORE'}, 'after': {'code': 'GlobalFilter at the gateway', 'note': '401 for all three', 'tag': 'AFTER'}, 'taglines': [('The chores, done once', 'gold')]}, 'highlight': {}}
