"""Scene definitions for the Secrets Manager with OpenBao teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Secrets Manager with OpenBao',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Secrets Manager pattern, with a real OpenBao server, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A secrets manager keeps passwords and keys out of the code, in one guarded store. [[slnc 300]] Each service may read only what it is allowed, and secrets can be changed without a rebuild. [[slnc 500]] OpenBao is an open-source secrets manager, the community fork of HashiCorp Vault, with the same interface. [[slnc 600]] Think of a bank's safe-deposit room. [[slnc 300]] Each person's card opens only their boxes. [[slnc 300]] And a lost card is cancelled at once. [[slnc 700]] In this video, the domain is an online shop's key for its card-payment company. [[slnc 500]] By the end, you will hear how policies and tokens decide who may read it. [[slnc 300]] How the key is rotated. [[slnc 300]] And how a leaked token is cancelled."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The payment key was in the code.', '', 'Built into three services.', '', 'Readable by anyone', 'with the repository.'],
         narration="Here is the scenario. [[slnc 400]] The shop's payment key was written in the code. [[slnc 500]] It was built into three services. [[slnc 500]] Anyone who could read the code could read the key."),
    dict(key='03-act-1', kind='console', title='Act One — A key in the code',
         body='ONE. A key in the code.\n  PAYMENT_KEY = "pay-key-v1"',
         narration='First demo: the payment key is written in the code. [[slnc 400]] It is built into three services. [[slnc 600]] Everyone who can read the code can read the key. [[slnc 300]] And every old copy stays in the history.'),
    dict(key='04-act-2', kind='console', title='Act Two — Policies and tokens',
         body='TWO. Policies and tokens.\n  checkout: 200, pay-key-v1\n  catalog: 403, permission denied',
         narration='Second demo: the key lives in OpenBao. [[slnc 400]] A policy called payments allows reading that one key. [[slnc 600]] Checkout has a token carrying that policy. [[slnc 300]] It reads the key. [[slnc 500]] The catalog service has a token without it. [[slnc 300]] Refused. [[slnc 300]] Permission denied.'),
    dict(key='05-act-3', kind='console', title='Act Three — Versions and rotation',
         body='THREE. Versions and rotation.\n  version 2: pay-key-v2\n  version 1 still readable',
         narration='Third demo: rotating the key. [[slnc 400]] Writing a new value creates version two. [[slnc 300]] Checkout now reads it, with no rebuild. [[slnc 600]] Version one is kept, and can still be read. [[slnc 300]] So old and new can overlap, for a grace period.'),
    dict(key='06-act-4', kind='console', title='Act Four — Revoke a leaked token',
         body='FOUR. Revoke a leaked token.\n  leaked token: 403\n  new token: 200',
         narration="Fourth demo: checkout's token leaks. [[slnc 400]] It is revoked, at once. [[slnc 600]] The attacker tries it. [[slnc 300]] Refused. [[slnc 500]] Checkout is given a new token, and reads the key as before. [[slnc 300]] And the key itself can be rotated too."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  secret zero: platform identity\n  dev mode is not production',
         narration='Fifth demo: the bill. [[slnc 400]] Every service still needs one first credential, to get its token. [[slnc 300]] Let the platform provide that identity. [[slnc 600]] And this server runs in development mode. [[slnc 300]] In memory, with a master token. [[slnc 500]] Production needs real storage, and high availability. [[slnc 300]] Because every service now depends on it to start.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in OpenBao',
         body=['Secrets at paths, with versions.', '', 'Policies: who may read a path.', 'Tokens: one per service,', 'revocable.'],
         narration="Let's name the pattern, in OpenBao's words. [[slnc 400]] Secrets live at paths, and every change is a new version. [[slnc 500]] A policy says who may read a path. [[slnc 300]] And each service holds a token, carrying its policies, that can be revoked."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['OpenBao: the secrets server', 'Secrets: store, policy, tokens', 'Checkout: reads with its token', 'Catalog: has no permission'],
         narration='Here is who does what. [[slnc 400]] OpenBao is the secrets server, in a container. [[slnc 500]] The secrets class stores the key, writes the policy, and issues tokens. [[slnc 500]] Checkout reads the key with its token. [[slnc 300]] And the catalog service has no permission at all.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['HashiCorp Vault', 'AWS, Azure, Google secret stores', 'Spring Cloud Vault'],
         narration='You have probably met this already. [[slnc 400]] HashiCorp Vault, whose interface OpenBao keeps. [[slnc 500]] The secret stores of every big cloud provider. [[slnc 500]] And Spring Cloud Vault, which reads these servers into a Spring application.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Every real secret.', '', 'Narrow policies.', 'A token per service.', 'Rotate as versions.', 'Revoke leaks at once.'],
         narration='So, when should you use it? [[slnc 400]] For every secret that guards real money or data. [[slnc 500]] Write narrow policies. [[slnc 300]] Give each service its own token. [[slnc 300]] Rotate secrets as versions. [[slnc 300]] And revoke leaks at once.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Try', 'AppRole login.'],
         narration="That's the Secrets Manager, with OpenBao. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Keep secrets in one guarded place, give each service only what it needs, and be ready to cancel any key. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts OpenBao for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Log in with an app role, instead of a token issued by hand. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Secrets Manager with OpenBao Pattern  ·  Java 21', 'poster': {'headline': [('SECRETS MANAGER', 'text'), ('WITH OPENBAO', 'text')], 'before': {'code': 'PAYMENT_KEY = "pay-key-v1"', 'note': 'readable by everyone', 'tag': 'BEFORE'}, 'after': {'code': 'GET /v1/secret/data/payment-key', 'note': 'policy, token, version', 'tag': 'AFTER'}, 'taglines': [('Open-source Vault, for real', 'gold')]}, 'highlight': {}}
