"""Scene definitions for the Broker teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Broker',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Broker pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A broker sits between clients and services. [[slnc 300]] Services register with it by name. [[slnc 300]] Clients call it by name. [[slnc 300]] The broker finds the service, forwards the call, and returns the answer. [[slnc 600]] Think of an old hotel switchboard. [[slnc 300]] Guests ask the operator to put them through to room service. [[slnc 300]] They never need the extension number. [[slnc 300]] When room service moves office, only the operator's list changes. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Its checkout calls a stock service and a price service, which run as small web servers. [[slnc 500]] By the end, you will hear why hard-coded addresses break. [[slnc 300]] How a broker fixes it. [[slnc 300]] How it handles moves and several copies. [[slnc 300]] And what it costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Checkout calls a stock service', 'and a price service.', '', 'Their addresses were written', 'into checkout.', '', 'Then the stock service moved.'],
         narration="Here is the scenario. [[slnc 400]] Checkout calls a stock service, and a price service. [[slnc 500]] Their addresses were written into checkout's configuration. [[slnc 500]] Then the stock service moved to a new machine."),
    dict(key='03-act-1', kind='console', title='Act One — A hard-coded address',
         body='ONE. A hard-coded address.\n  stock KETTLE-1 -> 4\n  the stock service moves\n  old address: FAILED, connection refused',
         narration="First demo: checkout knows the stock service's address. [[slnc 400]] It asks: how many kettles? [[slnc 300]] Four. [[slnc 600]] Then the stock service moves to a new machine, with a new address. [[slnc 500]] Checkout still calls the old address. [[slnc 300]] Connection refused. [[slnc 300]] Every order fails, until checkout itself is changed."),
    dict(key='04-act-2', kind='console', title='Act Two — Calls through a broker',
         body='TWO. Calls through a broker.\n  stock registers as "stock"\n  /call/stock?sku=KETTLE-1 -> 4',
         narration="Second demo: a broker. [[slnc 400]] The stock service registers with the broker, under the name stock. [[slnc 500]] Checkout now calls the broker, by name: stock, how many kettles? [[slnc 300]] The broker finds the stock service, forwards the question, and passes back the answer. [[slnc 300]] Four. [[slnc 600]] Checkout knows only one address: the broker's."),
    dict(key='05-act-3', kind='console', title='Act Three — A service moves',
         body='THREE. A service moves.\n  stock moves, re-registers\n  checkout, unchanged: MUG-1 -> 20',
         narration='Third demo: a service moves, and clients do not notice. [[slnc 400]] The stock service moves again. [[slnc 300]] This time it tells the broker its new address. [[slnc 600]] Checkout does not change at all. [[slnc 300]] It asks for mugs. [[slnc 300]] Twenty.'),
    dict(key='06-act-4', kind='console', title='Act Four — Several instances',
         body='FOUR. Several instances.\n  call 1: from price-a\n  call 2: from price-b\n  call 3: price-a; call 4: price-b',
         narration='Fourth demo: several instances of one service. [[slnc 400]] Two price services register, both under the name price. [[slnc 500]] Checkout calls four times. [[slnc 300]] Price A answers. [[slnc 200]] Then price B. [[slnc 200]] Then A. [[slnc 200]] Then B. [[slnc 600]] The broker takes turns. [[slnc 300]] Checkout never chose.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  one call = 2 network requests\n  broker stops: FAILED',
         narration='Fifth demo: the bill. [[slnc 400]] One call from checkout is now two network requests. [[slnc 300]] Checkout to broker, and broker to service. [[slnc 600]] And the broker is the one thing everyone needs. [[slnc 300]] When it stops, every service is unreachable, even though they are all still running.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Services register by name.', '', 'Clients call the broker by name.', '', 'The broker finds a live instance,', 'forwards, and returns the answer.'],
         narration="Let's name the pattern. [[slnc 400]] Each service registers with the broker, under a name. [[slnc 500]] Clients send every call to the broker, by name. [[slnc 500]] The broker finds a live instance of that service, forwards the call, and returns the answer. [[slnc 300]] Clients never know where services live."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Broker: names -> addresses, forwards', 'Stock, price: the services', 'Checkout: the client', 'Http: the plumbing'],
         narration="Here is who does what. [[slnc 400]] The broker keeps a list of names and addresses, and forwards calls. [[slnc 500]] The stock and price services register themselves, and answer questions. [[slnc 500]] Checkout is the client. [[slnc 300]] It knows one address: the broker's. [[slnc 300]] And the H T T P class is just the plumbing."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Java RMI registry, CORBA', 'Consul, Eureka, etcd', 'Kubernetes services', 'API gateways, service meshes'],
         narration="You have probably met this pattern already. [[slnc 400]] Java's R M I registry, and CORBA, were brokers. [[slnc 500]] Service registries such as Consul and Eureka do the same job today. [[slnc 500]] Kubernetes gives each service a stable name, whatever machines it runs on. [[slnc 300]] And gateways and service meshes route calls by name."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Services that move, scale', 'or change often.', '', 'Run the broker redundantly.', '', 'Avoid the hop? Look up once,', 'then call directly.'],
         narration='So, when should you use it? [[slnc 400]] When services move, scale, or change often. [[slnc 500]] Run the broker as several copies, so it is never the one thing that stops everything. [[slnc 500]] And to avoid the extra hop, clients can ask the broker for an address once, then call the service directly.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Drop instances', 'that stop answering.'],
         narration="That's the Broker pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Call services by name, and let the broker know where they live. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make the broker drop an instance when calls to it fail. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Broker Pattern  ·  Java 21', 'poster': {'headline': [('BROKER', 'text')], 'before': {'code': 'http://10.0.0.7:8081', 'note': 'moved: every order failed', 'tag': 'BEFORE'}, 'after': {'code': '/call/stock?sku=...', 'note': 'by name, wherever it lives', 'tag': 'AFTER'}, 'taglines': [('Call by name, not by address', 'gold')]}, 'highlight': {}}
