"""Scene definitions for the Secure Gateway with NGINX teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Secure Gateway with NGINX',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Secure Gateway pattern, also called the Gatekeeper, with NGINX. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] The services that hold passwords and data never face the internet. [[slnc 300]] A separate gatekeeper does. [[slnc 300]] It holds no secrets, and lets through only a few allowed kinds of request. [[slnc 500]] NGINX is the open-source web server and reverse proxy in front of much of the web. [[slnc 600]] Think of a bank teller behind a counter, with no key to the vault. [[slnc 700]] In this video, the domain is an online shop's order service, which holds the database password. [[slnc 500]] By the end, you will hear how two tricks exported every order. [[slnc 300]] How a short NGINX configuration stops them. [[slnc 300]] And what the gate costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The order service faced the internet.', '', 'It held the database password.', '', 'An admin header and an export', 'page were reachable by anyone.'],
         narration="Here is the scenario. [[slnc 400]] The shop's order service answered the internet directly. [[slnc 500]] It held the database password. [[slnc 500]] And an internal admin header, and an admin export page, were reachable by anyone."),
    dict(key='03-act-1', kind='console', title='Act One — The service faces the internet',
         body='ONE. The service faces the internet.\n  admin header: export of 12000 orders\n  /orders/../admin/export: export',
         narration='First demo: the order service faces the internet directly. [[slnc 400]] A normal request for order seven works. [[slnc 600]] A request with the internal admin header exports all twelve thousand orders. [[slnc 500]] So does a path that goes up a level, to the admin export. [[slnc 600]] And this machine holds the database password.'),
    dict(key='04-act-2', kind='console', title='Act Two — An NGINX gatekeeper',
         body='TWO. An NGINX gatekeeper.\n  GET /orders/7: 200\n  admin header: removed, order 7',
         narration='Second demo: an NGINX gatekeeper in front. [[slnc 400]] Only NGINX faces the internet now. [[slnc 600]] A request for order seven works as before. [[slnc 500]] The same request with the admin header just returns order seven. [[slnc 300]] NGINX removed the header on the way through.'),
    dict(key='05-act-3', kind='console', title='Act Three — An allow-list of locations',
         body='THREE. An allow-list of locations.\n  dot-dot path: 404\n  DELETE: 403\n  POST /orders: 201',
         narration='Third demo: only allowed requests pass. [[slnc 400]] The path trick is tidied by NGINX first. [[slnc 300]] It becomes the admin export. [[slnc 300]] No allowed location matches. [[slnc 300]] Not found. [[slnc 600]] Deleting an order is refused. [[slnc 300]] Forbidden. [[slnc 500]] A normal new order passes, and is created.'),
    dict(key='06-act-4', kind='console', title='Act Four — Size and shape',
         body='FOUR. Size and shape.\n  5 MB: 413\n  /orders/7 OR 1=1: 404',
         narration='Fourth demo: size and shape limits. [[slnc 400]] A five megabyte order is refused. [[slnc 300]] Too large. [[slnc 600]] A request for order seven, followed by a trick aimed at the database. [[slnc 300]] Not found. [[slnc 300]] The number must be digits only.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  gate holds credentials: false\n  an extra hop, a config to keep',
         narration='Fifth demo: the bill. [[slnc 400]] A look inside the NGINX container finds no password at all. [[slnc 300]] A gate that is broken into gives nothing away. [[slnc 600]] But every request pays for one extra hop. [[slnc 300]] A new endpoint stays blocked, until the configuration allows it. [[slnc 500]] And the service behind must still check its own inputs.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in NGINX',
         body=['Allowed locations only.', 'limit_except for methods.', 'client_max_body_size.', 'proxy_set_header to strip.', 'No secrets on the gate.'],
         narration="Let's name the pattern, in NGINX's words. [[slnc 400]] Only a few allowed locations. [[slnc 300]] A limit on methods. [[slnc 300]] A limit on body size. [[slnc 500]] Internal headers stripped on the way through. [[slnc 300]] And no secrets on the gate."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Gatekeeper: NGINX and its config', 'OrderService: trusted, holds the secret'],
         narration='Here is who does what. [[slnc 400]] The gatekeeper is NGINX, and its whole policy is a short configuration file. [[slnc 500]] The order service is trusted, holds the password, and can only be reached through the gate.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Reverse proxies in a DMZ', 'ModSecurity on NGINX', 'Cloud load balancer rules'],
         narration='You have probably met this already. [[slnc 400]] Reverse proxies placed in their own network zone, in front of internal services. [[slnc 500]] Web application firewall rules on NGINX. [[slnc 500]] And path rules on cloud load balancers.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Services with secrets or', 'sensitive data.', '', 'An allow-list config.', 'No secrets on the gate.', 'Still validate inside.'],
         narration='So, when should you use it? [[slnc 400]] In front of any service holding passwords or sensitive data. [[slnc 500]] Keep the configuration an allow-list. [[slnc 300]] Keep secrets off the gate. [[slnc 300]] And still validate inside the services.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a', 'rate limit with limit_req.'],
         narration="That's the Secure Gateway, with NGINX. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let only a gate with nothing to steal face the internet, and write its rules as an allow-list. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts NGINX for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a rate limit for each client, with NGINX's limit request setting. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Secure Gateway with NGINX Pattern  ·  Java 21', 'poster': {'headline': [('SECURE GATEWAY', 'text'), ('WITH NGINX', 'text')], 'before': {'code': 'order service on the internet', 'note': '12000 orders exported', 'tag': 'BEFORE'}, 'after': {'code': 'location ~ ^/orders/[0-9]+$', 'note': '404, 403, 413 at the gate', 'tag': 'AFTER'}, 'taglines': [('The gatekeeper is a config file', 'gold')]}, 'highlight': {}}
