"""Scene definitions for the Page Object teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Page Object',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Page Object pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Browser tests drive a web page the way a person would. [[slnc 300]] A page object is a class for one page. [[slnc 300]] It knows how to find the page's boxes and buttons, and how long the page takes to update. [[slnc 300]] So the tests only say what a shopper does. [[slnc 600]] Think of a hotel guest asking the concierge for a taxi. [[slnc 300]] The guest does not need the taxi firm's number. [[slnc 300]] The concierge knows it. [[slnc 300]] And if the number changes, only the concierge needs to know. [[slnc 700]] In this video, the domain is an online shop's checkout page, and the automated tests that check it. [[slnc 500]] By the end, you will hear why tests that find buttons themselves are fragile. [[slnc 300]] How one class fixes a renamed button for every test. [[slnc 300]] How it hides waiting. [[slnc 300]] And what it costs to keep."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Browser tests for checkout.', '', 'Each test types the coupon,', 'clicks #apply-btn,', 'and reads #total itself.'],
         narration='Here is the scenario. [[slnc 400]] The shop has automated browser tests for its checkout page. [[slnc 500]] Each test typed the coupon code, clicked the apply button, and read the total, all by itself. [[slnc 500]] Each test knew the names the page uses for those elements.'),
    dict(key='03-act-1', kind='console', title='Act One — Tests click selectors',
         body='ONE. Tests click selectors.\n  click #apply-btn, read #total\n  total: 50.00 (too soon)',
         narration='First demo: tests that click selectors themselves. [[slnc 400]] A selector is the name a test uses to find a box or a button on the page. [[slnc 600]] The test types a coupon code. [[slnc 300]] It clicks the apply button. [[slnc 300]] Then it reads the total, straight away. [[slnc 500]] It sees fifty. [[slnc 300]] The old price. [[slnc 500]] The coupon was accepted. [[slnc 300]] But the page updates a moment later, and the test looked too soon.'),
    dict(key='04-act-2', kind='console', title='Act Two — A button is renamed',
         body='TWO. A button is renamed.\n  #apply-btn is now #apply-coupon\n  0 of 5 tests pass',
         narration='Second demo: the designers rename the apply button. [[slnc 400]] It was called apply button. [[slnc 300]] Now it is called apply coupon. [[slnc 600]] Five coupon tests each used the old name. [[slnc 300]] None of them can find the button. [[slnc 500]] Zero of five pass. [[slnc 300]] And every one must be found and edited.'),
    dict(key='05-act-3', kind='console', title='Act Three — A Page Object',
         body='THREE. A Page Object.\n  one selector changed: 5 of 5 pass\n  applyCoupon(SAVE10).total(): 45.00',
         narration='Third demo: a page object. [[slnc 400]] One class, checkout page, is the only place that knows the page. [[slnc 300]] Its selectors, and its timing. [[slnc 600]] Its apply coupon method types the code, clicks the button, and waits until the page has updated. [[slnc 600]] After the rename, one line in that class changed. [[slnc 300]] And all five tests pass. [[slnc 500]] Each test simply says, apply coupon save ten. [[slnc 300]] And reads a total of forty-five.'),
    dict(key='06-act-4', kind='console', title='Act Four — Return the next page',
         body='FOUR. Return the next page.\n  placeOrder() -> ConfirmationPage\n  ORD-1042',
         narration='Fourth demo: an action that moves to a new page returns that page. [[slnc 400]] Place order returns the confirmation page. [[slnc 600]] The confirmation page shows the order number, O R D ten forty-two. [[slnc 300]] And the message, thank you for your order. [[slnc 600]] The test cannot ask the checkout page for an order number by mistake. [[slnc 300]] The code follows the real journey.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  one class per page, kept in step\n  page objects report, tests decide',
         narration='Fifth demo: the bill. [[slnc 400]] Every page now needs its own class. [[slnc 300]] And each must be kept in step with the real page. [[slnc 600]] And there is a rule to keep. [[slnc 300]] Page objects report what the page shows. [[slnc 300]] The tests decide whether it is right. [[slnc 500]] A page object that checks its own results hides what each test is testing.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['One class per page.', '', 'It knows the selectors', 'and the timing.', '', 'Tests speak in shop terms.'],
         narration="Let's name the pattern. [[slnc 400]] One class for each page. [[slnc 500]] It is the only place that knows the page's selectors, and how long the page takes to update. [[slnc 500]] Tests call its methods, in the shop's own words."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['CheckoutPage: apply coupon, total, place order', 'ConfirmationPage: the order number', 'FakeBrowser: stands in for WebDriver', 'Tests: decide what is right'],
         narration='Here is who does what. [[slnc 400]] Checkout page can apply a coupon, read the total, and place the order. [[slnc 500]] Confirmation page shows the order number. [[slnc 500]] The fake browser stands in for a real browser driver. [[slnc 300]] And the tests decide whether what they see is right.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Selenium page objects', 'Playwright and Cypress page classes', 'The Screenplay pattern'],
         narration="You have probably met this pattern already. [[slnc 400]] Selenium's own guides recommend page objects. [[slnc 500]] Playwright and Cypress projects are often organised into page classes. [[slnc 500]] And the Screenplay pattern is a later refinement of the same idea."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Several tests share a page.', '', 'Name methods after actions.', 'Hide the waiting.', 'Return the next page.', 'Keep checks in tests.'],
         narration='So, when should you use it? [[slnc 400]] Once several browser tests share a page. [[slnc 500]] Name methods after what a shopper does. [[slnc 300]] Hide the waiting inside them. [[slnc 300]] Return the next page when an action moves on. [[slnc 300]] And keep the checks in the tests.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Split out a', 'coupon panel component.'],
         narration="That's the Page Object pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Tests say what the shopper does, and one class knows how. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Move the coupon box into its own small component class. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Page Object Pattern  ·  Java 21', 'poster': {'headline': [('PAGE', 'text'), ('OBJECT', 'text')], 'before': {'code': 'click("#apply-btn")', 'note': 'rename: 0 of 5 tests pass', 'tag': 'BEFORE'}, 'after': {'code': 'checkout.applyCoupon("SAVE10")', 'note': 'one change, 5 of 5 pass', 'tag': 'AFTER'}, 'taglines': [('Tests speak shop, not HTML', 'gold')]}, 'highlight': {}}
