"""Scene definitions for the Event-Carried State Transfer with Kafka teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Event-Carried State Transfer with Kafka',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Event-Carried State Transfer, with a real Kafka broker, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] When data changes, the new data travels in the event itself. [[slnc 300]] So every service that cares can keep its own copy, and never call the owner back. [[slnc 500]] Kafka is an open-source event platform that keeps events on topics, so a copy can be built from them at any time. [[slnc 600]] Think of a town noticeboard of address changes. [[slnc 300]] A new postman reads the board once, and knows every current address. [[slnc 700]] In this video, the domain is an online shop, whose shipping service prints labels, and whose customer service owns the addresses. [[slnc 500]] By the end, you will hear how a Kafka topic becomes shipping's copy. [[slnc 300]] How keys keep events in order. [[slnc 300]] And how a deletion travels too."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Shipping prints labels.', '', 'The customer service owns addresses.', '', 'Shipping called it for every label.'],
         narration='Here is the scenario. [[slnc 400]] The shipping service prints delivery labels. [[slnc 500]] The customer service owns the addresses. [[slnc 500]] Shipping used to call it for every label. [[slnc 300]] When it was down, no labels were printed.'),
    dict(key='03-act-1', kind='console', title='Act One — Thin events and call-backs',
         body='ONE. Thin events and call-backs.\n  100 labels, 100 calls\n  owner down: 0 of 100',
         narration='First demo: thin events on Kafka, and a call back for every label. [[slnc 400]] Each event says only, this customer changed. [[slnc 600]] So shipping still asks the customer service for every address. [[slnc 300]] A hundred labels. [[slnc 300]] A hundred calls. [[slnc 600]] The customer service goes down. [[slnc 300]] Not one label can be printed.'),
    dict(key='04-act-2', kind='console', title='Act Two — The address in the event',
         body='TWO. The address in the event.\n  copy holds 10 addresses\n  owner down: 100 of 100, 0 calls',
         narration='Second demo: the event carries the address. [[slnc 400]] Each event is keyed by the customer, on a topic that keeps the latest per customer. [[slnc 600]] Shipping reads the topic into its own copy. [[slnc 300]] Ten addresses. [[slnc 500]] The customer service is still down. [[slnc 300]] All hundred labels are printed. [[slnc 300]] No calls at all.'),
    dict(key='05-act-3', kind='console', title='Act Three — A new copy from the topic',
         body='THREE. A new copy from the topic.\n  fresh copy: 11 events, 10 customers\n  C1 -> York; old copy -> Leeds',
         narration='Third demo: a new copy, from the topic. [[slnc 400]] A customer moves, from Leeds to York. [[slnc 600]] A brand-new shipping instance starts with nothing. [[slnc 300]] It reads the topic from the beginning. [[slnc 300]] Eleven events, for ten customers. [[slnc 500]] The latest event wins. [[slnc 300]] Its label goes to York. [[slnc 500]] The old copy has not read the new event yet. [[slnc 300]] It still says Leeds.'),
    dict(key='06-act-4', kind='console', title='Act Four — Order within a partition',
         body='FOUR. Order within a partition.\n  two partitions: Hull (old)\n  keyed, one partition: Bristol',
         narration='Fourth demo: Kafka keeps order only within a partition. [[slnc 400]] A customer moves to Hull, then to Bristol. [[slnc 600]] Sent to two different partitions, and read in the wrong order, the copy ends on Hull. [[slnc 300]] The older address. [[slnc 600]] Keyed by the customer, both events go to the same partition, in order. [[slnc 300]] The copy ends on Bristol. [[slnc 300]] No version numbers needed.'),
    dict(key='07-act-5', kind='console', title='Act Five — Deleting is an event',
         body='FIVE. Deleting is an event.\n  tombstone for C3\n  copy holds 9; C3 has no label',
         narration='Fifth demo: the bill. [[slnc 400]] Customer three closes the account. [[slnc 600]] The customer service sends a special event, with no address at all. [[slnc 300]] Kafka calls it a tombstone. [[slnc 500]] A copy built from the topic now holds nine addresses. [[slnc 300]] Customer three is gone. [[slnc 600]] Every service with a copy must honour it. [[slnc 300]] Or the address lives on. [[slnc 300]] And every copy is more data to store, and protect.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Kafka',
         body=['Events carry the address.', '', 'Keyed by customer: in order.', 'Compacted: the latest per key.', 'Tombstones: deletions.'],
         narration="Let's name the pattern, in Kafka's words. [[slnc 400]] Events carry the address. [[slnc 500]] Keyed by customer, so each customer's events stay in order. [[slnc 300]] On a compacted topic, which keeps the latest per customer. [[slnc 500]] And tombstones, to say a customer is gone."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Kafka: the broker, in a container', 'CustomerService: the owner', 'ShippingCopy: built from events'],
         narration="Here is who does what. [[slnc 400]] The Kafka class runs a real broker in a container, and sends and reads events. [[slnc 500]] The customer service owns the addresses. [[slnc 500]] And shipping's copy is built only from the events on the topic."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Compacted Kafka topics', 'Kafka Streams KTables', 'Change data capture'],
         narration="You have probably met this already. [[slnc 400]] Compacted Kafka topics, used as a service's own table. [[slnc 500]] Kafka Streams tables, which are exactly this local copy. [[slnc 500]] And change data capture, which publishes every changed database row."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Many services read the data often.', '', 'Key by entity.', 'Honour tombstones.', 'Copy only what you need.'],
         narration='So, when should you use it? [[slnc 400]] When many services read the same data often, and must keep working when its owner is down. [[slnc 500]] Key events by the entity. [[slnc 300]] Honour tombstones. [[slnc 300]] And copy only the fields you need.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Keep a consumer', 'running.'],
         narration="That's Event-Carried State Transfer, with Kafka. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Put the data in the event, key it by who it is about, and let every service keep its own copy. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts Kafka for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Keep a consumer running, and apply new events as they arrive. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Event-Carried State Transfer with Kafka Pattern  ·  Java 21', 'poster': {'headline': [('EVENT-CARRIED STATE', 'text'), ('WITH KAFKA', 'text')], 'before': {'code': '"customer changed" + call back', 'note': 'owner down: 0 labels', 'tag': 'BEFORE'}, 'after': {'code': 'key = customer, compacted', 'note': 'owner down: 100 labels', 'tag': 'AFTER'}, 'taglines': [("The topic is the copy's history", 'gold')]}, 'highlight': {}}
