"""Scene definitions for the Page Object with Selenium teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Page Object with Selenium',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Page Object pattern, with Selenium, in a real browser. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A page object is a class for one page of a web application. [[slnc 300]] It knows how to find the page's boxes and buttons, and how long the page takes to answer. [[slnc 300]] So tests only say what a shopper does. [[slnc 500]] Selenium is the open-source tool that drives a real web browser from code. [[slnc 600]] Think of a hotel guest asking the concierge for a taxi. [[slnc 300]] The concierge knows the number, and when the line is busy. [[slnc 700]] In this video, the domain is an online shop's checkout page, tested in a real Chromium browser. [[slnc 500]] By the end, you will hear why tests that find buttons themselves are fragile. [[slnc 300]] How one class fixes a renamed button for every test. [[slnc 300]] And how it waits for the page."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Browser tests for checkout.', '', 'Each test found the elements', 'itself and read the total', 'straight away.', '', 'Then a button was renamed.'],
         narration='Here is the scenario. [[slnc 400]] The shop has browser tests for its checkout page. [[slnc 500]] Each test found the coupon box and the apply button itself. [[slnc 300]] And read the total straight away. [[slnc 500]] Then the designers renamed the button.'),
    dict(key='03-act-1', kind='console', title='Act One — Selectors in the test',
         body='ONE. Selectors in the test.\n  read #total at once: 50.00',
         narration="First demo: a test that finds the page's elements itself, in a real browser. [[slnc 400]] It types the coupon code. [[slnc 300]] Clicks apply. [[slnc 300]] Reads the total, straight away. [[slnc 600]] Fifty pounds. [[slnc 300]] The old price. [[slnc 500]] The page updates a moment later, from its own script. [[slnc 300]] The test looked too soon."),
    dict(key='04-act-2', kind='console', title='Act Two — A button is renamed',
         body='TWO. A button is renamed.\n  0 of 5 pass\n  NoSuchElementException',
         narration='Second demo: the designers rename the apply button. [[slnc 400]] Five coupon tests each used the old name. [[slnc 600]] The browser cannot find the button. [[slnc 300]] Zero of five pass.'),
    dict(key='05-act-3', kind='console', title='Act Three — A Page Object',
         body='THREE. A Page Object.\n  5 of 5 pass\n  applyCoupon(SAVE10).total(): 45.00',
         narration="Third demo: a page object. [[slnc 400]] One class, checkout page, knows the page's elements, and waits for the page. [[slnc 600]] Its apply coupon method clicks, then waits until the page has answered. [[slnc 500]] After the rename, one line in that class changed. [[slnc 300]] All five tests pass. [[slnc 300]] The total, forty-five."),
    dict(key='06-act-4', kind='console', title='Act Four — Return the next page',
         body='FOUR. Return the next page.\n  placeOrder() -> ConfirmationPage\n  ORD-1042',
         narration='Fourth demo: an action that moves to a new page returns that page. [[slnc 400]] Place order returns the confirmation page. [[slnc 600]] It shows the order number, O R D ten forty-two. [[slnc 300]] And, thank you for your order.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  one class per page\n  real browsers are slow',
         narration='Fifth demo: the bill. [[slnc 400]] Every page needs its own class, kept in step with the real page. [[slnc 600]] Page objects report. [[slnc 300]] Tests decide. [[slnc 500]] And real browser tests are slow. [[slnc 300]] A browser has to start, and every page really loads.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, with Selenium',
         body=['One class per page.', '', 'It holds the selectors,', 'and waits with WebDriverWait.', '', 'Tests speak in shop terms.'],
         narration="Let's name the pattern, with Selenium. [[slnc 400]] One class for each page. [[slnc 500]] It holds the page's selectors, and waits for the page with Selenium's wait. [[slnc 500]] And tests call its methods, in the shop's own words."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['CheckoutPage: apply coupon, total', 'ConfirmationPage: the order number', 'Browser: Chromium in a container', 'ShopSite: the real pages'],
         narration='Here is who does what. [[slnc 400]] Checkout page applies coupons, reads the total, and places the order. [[slnc 500]] Confirmation page shows the order number. [[slnc 500]] The browser class runs Chromium in a container. [[slnc 300]] And the shop site serves the real pages.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Selenium page objects', 'Playwright and Cypress page classes', 'The Screenplay pattern'],
         narration="You have probably met this already. [[slnc 400]] Selenium's own guides recommend page objects. [[slnc 500]] Playwright and Cypress projects use page classes too. [[slnc 500]] And the Screenplay pattern is a later refinement of the same idea."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Several browser tests share a page.', '', 'Selectors and waits inside.', 'Real conditions, not pauses.', 'Checks stay in tests.'],
         narration='So, when should you use it? [[slnc 400]] Whenever several browser tests share a page. [[slnc 500]] Keep selectors and waits inside the page object. [[slnc 300]] Wait for real conditions, never fixed pauses. [[slnc 300]] And keep the checks in the tests.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Try it', 'in Firefox.'],
         narration="That's the Page Object, with Selenium. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Tests say what the shopper does, and one class knows how, and when. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts the browser for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Run the same page objects in Firefox. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Page Object with Selenium Pattern  ·  Java 21', 'poster': {'headline': [('PAGE OBJECT', 'text'), ('WITH SELENIUM', 'text')], 'before': {'code': 'driver.findElement(By.id("apply-btn"))', 'note': 'rename: 0 of 5 pass', 'tag': 'BEFORE'}, 'after': {'code': 'checkout.applyCoupon("SAVE10")', 'note': 'one change, 5 of 5 pass', 'tag': 'AFTER'}, 'taglines': [('A real browser, tests in shop terms', 'gold')]}, 'highlight': {}}
