"""Scene definitions for the Polling Consumer teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Polling Consumer',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Polling Consumer pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A polling consumer decides when to take messages. [[slnc 300]] Each time it is ready, it asks the queue for as many as it can handle. [[slnc 300]] Everything else waits safely in the queue. [[slnc 600]] Think of a post office box, instead of home delivery. [[slnc 300]] Nobody rings your doorbell while you are in the shower. [[slnc 300]] Letters wait in the box until you go and collect them. [[slnc 700]] In this video, the domain is an online shop's warehouse. [[slnc 300]] Its label printer can only print so fast, and orders arrive in bursts. [[slnc 500]] By the end, you will hear what happens when orders are pushed at the printer. [[slnc 300]] How polling fixes it. [[slnc 300]] How to pause safely. [[slnc 300]] And how often to ask."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The label printer: 5 labels', 'per tenth of a second.', 'It can hold 10 jobs.', '', 'Orders arrive in bursts.'],
         narration='Here is the scenario. [[slnc 400]] The warehouse label printer prints five labels every tenth of a second. [[slnc 300]] It can hold ten jobs waiting. [[slnc 600]] Orders arrive in bursts. [[slnc 300]] And each order was pushed straight at the printer, the moment it arrived.'),
    dict(key='03-act-1', kind='console', title='Act One — Pushed at the printer',
         body='ONE. Pushed at the printer.\n  burst of 50; buffer holds 10\n  printed: 10, refused: 40',
         narration="First demo: orders pushed at the printer as they arrive. [[slnc 400]] The printer's buffer holds ten jobs. [[slnc 500]] A burst of fifty orders arrives at once. [[slnc 300]] They are all pushed at the printer. [[slnc 600]] Ten are accepted. [[slnc 300]] Forty are refused: printer busy."),
    dict(key='04-act-2', kind='console', title='Act Two — A polling consumer',
         body='TWO. A polling consumer.\n  asks for up to 5 per tick\n  printed 50 of 50 in 10 ticks; refused 0',
         narration='Second demo: a polling consumer. [[slnc 400]] The orders go into a queue. [[slnc 300]] The printer asks the queue for work, when it is ready. [[slnc 500]] Every tenth of a second, it asks for up to five. [[slnc 300]] As many as it can print. [[slnc 600]] All fifty are printed, in one second. [[slnc 300]] None refused. [[slnc 300]] The queue held the rest until the printer asked.'),
    dict(key='05-act-3', kind='console', title='Act Three — Pausing',
         body='THREE. Pausing.\n  paused: printed 5, waiting 15\n  resumed: printed 20 of 20',
         narration='Third demo: pausing is simply not polling. [[slnc 400]] The printer runs out of paper. [[slnc 300]] It stops asking the queue for three seconds. [[slnc 600]] Five labels were printed. [[slnc 300]] Fifteen orders wait, safely, in the queue. [[slnc 500]] Paper is loaded. [[slnc 300]] Polling resumes. [[slnc 300]] All twenty are printed. [[slnc 300]] None was lost.'),
    dict(key='06-act-4', kind='console', title='Act Four — How often to poll',
         body='FOUR. How often to poll.\n  every 0.1 s: 600 polls, 600 empty\n  long polling (20 s): 3 requests',
         narration='Fourth demo: how often should you ask, when nothing is happening? [[slnc 400]] A quiet minute. [[slnc 300]] No orders at all. [[slnc 500]] Asking every tenth of a second, the printer makes six hundred requests. [[slnc 300]] Every one finds nothing. [[slnc 600]] With long polling, each request waits up to twenty seconds for something to arrive. [[slnc 300]] The same quiet minute takes three requests.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  just missed a poll: wait a whole interval\n  often = waste; rarely = waiting',
         narration='Fifth demo: the bill. [[slnc 400]] An order that arrives just after a poll waits until the next one. [[slnc 300]] Up to a whole interval. [[slnc 600]] Poll often, and you waste requests. [[slnc 300]] Poll rarely, and orders wait. [[slnc 500]] Long polling is the usual middle way.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Messages wait in a queue.', '', 'When ready, the consumer asks', 'for as many as it can handle.', '', 'Pausing is simply not asking.'],
         narration="Let's name the pattern. [[slnc 400]] Messages wait in a queue. [[slnc 500]] When the consumer is ready, it asks for as many as it can handle. [[slnc 300]] No more. [[slnc 500]] And to pause, the consumer simply stops asking. [[slnc 300]] Nothing is lost."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Queue: holds the orders', 'PollingConsumer: asks, each tick', 'LabelPrinter: prints', 'push(): the old way'],
         narration='Here is who does what. [[slnc 400]] The queue holds the orders. [[slnc 500]] The polling consumer asks the queue for up to five, each tick, and can be paused. [[slnc 500]] The label printer prints. [[slnc 300]] And pushing at the printer is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Kafka consumer poll()', 'Amazon SQS long polling', 'Spring Integration pollers', 'Checking email with IMAP'],
         narration="You have probably met this pattern already. [[slnc 400]] Kafka consumers call poll, in a loop. [[slnc 500]] Amazon's simple queue service offers long polling. [[slnc 300]] Spring Integration has pollers. [[slnc 500]] And an email program that checks for new mail every few minutes is a polling consumer."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['The consumer must set its pace,', 'handle bursts, or pause safely.', '', 'Take only what you can handle.', 'Use long polling.'],
         narration='So, when should you use it? [[slnc 400]] When a consumer must set its own pace, handle bursts, or pause safely. [[slnc 500]] Take only what you can handle. [[slnc 300]] Use long polling to avoid empty requests. [[slnc 500]] And accept that a message may wait a little, for the next poll.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Poll faster when busy,', 'slower when quiet.'],
         narration="That's the Polling Consumer pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Take messages when you are ready, and let the queue hold the rest. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Poll faster when the last poll was full, and slower when it was empty. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Polling Consumer Pattern  ·  Java 21', 'poster': {'headline': [('POLLING', 'text'), ('CONSUMER', 'text')], 'before': {'code': 'printer.push(order)', 'note': '40 of 50 refused', 'tag': 'BEFORE'}, 'after': {'code': 'queue.poll(max 5)', 'note': '50 of 50 printed', 'tag': 'AFTER'}, 'taglines': [('Take messages when you are ready', 'gold')]}, 'highlight': {}}
