CREATE TABLE stock (sku VARCHAR(20) PRIMARY KEY, price_pence BIGINT NOT NULL, on_hand INT NOT NULL CHECK (on_hand >= 0));
CREATE TABLE orders (id VARCHAR(20) PRIMARY KEY, customer VARCHAR(40) NOT NULL, sku VARCHAR(20) NOT NULL, quantity INT NOT NULL, total_pence BIGINT NOT NULL);
INSERT INTO stock VALUES ('ESP-001', 30000, 5);
INSERT INTO stock VALUES ('BNS-220', 1250, 10);
