"""Scene definitions for the Wire Tap teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Wire Tap',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Wire Tap pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A wire tap is attached to a channel of messages. [[slnc 300]] It sends a copy of every message to a second listener, such as an audit log. [[slnc 300]] The real message carries on to its destination, untouched. [[slnc 600]] Think of the message: calls may be recorded for training purposes. [[slnc 300]] The customer and the agent talk as normal. [[slnc 300]] A recorder quietly keeps a copy. [[slnc 300]] And when a card number is read out, the recording pauses. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Checkout sends payment messages, charges and refunds, to the payment service. [[slnc 500]] By the end, you will hear why typing logging into services goes wrong. [[slnc 300]] How a wire tap fixes it. [[slnc 300]] How taps come and go. [[slnc 300]] And what a tap must never do.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Checkout -> payment service:', 'charges and refunds.', '', 'A refund is disputed.', 'Someone needs to see the messages.'],
         narration='Here is the scenario. [[slnc 400]] Checkout sends payment messages to the payment service. [[slnc 300]] Charges, and refunds. [[slnc 600]] A customer disputes a refund. [[slnc 300]] Someone needs to see exactly which messages went through.'),
    dict(key='03-act-1', kind='console', title='Act One — Logging typed in by hand',
         body='ONE. Logging typed in by hand.\n  4 messages sent, 3 in the log\n  ... card 4929123412341234',
         narration='First demo: logging typed into the payment service, by hand. [[slnc 400]] Four payment messages are sent. [[slnc 300]] Three charges, and one refund. [[slnc 600]] Only three appear in the log. [[slnc 300]] Nobody added logging to the refund code. [[slnc 500]] And the lines that are there show the full card number.'),
    dict(key='04-act-2', kind='console', title='Act Two — A wire tap',
         body='TWO. A wire tap.\n  audit: CHARGE ORD-1 £63.44 **** 1234\n  audit: REFUND ORD-1 £30.00 **** 1234\n  4 of 4 copied; nothing changed',
         narration='Second demo: a wire tap, on the channel itself. [[slnc 400]] An audit log is attached to the channel. [[slnc 300]] Every message is copied to it, charges and refunds alike. [[slnc 600]] The copies show only the last four digits of each card. [[slnc 500]] The payment service handles all four messages, exactly as before. [[slnc 300]] Neither service was changed.'),
    dict(key='05-act-3', kind='console', title='Act Three — Attach and detach',
         body='THREE. Attach and detach.\n  tap detached\n  ORD-4 flows as normal',
         narration='Third demo: attach while investigating, detach afterwards. [[slnc 400]] The investigation is over. [[slnc 300]] The tap is detached. [[slnc 500]] Order four flows through, exactly as normal. [[slnc 300]] The audit log still holds its four lines.'),
    dict(key='06-act-4', kind='console', title='Act Four — A second tap',
         body='FOUR. A second tap.\n  net takings: £58.42',
         narration='Fourth demo: a second tap, for a sales dashboard. [[slnc 400]] It adds up the charges, and takes off the refunds. [[slnc 500]] Net takings: fifty-eight pounds forty-two. [[slnc 300]] Again, no service changed.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  slow tap: 4 payments over 0.4 s\n  on its own thread: under 0.05 s\n  mask before copying',
         narration='Fifth demo: the bill. [[slnc 400]] A tap that takes a tenth of a second per copy slows the real payments. [[slnc 300]] Four payments take over four tenths of a second. [[slnc 600]] Run the same tap on its own thread, and the payments take under five hundredths of a second. [[slnc 600]] And a tap sees everything. [[slnc 300]] Mask card numbers, before anything is copied.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Attach a tap to the channel.', '', 'Every message: delivered as normal,', 'and copied to the tap.', '', 'Sender and receiver unchanged.'],
         narration="Let's name the pattern. [[slnc 400]] Attach a tap to the channel itself. [[slnc 500]] Every message is delivered as normal. [[slnc 300]] And a copy goes to the tap. [[slnc 500]] The sender and the receiver are not changed at all. [[slnc 300]] Taps can be attached, and detached, while the shop runs."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Channel: delivers, and feeds taps', 'AuditLog: masked copies', 'SalesMeter: net takings', 'Async: keeps slow taps off the path', 'PaymentService: the real destination'],
         narration='Here is who does what. [[slnc 400]] The channel delivers each message, and hands a copy to every attached tap. [[slnc 500]] The audit log keeps copies, with card numbers masked. [[slnc 300]] The sales meter keeps a running total. [[slnc 500]] Async runs a slow tap on its own thread. [[slnc 300]] And the payment service is the real destination.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel wireTap', 'Spring Integration wire-tap', 'Kafka audit consumers', 'Port mirroring, call recording'],
         narration='You have probably met this pattern already. [[slnc 400]] Apache Camel and Spring Integration both have a wire tap. [[slnc 500]] In Kafka, a separate consumer group can read a topic for auditing. [[slnc 500]] Network switches mirror traffic to monitoring tools. [[slnc 300]] And call centres record calls.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Auditing, debugging, dashboards.', '', 'Mask sensitive data first.', 'Slow taps on their own thread.', 'Detach what you no longer need.'],
         narration='So, when should you use it? [[slnc 400]] For auditing, debugging, and dashboards. [[slnc 500]] Mask sensitive data before anything is copied. [[slnc 300]] Run slow taps on their own thread. [[slnc 300]] And detach the taps you no longer need.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Write the audit', 'to a file, on its own thread.'],
         narration="That's the Wire Tap pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Watch the traffic from the channel, never from inside the services. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make the audit tap write to a file, on its own thread. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Wire Tap Pattern  ·  Java 21', 'poster': {'headline': [('WIRE TAP', 'text')], 'before': {'code': 'log.info(...) in services', 'note': 'missed refunds, full cards', 'tag': 'BEFORE'}, 'after': {'code': 'channel.attach(audit)', 'note': 'every message, masked', 'tag': 'AFTER'}, 'taglines': [('See the traffic without touching it', 'gold')]}, 'highlight': {}}
