"""Scene definitions for the Resequencer with Apache Camel teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Resequencer with Apache Camel',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Resequencer pattern, built with Apache Camel, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A resequencer puts messages that arrived out of order back in order. [[slnc 300]] Using a number each message carries. [[slnc 500]] Apache Camel is an open-source library for moving messages, and it has a resequencer built in. [[slnc 600]] Think of a sorting office receiving the numbered pages of a letter, out of order. [[slnc 300]] It can pass pages on as soon as the next one arrives. [[slnc 300]] Or wait for the whole bundle, and sort it. [[slnc 700]] In this video, the domain is an online shop's order-tracking page, and the status updates it shows. [[slnc 500]] By the end, you will hear Camel's two modes, stream and batch. [[slnc 300]] What each makes the customer wait for. [[slnc 300]] And what happens when an update is lost."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Placed, paid, packed,', 'shipped, delivered.', '', 'They arrive out of order.', '', 'The page ended on SHIPPED.'],
         narration='Here is the scenario. [[slnc 400]] The tracking page shows five updates. [[slnc 300]] Placed, paid, packed, shipped, delivered. [[slnc 500]] They travel different paths, and arrive out of order. [[slnc 500]] The page ended on shipped, although the parcel was delivered.'),
    dict(key='03-act-1', kind='console', title='Act One — Applied as they arrive',
         body='ONE. Applied as they arrive.\n  arrival: #1, #3, #2, #5, #4\n  final status: SHIPPED',
         narration='First demo: updates applied as they arrive. [[slnc 400]] They arrive in the order one, three, two, five, four. [[slnc 600]] The customer sees placed, packed, paid, delivered, shipped. [[slnc 500]] The page ends on shipped. [[slnc 300]] But the parcel was delivered.'),
    dict(key='04-act-2', kind='console', title='Act Two — Stream mode',
         body='TWO. Stream mode.\n  page: PLACED ... DELIVERED\n  first update after about 0.3 s',
         narration="Second demo: Camel's resequencer, in stream mode. [[slnc 400]] Each update is released as soon as all the earlier ones have been seen. [[slnc 600]] The page shows placed, paid, packed, shipped, delivered. [[slnc 300]] In order. [[slnc 600]] One surprise. [[slnc 300]] The very first update waited about a third of a second. [[slnc 300]] Camel cannot know that number one is the first. [[slnc 300]] So it waits one timeout."),
    dict(key='05-act-3', kind='console', title='Act Three — Batch mode',
         body='THREE. Batch mode.\n  after 4: page shows []\n  after 5: all five, in order',
         narration='Third demo: batch mode. [[slnc 400]] Camel collects a group of five, sorts it, and releases it together. [[slnc 600]] After four updates, the page shows nothing at all. [[slnc 500]] The fifth arrives. [[slnc 300]] All five appear at once, in order. [[slnc 500]] Never out of order. [[slnc 300]] But the customer waits for the whole group.'),
    dict(key='06-act-4', kind='console', title='Act Four — Two orders at once',
         body='FOUR. Two orders at once.\n  ORD-2 PLACED, PAID\n  ORD-3 PLACED, PAID, PACKED',
         narration="Fourth demo: two orders at once. [[slnc 400]] Updates for two orders arrive mixed together. [[slnc 600]] Camel's stream mode keeps one sequence for everything. [[slnc 300]] It cannot keep two orders apart. [[slnc 500]] Batch mode sorts by order, then by number. [[slnc 300]] Order two's updates come out in order. [[slnc 300]] Then order three's."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  #4, #5 wait: page says PAID\n  after 0.5 s: DELIVERED',
         narration='Fifth demo: the bill. [[slnc 400]] Update three is lost. [[slnc 600]] Updates four and five arrive. [[slnc 300]] They wait. [[slnc 300]] The page stays on paid. [[slnc 500]] After about half a second, Camel gives up on number three. [[slnc 300]] The page says delivered. [[slnc 600]] A short timeout gives up on late messages quickly. [[slnc 300]] A long one leaves the customer on an old status for longer.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Camel',
         body=['resequence(sequence number).', '', 'Stream: release as soon as', 'the gap is filled.', '', 'Batch: collect, sort, release.'],
         narration="Let's name the pattern, in Camel's words. [[slnc 400]] The resequence step, given each message's number. [[slnc 500]] Stream mode releases each message as soon as the ones before it have gone. [[slnc 500]] Batch mode collects a group, sorts it, and releases it together."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShopRoutes: the three routes', 'resequence(): holds and releases', 'OrderPage: what the customer sees'],
         narration='Here is who does what. [[slnc 400]] Shop routes holds three routes. [[slnc 300]] Straight through, stream, and batch. [[slnc 500]] The resequence step holds messages, and releases them in order. [[slnc 500]] And the order page is what the customer sees.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel resequence()', 'Spring Integration resequencer', 'TCP packet ordering', 'Kafka partitions'],
         narration="You have probably met this already. [[slnc 400]] Camel's resequence step, and Spring Integration's resequencer. [[slnc 500]] The network does it too. [[slnc 300]] TCP puts packets back in order before your program sees them. [[slnc 500]] And Kafka keeps order within a partition."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Updates travel different paths', 'and order matters.', '', 'Stream: show soon.', 'Batch: never out of order.', 'Choose the timeout.'],
         narration='So, when should you use it? [[slnc 400]] When updates travel different paths, and their order matters. [[slnc 500]] Use stream mode to show updates soon. [[slnc 300]] Batch mode when nothing may ever appear out of order. [[slnc 300]] And choose the timeout on purpose.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Try a', '2-second timeout.'],
         narration="That's the Resequencer, with Apache Camel. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Put messages back in order, and decide how long to wait for a missing one. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Set the timeout to two seconds, and time how long the page stays on paid. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Resequencer with Apache Camel Pattern  ·  Java 21', 'poster': {'headline': [('RESEQUENCER', 'text'), ('WITH CAMEL', 'text')], 'before': {'code': 'as they arrive', 'note': 'final status: SHIPPED', 'tag': 'BEFORE'}, 'after': {'code': 'resequence(header("seq"))', 'note': 'in order: DELIVERED', 'tag': 'AFTER'}, 'taglines': [('Back in order: stream or batch', 'gold')]}, 'highlight': {}}
