"""Scene definitions for the Sharding with PostgreSQL teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Sharding with PostgreSQL',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Sharding pattern, with real PostgreSQL databases, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Sharding splits data across several databases, by a key such as the customer number. [[slnc 300]] So no single database has to take all the load. [[slnc 500]] PostgreSQL is an open-source relational database. [[slnc 300]] Here, three of them each hold a share of the shop's orders. [[slnc 600]] Think of a library that splits its members across three branches, by membership number. [[slnc 300]] Asking about one member means phoning one branch. [[slnc 300]] Asking about everyone means phoning all three. [[slnc 700]] In this video, the domain is an online shop's orders on Black Friday. [[slnc 500]] By the end, you will hear how a router splits the orders. [[slnc 300]] Which questions get easier, and which get harder. [[slnc 300]] And what adding a shard costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Black Friday: 2,500 orders', 'a minute.', '', 'One database took every', 'read and every write.'],
         narration='Here is the scenario. [[slnc 400]] On Black Friday, the shop takes two and a half thousand orders a minute. [[slnc 500]] One database took every read, and every write. [[slnc 300]] It became the limit.'),
    dict(key='03-act-1', kind='console', title='Act One — One database',
         body='ONE. One database.\n  one database: 2500 orders',
         narration='First demo: one database for every order. [[slnc 400]] Two and a half thousand orders go into one PostgreSQL database. [[slnc 600]] Every read, and every write, of Black Friday lands on that one server.'),
    dict(key='04-act-2', kind='console', title='Act Two — Three shards',
         body='TWO. Three shards.\n  shards: 833, 834, 833\n  customer 17 -> shard-2',
         narration='Second demo: three shards. [[slnc 400]] Three separate PostgreSQL databases. [[slnc 300]] The router picks one for each customer, from the customer number. [[slnc 600]] They hold eight hundred and thirty-three, eight hundred and thirty-four, and eight hundred and thirty-three orders. [[slnc 500]] Customer seventeen lives on shard two. [[slnc 300]] Customer forty-two on shard zero.'),
    dict(key='05-act-3', kind='console', title='Act Three — One customer, one shard',
         body='THREE. One customer, one shard.\n  customer 17: [ORD-17]; 1 shard asked',
         narration="Third demo: a question about one customer asks one shard. [[slnc 400]] Customer seventeen's orders come from shard two alone. [[slnc 500]] The other two databases are not asked at all."),
    dict(key='06-act-4', kind='console', title='Act Four — Everyone, every shard',
         body='FOUR. Everyone, every shard.\n  over £500: 1250, from 3 databases\n  WELCOME10 accepted twice',
         narration='Fourth demo: a question about everyone asks every shard. [[slnc 400]] How many orders are over five hundred pounds? [[slnc 300]] All three databases are asked, and the application adds up the answers. [[slnc 300]] One thousand, two hundred and fifty. [[slnc 600]] Worse. [[slnc 300]] A welcome coupon may only be used once. [[slnc 300]] Each database enforces that. [[slnc 500]] But customer seventeen and customer forty-two live on different shards. [[slnc 300]] Both use it. [[slnc 300]] Each database only knows its own rows.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill: resharding',
         body='FIVE. The bill: resharding.\n  modulo 4: 1874 must move\n  jump hash: 630 must move',
         narration='Fifth demo: the bill. [[slnc 400]] A fourth shard is added. [[slnc 600]] With the simple rule, customer number modulo four, one thousand eight hundred and seventy-four customers must move to another database. [[slnc 500]] With consistent hashing, only six hundred and thirty. [[slnc 600]] And no transaction covers two shards. [[slnc 300]] One very busy customer still overloads their own shard.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Several databases.', 'A key decides where each', 'row lives.', '', 'A router sends each query', 'to the right one.'],
         narration="Let's name the pattern. [[slnc 400]] Several databases, each holding a share. [[slnc 500]] A key, here the customer number, decides where each row lives. [[slnc 500]] And a router sends each query to the right database."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShardRouter: picks the database', 'Shards: three PostgreSQL containers', 'The application: merges answers'],
         narration='Here is who does what. [[slnc 400]] The shard router picks the database for each customer, and sends each query there. [[slnc 500]] The shards are three PostgreSQL databases, in containers. [[slnc 500]] And the application itself merges answers from several shards.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Citus and Vitess', 'MongoDB and Cassandra', 'Consistent hashing in caches'],
         narration='You have probably met this already. [[slnc 400]] Citus, and Vitess, add sharding to PostgreSQL and MySQL. [[slnc 500]] MongoDB and Cassandra shard by a key, built in. [[slnc 500]] And cache clients use consistent hashing to pick a server.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Writes outgrow one database.', '', 'A key most queries share.', 'Consistent hashing.', 'Cross-shard rules in one place.'],
         narration='So, when should you use it? [[slnc 400]] When writes outgrow the largest single database you can run. [[slnc 500]] Choose a key most queries share. [[slnc 300]] Route with consistent hashing. [[slnc 300]] And keep rules that span customers somewhere every shard can see.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Enforce the', 'coupon across shards.'],
         narration="That's Sharding, with PostgreSQL. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Split the data by a key, and remember that each database only knows its own share. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts the databases for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make the one-use coupon hold across all shards. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Sharding with PostgreSQL Pattern  ·  Java 21', 'poster': {'headline': [('SHARDING', 'text'), ('WITH POSTGRESQL', 'text')], 'before': {'code': 'one PostgreSQL', 'note': 'every order, one server', 'tag': 'BEFORE'}, 'after': {'code': 'customer % 3 -> database', 'note': '833, 834, 833 per shard', 'tag': 'AFTER'}, 'taglines': [('Three real databases, one router', 'gold')]}, 'highlight': {}}
