"""Scene definitions for the Request-Reply with RabbitMQ teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Request-Reply with RabbitMQ',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Request-Reply pattern, with a real RabbitMQ broker, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Request-reply is asking a question with one message, and getting the answer in another. [[slnc 300]] Each request says where to send the answer. [[slnc 300]] And carries a reference, so the answer can be matched to it. [[slnc 500]] RabbitMQ is an open-source message broker, and it has both of these built into every message. [[slnc 600]] Think of letters to a supplier, each with your address and a reference number. [[slnc 300]] The answers come back in any order, but each names your reference. [[slnc 700]] In this video, the domain is an online shop's checkout, asking an inventory service to reserve items. [[slnc 500]] By the end, you will hear how replies get mixed up. [[slnc 300]] How references and return addresses fix it. [[slnc 300]] And what to do about a reply that never comes."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Checkout asks inventory', 'to reserve items.', '', 'Cached items are answered first.', '', 'Web and phone app both ask.'],
         narration='Here is the scenario. [[slnc 400]] Checkout asks the inventory service to reserve items, and waits for the answer. [[slnc 500]] The inventory service answers items in its cache first. [[slnc 300]] So replies can come back in a different order. [[slnc 500]] And the web checkout and the phone app both ask.'),
    dict(key='03-act-1', kind='console', title='Act One — Replies taken in arrival order',
         body='ONE. Replies taken in arrival order.\n  KETTLE x 5 -> RESERVED 2 x MUG-1\n  MUG x 2 -> REFUSED 5 x KETTLE-1',
         narration="First demo: replies taken in the order they come back. [[slnc 400]] Checkout asks for five kettles, then two mugs. [[slnc 600]] The inventory service answers the mugs first, from its cache. [[slnc 500]] Checkout takes the first reply as the kettle's answer. [[slnc 300]] So it believes its kettles were reserved. [[slnc 300]] They were refused."),
    dict(key='04-act-2', kind='console', title='Act Two — Correlation IDs',
         body='TWO. Correlation IDs.\n  WEB-1 KETTLE x 5 -> REFUSED\n  WEB-2 MUG x 2 -> RESERVED',
         narration='Second demo: correlation identifiers. [[slnc 400]] Each request carries a reference. [[slnc 300]] The inventory service copies it onto the reply. [[slnc 600]] The mug reply still comes first. [[slnc 300]] But its reference says which request it answers. [[slnc 500]] The kettles are refused. [[slnc 300]] The mugs are reserved. [[slnc 300]] Each answer matched to its question.'),
    dict(key='05-act-3', kind='console', title='Act Three — Return addresses',
         body='THREE. Return addresses.\n  APP-1 -> RESERVED 1 x TEAPOT-1 (direct reply-to)\n  WEB-3 -> RESERVED 2 x TEAPOT-1 (own queue)',
         narration='Third demo: return addresses. [[slnc 400]] Each request names where its reply should go. [[slnc 600]] The phone app uses a RabbitMQ feature called direct reply-to. [[slnc 300]] It needs no reply queue at all. [[slnc 500]] The web checkout uses its own private queue. [[slnc 500]] One inventory service. [[slnc 300]] Each reply goes to the address in its request.'),
    dict(key='06-act-4', kind='console', title='Act Four — Many in flight',
         body='FOUR. Many in flight.\n  20 sent, 20 matched\n  still waiting: 0',
         narration='Fourth demo: many requests in flight at once. [[slnc 400]] Twenty requests are sent, before a single reply. [[slnc 600]] The service handles all twenty. [[slnc 300]] Every reply is matched by its reference. [[slnc 300]] None is left waiting.'),
    dict(key='07-act-5', kind='console', title='Act Five — A reply that never comes',
         body='FIVE. A reply that never comes.\n  WEB-24: no reply after 0.5 s\n  expired in the queue: service handles 0',
         narration='Fifth demo: the bill. [[slnc 400]] The inventory service is busy. [[slnc 300]] Request twenty-four waits half a second. [[slnc 300]] No reply. [[slnc 600]] The requester must time it out, and clean up. [[slnc 500]] But was the mug reserved later? [[slnc 300]] The request was sent with an expiry of half a second. [[slnc 300]] So RabbitMQ dropped it. [[slnc 500]] When the service comes back, there is nothing to handle. [[slnc 300]] Without the expiry, nobody could tell.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in RabbitMQ',
         body=['replyTo: where to answer.', 'correlationId: which question.', '', 'expiration: drop it if', 'nobody takes it in time.'],
         narration="Let's name the pattern, in RabbitMQ's words. [[slnc 400]] Reply to, says where to send the answer. [[slnc 300]] Correlation identifier, says which question it answers. [[slnc 500]] And expiration tells the broker to drop a request, if nobody takes it in time."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Requester: asks and matches', 'InventoryService: answers', 'Broker: RabbitMQ in a container', 'Poll: waits for real conditions'],
         narration='Here is who does what. [[slnc 400]] The requester sends each question, and matches each answer by its reference. [[slnc 500]] The inventory service answers, copying the reference. [[slnc 500]] The broker class runs RabbitMQ in a container. [[slnc 300]] And poll waits for real conditions.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['RabbitMQ RPC', 'Spring AMQP convertSendAndReceive', 'JMS reply-to and correlation', 'Email threads'],
         narration="You have probably met this already. [[slnc 400]] RabbitMQ's remote procedure call examples. [[slnc 300]] And Spring's send and receive methods. [[slnc 500]] Java messaging has reply-to and correlation fields too. [[slnc 500]] And every email reply carries a reference to the message it answers."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Callers and services decoupled,', 'replies may be slow.', '', 'Always an ID.', 'Time out in the requester.', 'Expire the request too.'],
         narration='So, when should you use it? [[slnc 400]] When callers and services are decoupled, and replies may be slow. [[slnc 500]] Always set a reference. [[slnc 300]] Time out in the requester. [[slnc 300]] And give each request an expiry that matches that time-out.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Remove the', 'expiry and watch.'],
         narration="That's Request-Reply, with RabbitMQ. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Say where to answer, say which question, and say when to give up. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts the broker for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Remove the expiry in the last demo, and watch the mug get reserved late. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Request-Reply with RabbitMQ Pattern  ·  Java 21', 'poster': {'headline': [('REQUEST-REPLY', 'text'), ('WITH RABBITMQ', 'text')], 'before': {'code': 'replies in arrival order', 'note': "kettle gets the mug's reply", 'tag': 'BEFORE'}, 'after': {'code': 'replyTo + correlationId', 'note': 'every reply matched', 'tag': 'AFTER'}, 'taglines': [('Ask, answer, and match', 'gold')]}, 'highlight': {}}
