"""Scene definitions for the Hedged Requests with gRPC teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Hedged Requests with gRPC',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Hedged Requests pattern, with gRPC, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] If a call has not answered after a short wait, send the same call again. [[slnc 300]] Use whichever answer comes first, and cancel the other. [[slnc 500]] gRPC is an open-source framework for calling other services, and it can hedge for you, as a setting. [[slnc 600]] Think of phoning two branches of a shop. [[slnc 300]] Ring one. [[slnc 300]] If nobody answers after a few rings, ring the other, and hang up on the first. [[slnc 700]] In this video, the domain is an online shop's product page, asking a price service for each price. [[slnc 500]] By the end, you will hear how one setting cuts the slow calls. [[slnc 300]] How gRPC cancels the loser. [[slnc 300]] And why an order must never be hedged."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The product page asks for prices.', '', 'Most answers: 20 ms.', '', '1 call in 33: a whole second.'],
         narration='Here is the scenario. [[slnc 400]] The product page asks the price service for each price, over gRPC. [[slnc 500]] Most answers take twenty milliseconds. [[slnc 500]] But about one call in thirty-three lands on a paused worker, and takes a whole second.'),
    dict(key='03-act-1', kind='console', title='Act One — A slow tail',
         body='ONE. A slow tail.\n  3 of 100 took about a second',
         narration='First demo: one call per price, and a slow tail. [[slnc 400]] The product page looks up a hundred prices, over gRPC. [[slnc 600]] Three of them take about a second. [[slnc 300]] The rest, about twenty milliseconds. [[slnc 500]] So the slowest pages wait a whole second.'),
    dict(key='04-act-2', kind='console', title='Act Two — A hedging policy',
         body='TWO. A hedging policy.\n  0 over 0.2 s\n  extra calls: 3',
         narration="Second demo: gRPC's hedging policy. [[slnc 400]] The channel gets one setting. [[slnc 300]] If no answer after fifty milliseconds, send a second attempt. [[slnc 600]] The shop's code does not change at all. [[slnc 500]] Now none of the hundred lookups is slow. [[slnc 300]] And gRPC sent just three extra calls."),
    dict(key='05-act-3', kind='console', title='Act Three — The loser is cancelled',
         body='THREE. The loser is cancelled.\n  cancelled, never replied: 3',
         narration='Third demo: the loser is cancelled. [[slnc 400]] When the second attempt answers first, gRPC cancels the first. [[slnc 600]] The server can see it. [[slnc 300]] The three slow attempts find their call cancelled. [[slnc 300]] They never reply.'),
    dict(key='06-act-4', kind='console', title='Act Four — Hedge at once',
         body='FOUR. Hedge at once.\n  100 lookups, 200 calls',
         narration='Fourth demo: hedge at once, with a delay of zero. [[slnc 400]] Every lookup is sent twice, immediately. [[slnc 600]] A hundred lookups, two hundred calls. [[slnc 300]] Twice the load on the price service.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  one click, 2 orders placed',
         narration='Fifth demo: the bill. [[slnc 400]] The same policy is applied, by mistake, to placing orders. [[slnc 600]] The customer sees one confirmation. [[slnc 300]] The server placed two orders. [[slnc 600]] Hedge only reads. [[slnc 300]] And cap hedging, so an overloaded service is not sent even more.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in gRPC',
         body=['A hedging policy in the', "channel's service config.", '', 'maxAttempts: 2', 'hedgingDelay: 0.05s', '', 'Only for safe methods.'],
         narration="Let's name the pattern, in gRPC's words. [[slnc 400]] A hedging policy, in the channel's service config. [[slnc 500]] Up to two attempts. [[slnc 300]] The second after fifty milliseconds. [[slnc 500]] And applied only to methods that are safe to repeat."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Channels: plain or hedged', 'PriceServer: sometimes slow', 'Shop: the two methods'],
         narration='Here is who does what. [[slnc 400]] Channels builds a plain gRPC channel, or one with the hedging policy. [[slnc 500]] The price server answers, and is sometimes slow. [[slnc 500]] And shop describes the two methods, price and place order.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['gRPC hedging and retry policies', 'Cassandra speculative retry', 'Envoy hedging'],
         narration="You have probably met this already. [[slnc 400]] gRPC's hedging and retry policies. [[slnc 500]] Cassandra's speculative retry. [[slnc 500]] And service meshes such as Envoy, which can hedge too."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Cheap, repeatable reads.', 'A rare slow outlier.', '', 'Scope to safe methods.', 'Delay near the worst case.', 'Throttle.'],
         narration='So, when should you use it? [[slnc 400]] For cheap reads that are safe to repeat, with a rare slow outlier. [[slnc 500]] Scope the policy to those methods. [[slnc 300]] Choose a delay near the normal worst case. [[slnc 300]] And add throttling.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add', 'retryThrottling.'],
         narration="That's Hedged Requests, with gRPC. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let the framework ask twice, but only for questions that are safe to ask twice. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add retry throttling, and make the server slow for every call. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Hedged Requests with gRPC Pattern  ·  Java 21', 'poster': {'headline': [('HEDGED REQUESTS', 'text'), ('WITH GRPC', 'text')], 'before': {'code': 'one attempt per call', 'note': '3 of 100 take a second', 'tag': 'BEFORE'}, 'after': {'code': 'hedgingPolicy: 0.05s', 'note': '0 slow, 3 extra calls', 'tag': 'AFTER'}, 'taglines': [('Hedging as a policy, not code', 'gold')]}, 'highlight': {}}
