"""Scene definitions for the Space-Based Architecture teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Space-Based Architecture',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Space-Based Architecture, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] In a space-based system, every copy of the application keeps its own copy of the data, in memory. [[slnc 300]] The copies are kept in step through a data grid. [[slnc 300]] And the database is updated in the background, so no request ever waits for it. [[slnc 600]] Think of pop-up stalls at a festival, selling the same T-shirts. [[slnc 300]] Each stall keeps its own tally, and serves its own queue. [[slnc 300]] They radio their sales to each other, and head office updates its books overnight. [[slnc 700]] In this video, the domain is an online shop's kettle flash sale. [[slnc 300]] Hundreds of orders arrive at once, and every one must check the stock. [[slnc 500]] By the end, you will hear why more servers did not help. [[slnc 300]] How processing units with the data in memory do. [[slnc 300]] How the copies catch up. [[slnc 300]] And the kettle that was sold twice."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A kettle flash sale.', '', 'Three app servers.', 'Every order checks one database:', '5 ms a query, one at a time.'],
         narration='Here is the scenario. [[slnc 400]] The shop runs a kettle flash sale. [[slnc 500]] Three app servers take the orders. [[slnc 300]] Every order checks and updates the stock in one central database. [[slnc 300]] Five milliseconds a query, and one query at a time.'),
    dict(key='03-act-1', kind='console', title='Act One — One database for everyone',
         body='ONE. One database for everyone.\n  300 orders: over 1.4 s\n  six servers: still over 1.4 s',
         narration='First demo: three app servers, one database. [[slnc 400]] Every kettle order checks and updates the stock in the database. [[slnc 300]] Five milliseconds each, one at a time. [[slnc 600]] Three hundred orders take over one point four seconds. [[slnc 500]] Double the app servers, to six. [[slnc 300]] Still over one point four seconds. [[slnc 300]] The database is the limit, not the servers.'),
    dict(key='04-act-2', kind='console', title='Act Two — Processing units',
         body='TWO. Processing units.\n  300 orders in under 0.3 s\n  no order touched the database',
         narration='Second demo: processing units, each with the data in memory. [[slnc 400]] Each unit is a copy of the app, holding its own copy of the stock. [[slnc 600]] Orders are spread across three units, and answered straight from memory. [[slnc 500]] Three hundred orders in under three tenths of a second. [[slnc 300]] Not one of them touched the database.'),
    dict(key='05-act-3', kind='console', title='Act Three — The data grid',
         body='THREE. The data grid.\n  before: unit-1 900, unit-2 900, unit-3 900\n  after:  unit-1 700, unit-2 700, unit-3 700',
         narration='Third demo: the data grid keeps the copies in step. [[slnc 400]] Right after the sale, each unit has only seen its own hundred sales. [[slnc 300]] Each one thinks there are nine hundred kettles left. [[slnc 600]] The grid copies every sale to the other units. [[slnc 500]] Now all three agree: seven hundred.'),
    dict(key='06-act-4', kind='console', title='Act Four — The database catches up',
         body='FOUR. The database catches up.\n  database stock: 700\n  3 batch writes, not 300',
         narration='Fourth demo: the database catches up, in the background. [[slnc 400]] A data writer collects the changes from the grid. [[slnc 300]] It writes them in batches of a hundred. [[slnc 600]] Three writes, instead of three hundred. [[slnc 300]] The database now says seven hundred. [[slnc 500]] And no customer waited for any of those writes.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  unit-1 sold: true, unit-2 sold: true\n  stock after replication: -1',
         narration="Fifth demo: the bill. [[slnc 400]] One kettle left. [[slnc 300]] Two customers buy it at the same moment, on two different units. [[slnc 600]] Neither unit has heard about the other's sale yet. [[slnc 300]] Both say yes. [[slnc 500]] After replication, the stock is minus one. [[slnc 500]] And a unit that crashes before the grid copies its sales loses them."),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Processing units: the app plus', 'its own data, in memory.', '', 'Data grid: copies every change.', '', 'Data writer: updates the database', 'in the background.'],
         narration="Let's name the pattern. [[slnc 400]] Run the app as processing units. [[slnc 300]] Each unit holds the data it needs, in its own memory, and answers from it. [[slnc 500]] A data grid copies every change to the other units. [[slnc 500]] And a data writer brings the database up to date in the background, in batches. [[slnc 300]] The database is no longer in the way of any request."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ProcessingUnit: sells from memory', 'DataGrid: keeps copies in step', 'DataWriter: batches to the database', 'CentralDatabase: the old way'],
         narration='Here is who does what. [[slnc 400]] A processing unit sells from its own copy of the stock. [[slnc 500]] The data grid copies each sale to the other units. [[slnc 500]] The data writer writes the changes to the database in batches. [[slnc 500]] And the central database, in every request, is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Hazelcast, Apache Ignite, Coherence', 'Ticketing and flash-sale systems', 'JavaSpaces, where the name began'],
         narration='You have probably met this pattern already. [[slnc 400]] In-memory data grids such as Hazelcast, Apache Ignite, and Coherence are built for it. [[slnc 500]] Ticket sales and flash sales use it to survive huge spikes. [[slnc 500]] And the name comes from JavaSpaces, an early shared memory space for Java programs.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Extreme, spiky load.', 'Brief disagreement is acceptable.', '', 'Use a data grid product.', '', 'Ordinary load? One database.'],
         narration='So, when should you use it? [[slnc 400]] For extreme, spiky load, where copies disagreeing for a moment is acceptable. [[slnc 500]] Use a data grid product, rather than writing your own. [[slnc 500]] And for ordinary load, one database, with good indexes and caching, is simpler, and always consistent.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Hold back a safety stock', 'on each unit.'],
         narration="That's Space-Based Architecture. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Keep the data next to the work, and let the database catch up later. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Hold back a small safety stock on each unit, so the last kettle is never sold twice. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Space-Based Architecture Pattern  ·  Java 21', 'poster': {'headline': [('SPACE-BASED', 'text'), ('ARCHITECTURE', 'text')], 'before': {'code': 'db.takeOne() x 300', 'note': 'over 1.4 s, any number of servers', 'tag': 'BEFORE'}, 'after': {'code': 'unit.takeOne()', 'note': 'under 0.3 s, from memory', 'tag': 'AFTER'}, 'taglines': [('Take the database out of the way', 'gold')]}, 'highlight': {}}
