"""Scene definitions for the Single Table Inheritance with JPA teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Single Table Inheritance with JPA',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Single Table Inheritance, with JPA and Hibernate, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Single table inheritance stores several related classes in one database table. [[slnc 300]] A type column says which class each row is. [[slnc 500]] JPA is the Java standard for storing objects in tables, and Hibernate is the open-source library that does the work. [[slnc 600]] Think of a single stock book, with a column for each kind of detail, and a word at the start of each line saying what kind of item it is. [[slnc 700]] In this video, the domain is an online shop's products: books, electronics, and food. [[slnc 500]] By the end, you will hear the SQL Hibernate writes for two strategies. [[slnc 300]] How each row comes back as its own class. [[slnc 300]] And a rule the database can no longer keep."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Books, electronics, food.', '', 'A table for each kind.', '', '"Everything under £10"', 'searched every table.'],
         narration='Here is the scenario. [[slnc 400]] The shop sells books, electronics, and food, each with its own details. [[slnc 500]] With a table for each kind, a question about all products had to search every table. [[slnc 500]] And every new kind made those questions bigger.'),
    dict(key='03-act-1', kind='console', title='Act One — A table per class',
         body='ONE. A table per class.\n  under £10: tea, desk lamp\n  SQL: a UNION over 3 tables',
         narration="First demo: a table for every class. [[slnc 400]] Books, electronics and food each have their own table. [[slnc 600]] The shop asks for everything under ten pounds. [[slnc 300]] Breakfast tea, and the desk lamp. [[slnc 500]] Hibernate's query joins three tables together, one after another. [[slnc 300]] A fourth kind of product makes it bigger again."),
    dict(key='04-act-2', kind='console', title='Act Two — One table',
         body='TWO. One table.\n  SQL: one plain select',
         narration="Second demo: one table. [[slnc 400]] The products now share a single table, with a type column. [[slnc 600]] The same question. [[slnc 300]] The same answer. [[slnc 500]] And Hibernate's query is one plain select, from one table."),
    dict(key='05-act-3', kind='console', title='Act Three — Each row as its own class',
         body='THREE. Each row as its own class.\n  KETTLE-1 -> Electronics: 2-year warranty\n  type column: BOOK, ELECTRONICS, FOOD',
         narration='Third demo: each row comes back as its own class. [[slnc 400]] The cook book comes back as a book, with its ISBN. [[slnc 300]] The kettle, as electronics, with its warranty card. [[slnc 300]] The tea, as food, with its best-before date. [[slnc 600]] Hibernate chose each class from the type column.'),
    dict(key='06-act-4', kind='console', title='Act Four — A new type',
         body='FOUR. A new type.\n  GIFT-1 -> GiftCard\n  one new column: value_pence',
         narration='Fourth demo: a new kind of product. [[slnc 400]] A gift card. [[slnc 300]] One new class, and one new column in the same table. [[slnc 600]] It loads back as a gift card, to be activated for fifty pounds on dispatch.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  15 of 20 cells NULL\n  isbn NOT NULL: refused\n  book with no ISBN: saved',
         narration='Fifth demo: the bill. [[slnc 400]] Fifteen of the twenty type-specific cells are empty. [[slnc 600]] Every book should have an ISBN. [[slnc 300]] But the database refuses to require it. [[slnc 300]] The kettle, lamp, tea and gift card have none. [[slnc 500]] So a book with no ISBN is saved. [[slnc 600]] The rule has to live in Java instead.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in JPA',
         body=['@Inheritance(SINGLE_TABLE).', '', '@DiscriminatorColumn: the type.', '@DiscriminatorValue: per class.', '', 'Hibernate writes the SQL.'],
         narration="Let's name the pattern, in JPA's words. [[slnc 400]] The inheritance annotation, set to single table. [[slnc 500]] A discriminator column holds the type. [[slnc 300]] Each class has its own discriminator value. [[slnc 500]] And Hibernate writes all the SQL."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Product: the one table', 'Book, Electronics, Food, GiftCard', 'CatalogItem: table per class', 'SqlLog: sees every statement'],
         narration='Here is who does what. [[slnc 400]] Product is mapped to the one table. [[slnc 300]] Book, electronics, food and gift card are its subclasses. [[slnc 500]] Catalog item is the comparison, with a table for each class. [[slnc 500]] And the SQL log sees every statement Hibernate sends.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['JPA @Inheritance', 'Rails single table inheritance', 'Tables with a dtype column'],
         narration='You have probably met this already. [[slnc 400]] The inheritance annotation, in JPA entities. [[slnc 500]] Ruby on Rails, which does the same with a type column. [[slnc 500]] And database tables with a column called D type, and many empty cells.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Types share most columns.', 'Queries span them all.', '', "Read Hibernate's SQL.", 'Rules in Java.', 'JOINED when cells run empty.'],
         narration='So, when should you use it? [[slnc 400]] When the types share most columns, and questions span all of them. [[slnc 500]] Read the SQL Hibernate writes. [[slnc 300]] Keep subclass rules in Java. [[slnc 300]] And move to the joined strategy when empty cells start to dominate.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Try the', 'JOINED strategy.'],
         narration="That's Single Table Inheritance, with JPA. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] One table and a type column, and always look at the SQL. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Switch to the joined strategy, and read the SQL it writes. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Single Table Inheritance with JPA Pattern  ·  Java 21', 'poster': {'headline': [('SINGLE TABLE', 'text'), ('INHERITANCE WITH JPA', 'text')], 'before': {'code': '@Inheritance(TABLE_PER_CLASS)', 'note': 'a UNION over 3 tables', 'tag': 'BEFORE'}, 'after': {'code': '@Inheritance(SINGLE_TABLE)', 'note': 'one plain select', 'tag': 'AFTER'}, 'taglines': [('One annotation, and the SQL behind it', 'gold')]}, 'highlight': {}}
