"""Scene definitions for the Railway-Oriented Programming with Vavr teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Railway-Oriented Programming with Vavr',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Railway-Oriented Programming, with the Vavr library, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Picture two railway tracks, one for success, one for failure. [[slnc 300]] Each step runs on the success track. [[slnc 300]] A failure switches to the other track, and every later step is skipped. [[slnc 500]] Vavr is an open-source functional library for Java that provides these tracks. [[slnc 600]] Think of an airport baggage belt. [[slnc 300]] A rejected bag goes onto a side belt that runs to the end. [[slnc 700]] In this video, the domain is an online shop's checkout. [[slnc 500]] By the end, you will hear how Vavr's either type chains the steps. [[slnc 300]] How try catches a library's exception. [[slnc 300]] And how validation reports every problem at once."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Validate, reserve, charge, email.', '', 'The payment library throws', 'on a declined card.', '', 'A forgotten catch: error page.'],
         narration="Here is the scenario. [[slnc 400]] The checkout has four steps. [[slnc 300]] Validate, reserve, charge, and email. [[slnc 500]] The payment company's library throws an exception when a card is declined. [[slnc 500]] A controller that forgot to catch it showed customers an error page."),
    dict(key='03-act-1', kind='console', title='Act One — A throwing library',
         body='ONE. A throwing library.\n  threw "card declined"',
         narration="First demo: a library that throws. [[slnc 400]] The payment company's library reports a declined card by throwing an exception. [[slnc 600]] Nothing forces the caller to handle it. [[slnc 300]] A controller that forgot, shows the customer an internal error."),
    dict(key='04-act-2', kind='console', title='Act Two — Either',
         body='TWO. Either.\n  200 order ORD-1 confirmed',
         narration="Second demo: Vavr's either type. [[slnc 400]] Each step returns either a failure, on the left, or a cart, on the right. [[slnc 600]] The steps are chained with flat map. [[slnc 500]] Two mugs, a good card. [[slnc 300]] All four steps run. [[slnc 300]] Order confirmed."),
    dict(key='05-act-3', kind='console', title='Act Three — Skipping, and Try',
         body='THREE. Skipping, and Try.\n  empty cart: 422 (at validate)\n  declined: 422 (at charge), via Try',
         narration="Third demo: the failure track. [[slnc 400]] An empty cart fails at the first step. [[slnc 300]] The other three are skipped. [[slnc 600]] A declined card fails at charge. [[slnc 300]] The library threw an exception. [[slnc 300]] Vavr's try caught it, and put it on the failure track. [[slnc 500]] So it is handled like any other failure."),
    dict(key='06-act-4', kind='console', title='Act Four — map and orElse',
         body='FOUR. map and orElse.\n  with tax: 23.98\n  lamp: back-order',
         narration='Fourth demo: plain steps, and a way back. [[slnc 400]] Adding tax cannot fail, so it rides along with map. [[slnc 300]] Twenty-three ninety-eight. [[slnc 600]] The lamp is out of stock. [[slnc 300]] Or else turns the failure into a back-order.'),
    dict(key='07-act-5', kind='console', title='Act Five — Validation',
         body='FIVE. Validation.\n  Either: 1 problem\n  Validation: both problems',
         narration="Fifth demo: collecting every problem. [[slnc 400]] A cart that is empty, and has no card. [[slnc 600]] The either chain stops at the first failure. [[slnc 300]] It reports only the empty cart. [[slnc 600]] Vavr's validation checks every field, and combines the results. [[slnc 300]] The cart is empty, and no card given. [[slnc 300]] Both at once."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Vavr',
         body=['Either: Left failure, Right success.', '', 'Try: exceptions onto the track.', '', 'Validation: every problem.'],
         narration="Let's name the pattern, in Vavr's words. [[slnc 400]] Either holds a failure on the left, or a success on the right. [[slnc 500]] Try moves exceptions onto the railway. [[slnc 500]] And validation collects every problem, instead of stopping at the first."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['CheckoutSteps: the steps', 'LegacyPayments: throws', 'Failure: step and reason', 'Vavr: Either, Try, Validation'],
         narration='Here is who does what. [[slnc 400]] Checkout steps holds the four steps, and the form check. [[slnc 500]] Legacy payments is the library that throws. [[slnc 500]] A failure records the step and the reason. [[slnc 300]] And Vavr supplies the types.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Vavr in Java codebases', 'Kotlin Result and Arrow', 'Scala Either and Try'],
         narration="You have probably met this already. [[slnc 400]] Vavr's either and try, in many Java codebases. [[slnc 500]] Kotlin's result type, and the Arrow library. [[slnc 500]] And Scala's either and try, which Vavr is modelled on."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Chains of steps: Either.', 'Code that throws: Try.', 'Forms: Validation.'],
         narration='So, when should you use it? [[slnc 400]] Use either for chains of steps that can fail. [[slnc 500]] Use try at the edge, where code throws. [[slnc 500]] And use validation for forms, where every problem should be reported.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a', 'postcode to the Validation.'],
         narration="That's Railway-Oriented Programming, with Vavr. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Keep failures on their own track, and when checking a form, collect them all. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a postcode check to the validation. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Railway-Oriented Programming with Vavr Pattern  ·  Java 21', 'poster': {'headline': [('RAILWAY-ORIENTED', 'text'), ('WITH VAVR', 'text')], 'before': {'code': 'throw new IllegalStateException', 'note': 'a forgotten catch: 500', 'tag': 'BEFORE'}, 'after': {'code': 'Either<Failure, Cart>', 'note': '422 at charge; both form errors', 'tag': 'AFTER'}, 'taglines': [('Either, Try and Validation', 'gold')]}, 'highlight': {}}
