"""Scene definitions for the Leader/Followers teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Leader/Followers',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Leader Followers pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A pool of threads takes turns. [[slnc 300]] One thread, the leader, waits for the next message. [[slnc 300]] When it gets one, it hands leadership to another thread, and then handles that message itself. [[slnc 600]] Think of a taxi rank. [[slnc 300]] The taxi at the front waits for a passenger. [[slnc 300]] When someone gets in, it drives off, and the next taxi moves up. [[slnc 300]] The car that picks you up is the car that takes you home. [[slnc 700]] In this video, the domain is an online shop's order service. [[slnc 300]] It receives a stream of order messages, and a pool of threads handles them. [[slnc 500]] By the end, you will hear what a dispatcher costs. [[slnc 300]] How leader and followers take turns. [[slnc 300]] How leadership passes on. [[slnc 300]] And why order is not kept."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A stream of order messages.', '', 'A dispatcher thread received each', 'and handed it to one of 4 workers.'],
         narration='Here is the scenario. [[slnc 400]] The order service receives a stream of order messages. [[slnc 500]] A dispatcher thread received each message. [[slnc 300]] Then it passed it, through a second queue, to one of four worker threads.'),
    dict(key='03-act-1', kind='console', title='Act One — A dispatcher that hands off',
         body='ONE. A dispatcher that hands off.\n  5 threads: 1 dispatcher + 4 workers\n  hand-offs between threads: 20\n  the dispatcher handled 0 orders',
         narration='First demo: a dispatcher receives every message, and hands it to a worker. [[slnc 400]] One dispatcher thread, and four workers. [[slnc 500]] The dispatcher takes each order message, and passes it through a second queue to a worker. [[slnc 600]] Twenty orders. [[slnc 300]] Twenty hand-offs between threads. [[slnc 300]] And the dispatcher itself handled no orders at all.'),
    dict(key='04-act-2', kind='console', title='Act Two — Leader and followers',
         body='TWO. Leader and followers.\n  4 threads, no dispatcher\n  20 orders handled\n  waiting for a message at once: 1',
         narration='Second demo: leader and followers. [[slnc 400]] Four threads, and no dispatcher. [[slnc 500]] At any moment, one thread is the leader. [[slnc 300]] Only the leader waits for the next message. [[slnc 300]] The others are followers, waiting their turn to lead. [[slnc 600]] Twenty orders are handled. [[slnc 300]] And never more than one thread waits for a message at the same moment.'),
    dict(key='05-act-3', kind='console', title='Act Three — Receive, promote, handle',
         body='THREE. Receive, promote, handle.\n  leadership passed on 20 times\n  same thread: 20 of 20\n  hand-offs: 0',
         narration='Third demo: receive, promote a follower, then handle. [[slnc 400]] The leader takes a message. [[slnc 300]] At once, it passes leadership to a follower. [[slnc 300]] Then it handles the message itself. [[slnc 600]] Leadership passes twenty times, once per order. [[slnc 300]] Every order is handled by the thread that received it. [[slnc 300]] Zero hand-offs.'),
    dict(key='06-act-4', kind='console', title='Act Four — Every thread works',
         body='FOUR. Every thread works.\n  20 orders, several threads\n  no pure dispatcher',
         narration='Fourth demo: every thread in the pool does real work. [[slnc 400]] The twenty orders were handled by several different pool threads. [[slnc 500]] None of them sat as a pure dispatcher, only receiving and passing on.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  received: place, then cancel\n  finished: cancel, then place',
         narration='Fifth demo: the bill. [[slnc 400]] Two messages for the same order arrive: place the order, then cancel it. [[slnc 600]] The first leader takes place order, and promotes a follower. [[slnc 300]] The follower takes cancel, which is quicker. [[slnc 500]] Cancel finishes first. [[slnc 300]] Then place. [[slnc 600]] Messages that must stay in order need to go to the same thread.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['One leader waits for a message.', 'Followers wait to lead.', '', 'Receive -> promote a follower', '-> handle it yourself.'],
         narration="Let's name the pattern. [[slnc 400]] One thread is the leader. [[slnc 300]] Only it waits for the next message. [[slnc 500]] The other threads are followers. [[slnc 300]] They wait to become leader. [[slnc 500]] When the leader receives a message, it promotes a follower, and then handles the message itself."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['LeaderFollowers: the pool', 'leadership: a lock', 'source: the incoming messages', 'Record: who received, who handled', 'DispatcherWorkers: the old way'],
         narration='Here is who does what. [[slnc 400]] Leader followers is the pool of threads. [[slnc 500]] Leadership is a lock. [[slnc 300]] The thread holding it is the leader. [[slnc 500]] The source is the queue of incoming messages. [[slnc 300]] Record notes who received each message, and who handled it. [[slnc 500]] And dispatcher workers is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['High-performance C++ servers', 'Threads taking turns on a selector', 'Several threads calling accept()'],
         narration='You have probably met this pattern in fast servers. [[slnc 400]] It was described for high-performance C++ servers. [[slnc 500]] Some event loops let several threads take turns on the same selector. [[slnc 500]] And several threads calling accept on the same server socket are, in effect, taking turns as leader.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Very high throughput, where a', 'hand-off per message counts.', '', 'Most apps: an ExecutorService.', '', 'Order matters? Same thread.'],
         narration='So, when should you use it? [[slnc 400]] In very high-throughput servers, where a hand-off per message is a real cost. [[slnc 500]] For most applications, a plain executor service is simpler, and fast enough. [[slnc 500]] And either way, messages that must stay in order should go to the same thread.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Keep place and cancel', 'in order.'],
         narration="That's the Leader Followers pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Take turns to wait, and handle what you receive yourself. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Send messages for the same order to the same thread, so place always finishes before cancel. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Leader/Followers Pattern  ·  Java 21', 'poster': {'headline': [('LEADER', 'text'), ('FOLLOWERS', 'text')], 'before': {'code': 'dispatcher.handOff(order)', 'note': '20 hand-offs', 'tag': 'BEFORE'}, 'after': {'code': 'lock(); take(); unlock(); handle()', 'note': '0 hand-offs', 'tag': 'AFTER'}, 'taglines': [('Take turns, no hand-offs', 'gold')]}, 'highlight': {}}
