"""Scene definitions for the Authorization Policy with Spring Security teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Authorization Policy with Spring Security',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Authorization Policy pattern, built with Spring Security, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Signing in proves who you are. [[slnc 300]] Authorization decides what you may do. [[slnc 300]] A policy makes those decisions by rules, and refuses anything no rule allows. [[slnc 500]] Spring Security is the open-source security framework most Java web applications use. [[slnc 600]] Think of a hotel key-card system. [[slnc 300]] Guests open their own room. [[slnc 300]] Staff open more. [[slnc 300]] A new door opens for nobody, until someone programs it. [[slnc 700]] In this video, the domain is an online shop, with customers, support staff and an admin. [[slnc 500]] By the end, you will hear how roles fall short. [[slnc 300]] How rules beside each endpoint fix it. [[slnc 300]] Why denying by default matters. [[slnc 300]] And two traps in the framework.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['View, refund and export endpoints.', '', 'Any customer could read any order.', '', 'Support could refund any amount.'],
         narration='Here is the scenario. [[slnc 400]] The shop has endpoints to view orders, refund them, and export them. [[slnc 500]] Any signed-in customer could read any order. [[slnc 500]] And support staff could refund any amount, though the rule was a hundred.'),
    dict(key='03-act-1', kind='console', title='Act One — Signed in is enough',
         body="ONE. Signed in is enough.\n  ana views ben's ORD-7: 200",
         narration="First demo: signed in is enough. [[slnc 400]] The old endpoint for viewing an order only asks that you are signed in. [[slnc 600]] Ana is a customer. [[slnc 300]] Ana asks for Ben's order. [[slnc 300]] And gets it."),
    dict(key='04-act-2', kind='console', title='Act Two — Roles only',
         body='TWO. Roles only.\n  hasRole(CUSTOMER): 200',
         narration="Second demo: roles only. [[slnc 400]] A rule on the address says, customers may view orders. [[slnc 600]] Ana is a customer. [[slnc 300]] Ana still sees Ben's order. [[slnc 500]] A role cannot say, their own orders."),
    dict(key='05-act-3', kind='console', title='Act Three — Rules beside each endpoint',
         body="THREE. Rules beside each endpoint.\n  ana -> ben's order: 403\n  ben -> own order: 200\n  sam 80: 200; 250: 403\n  alex 250: 200",
         narration="Third demo: rules beside each endpoint. [[slnc 400]] Viewing an order needs its owner, or support staff, or an admin. [[slnc 600]] Ana asks for Ben's order. [[slnc 300]] Refused. [[slnc 300]] Ben asks for the same order. [[slnc 300]] Allowed. [[slnc 600]] Refunds need an admin, or support staff up to a hundred. [[slnc 500]] Sam from support refunds eighty. [[slnc 300]] Allowed. [[slnc 300]] Two hundred and fifty. [[slnc 300]] Refused. [[slnc 500]] Alex, an admin, refunds two hundred and fifty. [[slnc 300]] Allowed."),
    dict(key='06-act-4', kind='console', title='Act Four — Deny by default',
         body='FOUR. Deny by default.\n  alex exports: 403',
         narration='Fourth demo: deny by default. [[slnc 400]] A developer added an export endpoint, and wrote no rule for it. [[slnc 600]] The last rule says, deny anything else. [[slnc 500]] So even Alex, the admin, is refused. [[slnc 300]] A new endpoint starts closed.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  refusals announced: 3\n  rules checked only at run time',
         narration='Fifth demo: the bill. [[slnc 400]] Spring Security announced each of the three refusals as an event. [[slnc 300]] But only because the shop asked it to. [[slnc 600]] The rules are written as text, and only checked when they run. [[slnc 300]] A typo shows up at the first request, not when the code is built. [[slnc 600]] And a rule on one method protects only that method. [[slnc 300]] Deny everything else by default.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Spring Security',
         body=['URL rules, ending in denyAll().', '', '@PreAuthorize beside each endpoint.', '', 'A policy bean for shop facts.', 'Refusals as events.'],
         narration="Let's name the pattern, in Spring Security's words. [[slnc 400]] Rules on addresses, ending with, deny anything else. [[slnc 500]] Pre-authorize rules, written beside each endpoint. [[slnc 500]] A policy bean for facts only the shop knows. [[slnc 300]] And every refusal published as an event."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShopApp: URL rules, users, events', 'OrderController: rules per endpoint', 'OrderPolicy: who owns which order'],
         narration='Here is who does what. [[slnc 400]] Shop app holds the address rules, the users, and the event listener. [[slnc 500]] The order controller carries a rule on each endpoint. [[slnc 500]] And the order policy knows who owns which order.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['@PreAuthorize and hasRole', 'SecurityFilterChain rules', 'Open Policy Agent'],
         narration='You have probably met this already. [[slnc 400]] Pre-authorize annotations, and has role, in Spring applications. [[slnc 500]] Security filter chains, listing which addresses need what. [[slnc 500]] And policy engines such as Open Policy Agent, for rules kept outside the code.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Different users, different rights.', '', 'Broad URL rules, denyAll last.', 'Detail beside endpoints.', 'Publish refusals.', 'Test every rule.'],
         narration='So, when should you use it? [[slnc 400]] As soon as different users may do different things. [[slnc 500]] Broad rules on addresses, ending with deny. [[slnc 300]] Detailed rules beside each endpoint. [[slnc 300]] Publish every refusal. [[slnc 300]] And test every rule.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Stop support', 'refunding their own orders.'],
         narration="That's the Authorization Policy, with Spring Security. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Put each rule where it is read, and let everything else be refused. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Stop support staff refunding orders they placed themselves. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Authorization Policy with Spring Security Pattern  ·  Java 21', 'poster': {'headline': [('AUTHORIZATION POLICY', 'text'), ('WITH SPRING SECURITY', 'text')], 'before': {'code': 'signed in is enough', 'note': "ana reads ben's order", 'tag': 'BEFORE'}, 'after': {'code': '@PreAuthorize(owns or staff)', 'note': '403, denied by default', 'tag': 'AFTER'}, 'taglines': [('Rules beside the code', 'gold')]}, 'highlight': {}}
