"""Scene definitions for the Valet Key teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Valet Key',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Valet Key pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Instead of carrying every upload yourself, you give the client a signed key. [[slnc 300]] The key lets it do one specific thing, directly with the storage service, for a few minutes. [[slnc 600]] Think of the valet key some cars come with. [[slnc 300]] It opens the door, and starts the engine. [[slnc 300]] But it will not open the boot, or the glovebox. [[slnc 300]] The attendant parks the car, and the key is only good for that job. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Customers add photos to their product reviews. [[slnc 500]] By the end, you will hear what carrying uploads costs. [[slnc 300]] How a valet key works. [[slnc 300]] What it will not allow. [[slnc 300]] And its one big risk.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Customers add photos to reviews.', '', 'Photos went to the app server,', 'which sent them on to storage.'],
         narration="Here is the scenario. [[slnc 400]] Customers can add photos to their product reviews. [[slnc 500]] Each photo was uploaded to the shop's app server. [[slnc 300]] The app server then sent it on to the file storage service."),
    dict(key='03-act-1', kind='console', title='Act One — Carried by the app',
         body='ONE. Carried by the app.\n  10 photos x 2 MB\n  the app server carried 40.0 MB',
         narration="First demo: review photos carried through the shop's app server. [[slnc 400]] Ten customers each upload a two megabyte photo. [[slnc 500]] Each photo goes to the app server. [[slnc 300]] The app server sends it on to storage. [[slnc 600]] The app server carried forty megabytes. [[slnc 300]] Every byte came in, and went out again."),
    dict(key='04-act-2', kind='console', title='Act Two — A valet key',
         body='TWO. A valet key.\n  key: PUT /reviews/R-11, 5 min, 5 MB\n  direct upload: 201 stored\n  app server carried under 200 bytes',
         narration="Second demo: a valet key. [[slnc 400]] The shop signs a short permission. [[slnc 300]] You may upload one photo, to this address, within five minutes, up to five megabytes. [[slnc 600]] The customer's browser sends the photo straight to storage. [[slnc 300]] Storage checks the signature, and stores it. [[slnc 500]] The app server carried under two hundred bytes. [[slnc 300]] Just the key."),
    dict(key='05-act-3', kind='console', title='Act Three — Only what it allows',
         body='THREE. Only what it allows.\n  read with it: 403\n  other review: 403\n  6 MB: 413; no key: 401',
         narration="Third demo: the key allows that, and nothing else. [[slnc 400]] Use it to read the photo? [[slnc 300]] Refused. [[slnc 500]] Change the address, to overwrite someone else's review? [[slnc 300]] Refused: the signature no longer matches. [[slnc 500]] Upload a six megabyte file? [[slnc 300]] Refused: too large. [[slnc 500]] And with no key at all, storage says no."),
    dict(key='06-act-4', kind='console', title='Act Four — Expiry',
         body='FOUR. Expiry.\n  valid 0.2 s, used at 0.4 s: 403 expired',
         narration='Fourth demo: the key runs out. [[slnc 400]] A key is signed for two tenths of a second. [[slnc 300]] It is used after four tenths. [[slnc 500]] Refused: key expired. [[slnc 300]] Nobody had to switch it off.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  a stranger uses the key: 201\n  short-lived, narrow, out of logs',
         narration='Fifth demo: the bill. [[slnc 400]] Whoever holds the key can use it. [[slnc 500]] A key is pasted into a public chat. [[slnc 300]] A stranger uses it. [[slnc 300]] Storage accepts: the key is valid. [[slnc 600]] It cannot be taken back before it expires. [[slnc 300]] So keep keys short-lived, narrow, and out of your logs.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['The app signs a key:', 'one method, one file, a size,', 'an expiry.', '', 'The client uses it directly.', 'Storage checks every part.'],
         narration="Let's name the pattern. [[slnc 400]] The app signs a key. [[slnc 300]] It names one action, one file, a size limit, and an expiry time. [[slnc 500]] The client uses the key to talk to storage directly. [[slnc 500]] Storage checks every part of it, and refuses anything else."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Shop: signs valet keys', 'Signer: a shared secret', 'Storage: checks and stores', 'Customer: uploads directly'],
         narration="Here is who does what. [[slnc 400]] The shop's app server signs valet keys. [[slnc 500]] The signer uses a secret that only the shop and the storage service know. [[slnc 500]] Storage checks each key, and stores the file. [[slnc 300]] And the customer's browser uploads directly."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Amazon S3 presigned URLs', 'Azure shared access signatures', 'Google Cloud signed URLs', 'Expiring download links'],
         narration='You have probably met this pattern already. [[slnc 400]] Amazon S3 has presigned URLs. [[slnc 300]] Azure has shared access signatures. [[slnc 300]] Google Cloud has signed URLs. [[slnc 500]] And every download link that stops working after a day is a valet key.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Large or many files the app', 'does not need to touch.', '', 'Sign method, path, size, expiry.', 'Short lifetimes.', 'Keep keys out of logs.'],
         narration='So, when should you use it? [[slnc 400]] For large, or many, files that the app does not need to look at. [[slnc 500]] Sign the method, the path, the size, and the expiry. [[slnc 300]] Keep lifetimes short. [[slnc 300]] And keep signed addresses out of your logs.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Make a key that', 'works only once.'],
         narration="That's the Valet Key pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Hand out a key that opens one door, briefly, and let the bytes go direct. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make a key that works only once. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Valet Key Pattern  ·  Java 21', 'poster': {'headline': [('VALET KEY', 'text')], 'before': {'code': 'upload -> app -> storage', 'note': '40 MB through the app', 'tag': 'BEFORE'}, 'after': {'code': 'PUT ...?expires=...&sig=...', 'note': 'straight to storage', 'tag': 'AFTER'}, 'taglines': [('A key that opens one door, briefly', 'gold')]}, 'highlight': {}}
