"""Scene definitions for the Cell-Based Architecture teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Cell-Based Architecture',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Cell-Based Architecture, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] In a cell-based system, the whole back end runs as several complete, independent copies, called cells. [[slnc 300]] Each cell serves its own share of the customers. [[slnc 300]] So a failure, or a bad release, only ever reaches one cell. [[slnc 600]] Think of a restaurant chain with branches in different neighbourhoods. [[slnc 300]] Each branch has its own kitchen and staff. [[slnc 300]] If one branch's oven breaks, only that branch closes for the evening. [[slnc 300]] And a new recipe is tried in one branch first. [[slnc 700]] In this video, the domain is an online shop, with thirty customers checking out. [[slnc 500]] By the end, you will hear how one shared back end fails everyone at once. [[slnc 300]] How cells limit the damage. [[slnc 300]] How to grow by adding a cell. [[slnc 300]] And what all those copies cost."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['One shared back end', 'for every customer.', '', 'A release with a checkout bug', 'goes out to everyone.'],
         narration='Here is the scenario. [[slnc 400]] The shop ran one shared back end, for every customer. [[slnc 500]] Then a release went out, with a bug in checkout. [[slnc 300]] Every release goes to everyone, at once.'),
    dict(key='03-act-1', kind='console', title='Act One — One shared stack',
         body='ONE. One shared stack.\n  a buggy release goes out\n  cannot check out: 30 of 30',
         narration='First demo: one shared stack for every customer. [[slnc 400]] A new release goes out, with a bug in checkout. [[slnc 600]] Thirty customers try to check out. [[slnc 300]] All thirty fail. [[slnc 500]] Everyone, everywhere, is affected at once.'),
    dict(key='04-act-2', kind='console', title='Act Two — Cells',
         body='TWO. Cells.\n  {cell-1=10, cell-2=10, cell-3=10}\n  C-1 -> cell-1; C-2 -> cell-2\n  failures: 0',
         narration="Second demo: cells. [[slnc 400]] The shop now runs as three cells. [[slnc 300]] Each is a complete copy of the back end, with its own database. [[slnc 600]] A thin router places the customers: ten in each cell. [[slnc 300]] Customer one lives in cell one, customer two in cell two. [[slnc 500]] Every request goes to the customer's own cell. [[slnc 300]] Everyone checks out."),
    dict(key='05-act-3', kind='console', title='Act Three — A small blast radius',
         body='THREE. A small blast radius.\n  buggy release to cell-1 only\n  cannot check out: 10 of 30\n  rolled back: 0 failures',
         narration='Third demo: a bad release reaches one cell, not everyone. [[slnc 400]] The buggy release goes to cell one first. [[slnc 600]] Ten customers cannot check out. [[slnc 300]] The other twenty can. [[slnc 500]] Cell one is rolled back. [[slnc 300]] Failures: zero. [[slnc 300]] Cells two and three never noticed.'),
    dict(key='06-act-4', kind='console', title='Act Four — Add a cell',
         body='FOUR. Add a cell.\n  6 new customers placed in cell-4\n  C-1 still in cell-1; nobody moved',
         narration='Fourth demo: more customers, add a cell. [[slnc 400]] The shop grows. [[slnc 300]] A fourth cell is added. [[slnc 500]] The router places new customers there. [[slnc 300]] Six newcomers go to cell four. [[slnc 500]] Customer one is still in cell one. [[slnc 300]] Nobody was moved.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  total sales: ask all 4 cells\n  4 copies of everything',
         narration="Fifth demo: the bill. [[slnc 400]] Every cell is a separate world. [[slnc 500]] To answer: what were today's total sales? [[slnc 300]] You must ask all four cells, and add up. [[slnc 600]] And there are now four copies of every service and database to run, watch, and pay for."),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Several complete copies: cells.', 'Each serves its own customers.', 'Cells share nothing.', '', 'A thin router: customer -> cell.', '', 'Release one cell at a time.'],
         narration="Let's name the pattern. [[slnc 400]] Run several complete copies of the back end. [[slnc 300]] These are the cells. [[slnc 300]] They share nothing with each other. [[slnc 500]] Each customer lives in one cell. [[slnc 300]] A thin router in front knows which, and sends every request there. [[slnc 500]] And releases go to one cell at a time."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['CellRouter: placement and forwarding', 'Cell: a complete copy of the shop', 'One shared stack: the old way'],
         narration="Here is who does what. [[slnc 400]] The cell router keeps a table of which customer lives in which cell, and forwards every request. [[slnc 500]] A cell is a complete copy of the shop's back end, with its own database. [[slnc 500]] And one shared stack is the old way, kept for comparison."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['AWS cell-based architecture', 'Slack and Salesforce pods', 'Region-by-region rollouts'],
         narration='You have probably met this pattern already. [[slnc 400]] Amazon Web Services builds many of its services from cells. [[slnc 500]] Slack and Salesforce place each customer in a pod. [[slnc 500]] And releases that go out region by region, or cell by cell, rely on the same idea.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Large systems where limiting', 'the blast radius is worth', 'many copies.', '', 'Thin router. One cell at a time.', 'Plan cross-cell questions.'],
         narration='So, when should you use it? [[slnc 400]] For large systems, where limiting the damage of failures and releases is worth running many copies. [[slnc 500]] Keep the router thin. [[slnc 300]] Release one cell at a time. [[slnc 300]] And plan how questions across all customers, and customer moves, will work. [[slnc 500]] For a smaller system, one stack is simpler.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Roll a release out', 'cell by cell.'],
         narration="That's Cell-Based Architecture. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Run small, complete copies, so any problem stays small. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Roll a release out cell by cell, and stop at the first failure. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Cell-Based Architecture Pattern  ·  Java 21', 'poster': {'headline': [('CELL-BASED', 'text'), ('ARCHITECTURE', 'text')], 'before': {'code': 'one stack for everyone', 'note': 'one bug: 30 of 30 down', 'tag': 'BEFORE'}, 'after': {'code': 'router.cellOf(customer)', 'note': 'one bug: 10 of 30, one cell', 'tag': 'AFTER'}, 'taglines': [('Small copies, small blast radius', 'gold')]}, 'highlight': {}}
