"""Scene definitions for the Table Data Gateway with JdbcTemplate teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Table Data Gateway with JdbcTemplate',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Table Data Gateway pattern, with Spring's JdbcTemplate, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A table data gateway is one class that holds all the SQL for one table. [[slnc 300]] Everyone else asks it, instead of writing their own. [[slnc 500]] JdbcTemplate is part of the open-source Spring framework, and it takes care of the database plumbing. [[slnc 600]] Think of a library's front desk. [[slnc 300]] Nobody walks into the stacks. [[slnc 300]] You ask the desk, and it fetches and returns books the same careful way every time. [[slnc 700]] In this video, the domain is an online shop's product table. [[slnc 500]] By the end, you will hear how hand-written database code leaks. [[slnc 300]] How the gateway keeps SQL in one place. [[slnc 300]] And what errors, and stock, look like with Spring."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Product page, stock report,', 'checkout: each wrote its own JDBC.', '', 'One never closed its connections.', '', 'A rename broke them all.'],
         narration='Here is the scenario. [[slnc 400]] The product page, the stock report, and checkout each wrote their own database code. [[slnc 500]] One page borrowed connections, and never gave them back. [[slnc 500]] And a renamed column broke them all at once.'),
    dict(key='03-act-1', kind='console', title='Act One — Hand-written JDBC that leaks',
         body='ONE. Hand-written JDBC that leaks.\n  page 1, page 2: served, not closed\n  page 3: FAILED, pool empty',
         narration='First demo: every page writes its own database code. [[slnc 400]] One page borrows a connection from the pool, and never gives it back. [[slnc 600]] The pool holds two connections. [[slnc 300]] The page works twice. [[slnc 500]] The third time, there are none left. [[slnc 300]] After a quarter of a second, it fails.'),
    dict(key='04-act-2', kind='console', title='Act Two — A gateway on JdbcTemplate',
         body='TWO. A gateway on JdbcTemplate.\n  4 requests on a pool of 2: fine\n  under £10: mug, tea towel',
         narration="Second demo: a table data gateway, built on JdbcTemplate. [[slnc 400]] All the product table's SQL, in one class. [[slnc 600]] The product page is asked four times, on the same pool of two. [[slnc 300]] It works every time. [[slnc 300]] JdbcTemplate always gives the connection back. [[slnc 600]] One product is out of stock. [[slnc 300]] And under ten pounds, the mug and the tea towel."),
    dict(key='05-act-3', kind='console', title='Act Three — Errors that mean something',
         body='THREE. Errors that mean something.\n  renamed column: BadSqlGrammarException\n  second MUG-1: DuplicateKeyException',
         narration="Third demo: errors that mean something. [[slnc 400]] A column is renamed, behind the gateway's back. [[slnc 300]] The next query fails, with Spring's bad SQL error. [[slnc 600]] A second mug with the same code. [[slnc 300]] A duplicate key error. [[slnc 500]] The same kinds of error, whatever the database. [[slnc 300]] So callers can react to them."),
    dict(key='06-act-4', kind='console', title='Act Four — Stock in one statement',
         body='FOUR. Stock in one statement.\n  4 tries, 2 lamps: 2 taken, stock 0',
         narration='Fourth demo: stock taken in one statement. [[slnc 400]] Four customers try for two desk lamps. [[slnc 600]] The gateway takes one only if the quantity is above zero, in the same statement. [[slnc 500]] Two are taken. [[slnc 300]] Stock ends at zero. [[slnc 300]] It can never go below.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  rows, not rules\n  SQL checked only at run time',
         narration='Fifth demo: the bill. [[slnc 400]] A row is only data. [[slnc 300]] Whether a product is low on stock is still decided by each caller. [[slnc 600]] The gateway grows a method for every question. [[slnc 300]] And its SQL is still text, only checked when it runs.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, with JdbcTemplate',
         body=['One gateway per table.', '', 'JdbcTemplate: borrow, run, return.', 'Row mappers: rows to records.', 'Spring exceptions.'],
         narration="Let's name the pattern, with Spring. [[slnc 400]] One gateway class for each table. [[slnc 500]] JdbcTemplate borrows a connection, runs the SQL, and always returns it. [[slnc 300]] A row mapper turns each row into a record. [[slnc 500]] And errors come back as Spring's own exceptions."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ProductGateway: all the SQL', 'Row: one row as data', 'ScatteredJdbc: the old way', 'HikariCP: the pool of 2'],
         narration="Here is who does what. [[slnc 400]] The product gateway holds all the SQL for the product table. [[slnc 500]] A row is one product's data. [[slnc 500]] Scattered JDBC is the old way, with its missing close. [[slnc 300]] And the pool holds just two connections, to make the leak visible."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Spring @Repository classes', 'Spring Data JDBC, jOOQ', 'DAO classes'],
         narration='You have probably met this already. [[slnc 400]] Spring repository classes, built on JdbcTemplate. [[slnc 500]] Spring Data JDBC and jOOQ, which generate or check the SQL for you. [[slnc 500]] And data access objects, the older name for the same idea.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Several parts share a table.', '', 'Plain SQL, safe plumbing.', 'Map to records.', 'Rules stay out.'],
         narration='So, when should you use it? [[slnc 400]] When several parts of the code share a table. [[slnc 500]] Keep plain SQL, and let Spring handle the plumbing. [[slnc 300]] Map rows to records. [[slnc 300]] And keep business rules out of the gateway.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Point it at', 'PostgreSQL.'],
         narration="That's the Table Data Gateway, with JdbcTemplate. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Keep a table's SQL in one class, and let the framework do the plumbing. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Point the gateway at PostgreSQL, and check the same errors come back. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Table Data Gateway with JdbcTemplate Pattern  ·  Java 21', 'poster': {'headline': [('TABLE DATA GATEWAY', 'text'), ('WITH JDBCTEMPLATE', 'text')], 'before': {'code': 'pool.getConnection() (no close)', 'note': 'third page: pool empty', 'tag': 'BEFORE'}, 'after': {'code': 'jdbc.query(sql, rowMapper)', 'note': 'every connection returned', 'tag': 'AFTER'}, 'taglines': [('One class of SQL, safe plumbing', 'gold')]}, 'highlight': {}}
