"""Scene definitions for the Write-Through Cache with Redis teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Write-Through Cache with Redis',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Write-Through Cache pattern, with a real Redis and a real PostgreSQL database, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] In a write-through cache, every write goes to the database, and then to the cache, before it is finished. [[slnc 300]] So the cache never shows something the database does not have. [[slnc 500]] Redis is an open-source in-memory store, often used as a cache shared by many servers. [[slnc 600]] Think of a shop's price list in the back office, and the price tags on the shelves. [[slnc 300]] Whoever changes a price updates the list, then the tag, before doing anything else. [[slnc 700]] In this video, the domain is an online shop's prices, shown on product pages and charged at checkout. [[slnc 500]] By the end, you will hear how a forgotten cache shows the wrong price. [[slnc 300]] How write-through fixes it. [[slnc 300]] And why two real systems can still disagree."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Pages read prices from Redis.', 'Checkout reads PostgreSQL.', '', 'The nightly job wrote', 'only to PostgreSQL.'],
         narration='Here is the scenario. [[slnc 400]] Product pages read prices from Redis. [[slnc 300]] Checkout reads the database. [[slnc 500]] The nightly price job wrote new prices only to the database. [[slnc 500]] Customers saw one price, and paid another.'),
    dict(key='03-act-1', kind='console', title='Act One — Round the cache',
         body='ONE. Round the cache.\n  page (Redis): £30.00\n  checkout (PostgreSQL): £27.00',
         narration='First demo: a price change goes round the cache. [[slnc 400]] The kettle costs thirty pounds, and that price is in Redis. [[slnc 600]] The nightly job writes twenty-seven pounds, straight into the database. [[slnc 300]] It forgets Redis. [[slnc 600]] The product page still says thirty. [[slnc 300]] Checkout charges twenty-seven.'),
    dict(key='04-act-2', kind='console', title='Act Two — Write through',
         body='TWO. Write through.\n  page £27.00, checkout £27.00\n  second instance: £27.00',
         narration='Second demo: write-through. [[slnc 400]] Every price write now goes through one store. [[slnc 300]] The database first, then Redis, before it returns. [[slnc 600]] The page says twenty-seven. [[slnc 300]] Checkout says twenty-seven. [[slnc 500]] And a second copy of the shop, reading the same Redis, says twenty-seven too.'),
    dict(key='05-act-3', kind='console', title='Act Three — Reads from Redis',
         body='THREE. Reads from Redis.\n  100 views: 0 database reads\n  Redis: 100 cache hits',
         narration="Third demo: reads come from Redis. [[slnc 400]] A hundred people view the product page. [[slnc 600]] The database is not read at all. [[slnc 300]] Redis's own counter shows a hundred cache hits."),
    dict(key='06-act-4', kind='console', title='Act Four — When one of the two refuses',
         body='FOUR. When one of the two refuses.\n  database refused: both £27.00\n  Redis unreachable: page £27.00, db £25.00',
         narration='Fourth demo: when one of the two refuses. [[slnc 400]] The database is read-only, for maintenance. [[slnc 300]] The write fails first, and Redis is never touched. [[slnc 300]] They still agree. [[slnc 600]] Now the other way round. [[slnc 300]] Redis cannot be reached, during a write. [[slnc 500]] The database saves twenty-five pounds. [[slnc 300]] Redis keeps twenty-seven. [[slnc 500]] Two systems. [[slnc 300]] No transaction covers both. [[slnc 300]] An expiry time on each cached price limits how long they can disagree.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  1000 + 1000 writes\n  1000 more prices in Redis',
         narration='Fifth demo: the bill. [[slnc 400]] The nightly job updates a thousand prices. [[slnc 300]] A thousand database writes, and a thousand Redis writes. [[slnc 600]] And Redis now holds a thousand more prices. [[slnc 300]] Most will never be viewed.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Every write: database, then Redis.', '', 'Every read: Redis.', '', 'Give cached values an expiry.'],
         narration="Let's name the pattern. [[slnc 400]] Every write goes to the database, then to Redis. [[slnc 500]] Every read comes from Redis. [[slnc 500]] And cached values get an expiry time, to limit how long they can be wrong."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['PriceStore: writes through', 'PriceDb: PostgreSQL, the truth', 'Redis: the shared cache', 'Infra: the containers'],
         narration='Here is who does what. [[slnc 400]] The price store writes through, and reads from the cache. [[slnc 500]] The price database is PostgreSQL, the record of truth. [[slnc 300]] Redis is the shared cache. [[slnc 500]] And the infra class starts both in containers.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Redis in front of a database', 'Hazelcast and Ignite map stores', 'CPU write-through caches'],
         narration='You have probably met this already. [[slnc 400]] Redis, in front of a database, in many web shops. [[slnc 500]] Hazelcast and Apache Ignite, which can write through for you. [[slnc 500]] And the caches inside a processor.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Read far more than written.', 'Stale values are costly.', '', 'Database first.', 'Give an expiry.', 'Plan for disagreement.'],
         narration='So, when should you use it? [[slnc 400]] For data read far more often than it is written, where a stale value is costly. [[slnc 500]] Write the database first. [[slnc 300]] Give cached values an expiry. [[slnc 300]] And plan for the moment the cache cannot be written.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Try a', '2-second expiry.'],
         narration="That's the Write-Through Cache, with Redis. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Write the truth, then the cache, and put a limit on how long they can disagree. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts Redis and PostgreSQL for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Set a two-second expiry, and watch the page correct itself. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Write-Through Cache with Redis Pattern  ·  Java 21', 'poster': {'headline': [('WRITE-THROUGH CACHE', 'text'), ('WITH REDIS', 'text')], 'before': {'code': 'UPDATE prices ... (only)', 'note': 'page £30, checkout £27', 'tag': 'BEFORE'}, 'after': {'code': 'db.write(); redis.set()', 'note': 'one price everywhere', 'tag': 'AFTER'}, 'taglines': [('Database, then Redis, every write', 'gold')]}, 'highlight': {}}
