"""Scene definitions for the Priority Queue teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Priority Queue',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Priority Queue pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] In a priority queue, urgent messages overtake routine ones. [[slnc 300]] However long the routine ones have been waiting. [[slnc 300]] And a share of capacity is kept, so routine work still gets done. [[slnc 600]] Think of the fast-track lane at airport security. [[slnc 300]] Passengers with a tight connection skip the long queue. [[slnc 300]] But at least one officer stays on the ordinary lane. [[slnc 300]] And if every ticket came with fast track, the fast lane would just be another queue. [[slnc 700]] In this video, the domain is an online shop's warehouse. [[slnc 300]] Pickers work through the orders, and same-day orders must catch the courier's van. [[slnc 500]] By the end, you will hear how same-day orders missed the van. [[slnc 300]] How a priority queue fixes it. [[slnc 300]] How to stop routine work being starved. [[slnc 300]] And what happens when everything is urgent."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Pickers do 10 orders a minute.', '', 'Same-day orders must reach', 'the van by 9:05.', '', 'One queue, first come first served.'],
         narration="Here is the scenario. [[slnc 400]] The warehouse pickers work through a queue of orders, ten a minute. [[slnc 500]] Same-day orders must be picked before the courier's van leaves, at five past nine. [[slnc 500]] The queue was first come, first served."),
    dict(key='03-act-1', kind='console', title='Act One — First come, first served',
         body='ONE. First come, first served.\n  100 standard at 9:00; 5 same-day at 9:01\n  last same-day picked at 9:10\n  the van left at 9:05',
         narration="First demo: one queue, first come, first served. [[slnc 400]] The pickers do ten orders a minute. [[slnc 500]] At nine o'clock, a hundred standard orders arrive. [[slnc 300]] At one minute past, five same-day orders. [[slnc 300]] The van leaves at five past. [[slnc 600]] The same-day orders wait behind all hundred. [[slnc 300]] The last one is picked at ten past nine. [[slnc 300]] The van has gone."),
    dict(key='04-act-2', kind='console', title='Act Two — A priority queue',
         body='TWO. A priority queue.\n  same-day picked by 9:01\n  standard orders straight after',
         narration='Second demo: a priority queue. [[slnc 400]] Same-day orders now go first. [[slnc 300]] Then, oldest first. [[slnc 600]] All five same-day orders are picked by one minute past nine. [[slnc 300]] In time for the van. [[slnc 500]] The standard orders carry on straight after.'),
    dict(key='05-act-3', kind='console', title='Act Three — A flood of standard orders',
         body='THREE. A flood of standard orders.\n  1000 standard ahead: same-day by 9:01',
         narration='Third demo: a flood of standard orders makes no difference. [[slnc 400]] This time, a thousand standard orders arrive first. [[slnc 500]] The same-day orders overtake all of them. [[slnc 300]] Still picked by one minute past nine.'),
    dict(key='06-act-4', kind='console', title='Act Four — Starvation, and a reserved share',
         body='FOUR. Starvation, and a reserved share.\n  strict: standard picked 0 of 20\n  2 reserved per minute: 20 of 20',
         narration='Fourth demo: too many urgent orders starve the rest. [[slnc 400]] Twelve same-day orders arrive every minute. [[slnc 300]] The pickers can do ten. [[slnc 600]] With strict priority, standard orders are never picked. [[slnc 300]] Zero of twenty, in ten minutes. [[slnc 600]] Now keep two picks a minute for the oldest standard orders. [[slnc 300]] All twenty are picked.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  every order marked same-day\n  rules for who sets priority',
         narration='Fifth demo: the bill. [[slnc 400]] If everything is urgent, nothing is. [[slnc 500]] Marketplace sellers learn that same-day jumps the queue. [[slnc 300]] So they mark every order same-day. [[slnc 600]] Priorities need rules about who may set them. [[slnc 300]] And more queues, and settings, to watch.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Each message has a priority.', '', 'Highest priority first,', 'then oldest first.', '', 'Keep a share for routine work.'],
         narration="Let's name the pattern. [[slnc 400]] Each message carries a priority. [[slnc 500]] Workers take the highest priority first. [[slnc 300]] Within the same priority, the oldest first. [[slnc 500]] And keep a share of capacity for routine work, so it is never starved."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Order: same-day or not, and its age', 'Picking.priority: the ordering', 'Picking.run: 10 picks a minute', 'Picking.fifo: the old way'],
         narration='Here is who does what. [[slnc 400]] An order knows whether it is same-day, and when it arrived. [[slnc 500]] The priority queue orders same-day first, then oldest. [[slnc 500]] The run method is the pickers: ten a minute, with an optional share kept for standard orders. [[slnc 300]] And the first-in, first-out queue is the old way.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['java.util.PriorityQueue', 'RabbitMQ priority queues', 'High and low SQS queues', 'Triage, fast-track lanes'],
         narration='You have probably met this pattern already. [[slnc 400]] Java has a priority queue class. [[slnc 500]] RabbitMQ supports priorities on queues. [[slnc 300]] And many systems run separate high and low priority queues. [[slnc 500]] Hospital triage and airport fast-track lanes work the same way.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Some work has a real,', 'earlier deadline.', '', 'Priority, then age.', 'Reserve a share.', 'Control who sets priority.'],
         narration='So, when should you use it? [[slnc 400]] When some work has a real, earlier deadline than the rest. [[slnc 500]] Order by priority, then by age. [[slnc 300]] Reserve a share for routine work. [[slnc 300]] And control who is allowed to mark work as urgent.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Promote orders older', 'than 15 minutes.'],
         narration="That's the Priority Queue pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let urgent work go first, but never let routine work wait for ever. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Promote standard orders that have waited more than fifteen minutes. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Priority Queue Pattern  ·  Java 21', 'poster': {'headline': [('PRIORITY', 'text'), ('QUEUE', 'text')], 'before': {'code': 'first come, first served', 'note': 'same-day missed the van', 'tag': 'BEFORE'}, 'after': {'code': 'same-day first', 'note': 'picked by 9:01', 'tag': 'AFTER'}, 'taglines': [('Urgent work goes first', 'gold')]}, 'highlight': {}}
