spring.main.banner-mode=off
logging.level.root=ERROR
logging.level.org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter=OFF
logging.level.org.springframework.boot.SpringApplication=OFF
