"""Scene definitions for the Micro-Frontends teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Micro-Frontends',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Micro-Frontends pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] With micro-frontends, a web page is split into parts, and each part belongs to one team. [[slnc 300]] Each team builds and releases its part on its own. [[slnc 300]] The page is assembled from those parts, with a fallback when one fails. [[slnc 600]] Think of a newspaper. [[slnc 300]] The sport, business, and weather desks each write their own pages. [[slnc 300]] The printers put the paper together from whatever arrives. [[slnc 300]] If the weather desk is late, the paper still goes out, with a note in the weather box. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Its product page shows the product, a small basket summary, and recommendations, built by three teams. [[slnc 500]] By the end, you will hear why one front-end for many teams fails as a whole. [[slnc 300]] How a page is assembled from team parts. [[slnc 300]] How failures stay in their slot. [[slnc 300]] And what it costs.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The product page:', 'product details, basket summary,', 'recommendations.', '', 'Three teams.', 'One front-end application.'],
         narration='Here is the scenario. [[slnc 400]] The product page shows the product details, a small basket summary, and recommendations. [[slnc 500]] Three teams work on it. [[slnc 300]] But it was one front-end application. [[slnc 300]] Built together, released together, and failing together.'),
    dict(key='03-act-1', kind='console', title='Act One — One front-end for everything',
         body='ONE. One front-end for everything.\n  [product] ... | [basket] ... | [recs] ...\n  recommendations bug: whole page fails',
         narration="First demo: one front-end renders the whole product page. [[slnc 400]] The product details, the basket summary, and the recommendations. [[slnc 300]] Three teams, one application. [[slnc 600]] The recommendations team ships a bug. [[slnc 300]] The whole page fails. [[slnc 300]] Including the parts that had nothing wrong with them. [[slnc 500]] And to fix it, everyone's code must be released together."),
    dict(key='04-act-2', kind='console', title='Act Two — Each team serves its part',
         body='TWO. Each team serves its part.\n  [product] steel kettle, £30.00\n  [basket] 2 items, £38.00\n  [recommendations] mug, teapot',
         narration="Second demo: micro-frontends. [[slnc 400]] Each team now runs its own small web application. [[slnc 300]] It serves only that team's part of the page. [[slnc 600]] The page itself is a layout with three slots. [[slnc 300]] Product, basket, and recommendations. [[slnc 300]] Each slot is filled by asking the team that owns it. [[slnc 500]] The page looks exactly as before."),
    dict(key='05-act-3', kind='console', title='Act Three — Failure stays in its slot',
         body='THREE. Failure stays in its slot.\n  recs fails: (recommendations unavailable)\n  recs slow: (recommendations unavailable)\n  product and basket served as normal',
         narration="Third demo: one team's failure stays in its slot. [[slnc 400]] The recommendations app fails. [[slnc 300]] The page still shows the product and the basket. [[slnc 300]] The recommendations slot says: unavailable. [[slnc 600]] Then the recommendations app is slow. [[slnc 300]] After three hundred milliseconds, the page stops waiting for it. [[slnc 300]] Same result: the rest of the page is served."),
    dict(key='06-act-4', kind='console', title='Act Four — Independent releases',
         body='FOUR. Independent releases.\n  [basket] 2 items, £38.00,\n           free delivery over £40',
         narration='Fourth demo: each team releases on its own. [[slnc 400]] The basket team releases version two. [[slnc 300]] It now says: free delivery over forty pounds. [[slnc 500]] The very next page view shows it. [[slnc 300]] The product and recommendations apps were not touched.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  1 page + 3 fragment requests\n  "30.00 GBP" next to "£38.00"',
         narration='Fifth demo: the bill. [[slnc 400]] One page view is now one page, and three fragment requests. [[slnc 300]] The slowest fragment sets the pace. [[slnc 600]] And teams drift apart. [[slnc 300]] The product team starts writing thirty point zero zero G B P. [[slnc 300]] The basket team writes pounds and pence. [[slnc 300]] The page looks like two different shops.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['The page is a layout of slots.', '', 'Each slot belongs to one team,', "served by that team's app.", '', 'Each slot has a timeout', 'and a fallback.'],
         narration="Let's name the pattern. [[slnc 400]] The page becomes a layout with slots. [[slnc 500]] Each slot belongs to one team. [[slnc 300]] It is filled by that team's own small application. [[slnc 500]] And each slot has a time limit and a fallback, so one team's problem never takes down the page."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['PageAssembler: layout and slots', "TeamApp: one team's fragment", 'OneFrontEnd: the old way'],
         narration="Here is who does what. [[slnc 400]] The page assembler holds the layout, fetches every slot at once, and fills in fallbacks. [[slnc 500]] A team app is one team's small server. [[slnc 300]] It serves only that team's fragment, and is released by that team. [[slnc 500]] And one front-end is the old way, kept for comparison."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Server-side and edge-side includes', 'Module Federation, single-spa', 'Big shops and news sites'],
         narration='You have probably met this pattern already. [[slnc 400]] Server-side includes, and edge-side includes on content delivery networks, assemble pages from parts. [[slnc 500]] In the browser, tools such as Module Federation and single-spa do it. [[slnc 500]] And many large shops and news sites give each team its own part of the page.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Several independent teams', "blocking each other's releases.", '', 'Timeouts and fallbacks.', 'A shared design system.', '', 'One team? One front-end.'],
         narration="So, when should you use it? [[slnc 400]] When several independent teams keep blocking each other's front-end releases. [[slnc 500]] Give every fragment a time limit and a fallback. [[slnc 300]] Share a design system, so the page still looks like one shop. [[slnc 500]] And when one team owns the page, keep one front-end."),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a reviews slot', 'for a new team.'],
         narration="That's the Micro-Frontends pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Each team owns its part of the page, and one part failing never takes down the rest. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a reviews slot, owned by a new team. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Micro-Frontends Pattern  ·  Java 21', 'poster': {'headline': [('MICRO-', 'text'), ('FRONTENDS', 'text')], 'before': {'code': 'one front-end, three teams', 'note': 'one bug, no page', 'tag': 'BEFORE'}, 'after': {'code': '[basket] <- basket team', 'note': 'each part on its own', 'tag': 'AFTER'}, 'taglines': [('Each team owns its part of the page', 'gold')]}, 'highlight': {}}
