"""Scene definitions for the Write-Through Cache teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Write-Through Cache',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Write-Through Cache pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] With a write-through cache, every write goes through the cache. [[slnc 300]] It writes the database, then updates its own copy, before saying the write is done. [[slnc 300]] So reads from the cache always match the database. [[slnc 600]] Think of a supermarket, where the till price and the shelf label must match. [[slnc 300]] Whoever changes a price in the till also changes the shelf label, straight away, before moving on. [[slnc 300]] A customer never sees one price and pays another. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Its product page reads prices from a cache, and a nightly job changes prices. [[slnc 500]] By the end, you will hear how a write round the cache causes trouble. [[slnc 300]] How write-through fixes it. [[slnc 300]] What happens when a write fails. [[slnc 300]] And what it costs.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Product page: reads a cache.', 'Checkout: reads the database.', '', 'A nightly job changes prices', 'in the database.'],
         narration='Here is the scenario. [[slnc 400]] The product page reads prices from a fast cache. [[slnc 300]] Checkout reads them from the database. [[slnc 600]] A nightly job changes prices. [[slnc 300]] It wrote them straight into the database.'),
    dict(key='03-act-1', kind='console', title='Act One — A write round the cache',
         body='ONE. A write round the cache.\n  page (cache): £30.00\n  checkout (database): £27.00',
         narration='First demo: a price change goes round the cache. [[slnc 400]] The product page reads prices from a fast cache. [[slnc 300]] Checkout reads them from the database. [[slnc 600]] The nightly job cuts the kettle to twenty-seven pounds. [[slnc 300]] It writes straight to the database, and forgets the cache. [[slnc 500]] The page still shows thirty pounds. [[slnc 300]] Checkout charges twenty-seven. [[slnc 300]] The customer sees one price, and pays another.'),
    dict(key='04-act-2', kind='console', title='Act Two — Write-through',
         body='TWO. Write-through.\n  store.put: database, then cache\n  page £27.00; checkout £27.00',
         narration='Second demo: write-through. [[slnc 400]] Every write now goes through the cache. [[slnc 500]] The job asks the store to set the kettle to twenty-seven pounds. [[slnc 300]] The store writes the database. [[slnc 300]] Then it updates its own copy. [[slnc 300]] Only then does it return. [[slnc 600]] The page says twenty-seven. [[slnc 300]] Checkout says twenty-seven.'),
    dict(key='05-act-3', kind='console', title='Act Three — Fast reads',
         body='THREE. Fast reads.\n  100 page views: 0 database reads',
         narration='Third demo: reads come from the cache. [[slnc 400]] A hundred people view the kettle. [[slnc 500]] Database reads: zero. [[slnc 300]] Every view was answered from the cache. [[slnc 300]] And every answer was up to date.'),
    dict(key='06-act-4', kind='console', title='Act Four — A refused write',
         body='FOUR. A refused write.\n  £25.00: database is read-only\n  page and database: both £27.00',
         narration='Fourth demo: a refused write changes nothing. [[slnc 400]] The database is read-only, for maintenance. [[slnc 500]] The price job tries twenty-five pounds. [[slnc 300]] The database refuses. [[slnc 300]] Because the store writes the database first, it never touches its cache. [[slnc 600]] Both still say twenty-seven. [[slnc 300]] They never disagree.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  1000 updates: 20.0 s waiting\n  1000 entries cached, few viewed',
         narration='Fifth demo: the bill. [[slnc 400]] Every write waits for the database. [[slnc 300]] A thousand price updates spend twenty seconds waiting. [[slnc 600]] And all thousand prices now sit in the cache. [[slnc 300]] Though most of those products will never be viewed.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Every write goes through the cache.', '', 'Database first, then the cache,', 'then return.', '', 'Reads come from the cache.'],
         narration="Let's name the pattern. [[slnc 400]] Every write goes through the cache. [[slnc 300]] Nothing writes around it. [[slnc 500]] The cache writes the database first. [[slnc 300]] Then it updates itself. [[slnc 300]] Only then does it tell the caller the write is done. [[slnc 500]] And reads come from the cache, which is always up to date."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['WriteThroughStore: get and put', 'Database: the source of truth', 'CacheAside: the old way'],
         narration='Here is who does what. [[slnc 400]] The write-through store has two methods. [[slnc 300]] Get reads from the cache. [[slnc 300]] Put writes the database, then the cache. [[slnc 500]] The database is the source of truth. [[slnc 300]] And cache aside, with the forgetful price job, is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Hazelcast, Ehcache write-through', 'Spring @CachePut', 'CPU write-through caches'],
         narration="You have probably met this pattern already. [[slnc 400]] Caches such as Hazelcast and Ehcache can be configured to write through. [[slnc 500]] Spring's cache put annotation updates the cache whenever a method writes. [[slnc 500]] And computer processors have write-through caches, between the processor and main memory."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Read often, must never be stale:', 'prices, stock levels.', '', 'Make it the only way to write.', '', 'Writes fast and many?', 'Consider write-behind.'],
         narration='So, when should you use it? [[slnc 400]] For data that is read often, and must never be out of date. [[slnc 300]] Prices, and stock levels. [[slnc 500]] Make it the only way to write that data. [[slnc 500]] And when writes are many, and speed matters more, consider write-behind instead.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Swap the two lines', 'in put, and see what breaks.'],
         narration="That's the Write-Through Cache pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Change the database and the cache together, every time, through one door. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Swap the two lines in put, and write a test that shows what breaks. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Write-Through Cache Pattern  ·  Java 21', 'poster': {'headline': [('WRITE-THROUGH', 'text'), ('CACHE', 'text')], 'before': {'code': 'db.write(price)', 'note': 'page £30, till £27', 'tag': 'BEFORE'}, 'after': {'code': 'store.put(sku, price)', 'note': 'both £27, always', 'tag': 'AFTER'}, 'taglines': [('Change both, together, every time', 'gold')]}, 'highlight': {}}
