"""Scene definitions for the Contract Stub with WireMock teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Contract Stub with WireMock',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Contract Stub pattern, with WireMock, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A contract stub is a stand-in for another service, built from a written agreement between two teams. [[slnc 300]] The real service is checked against the same agreement. [[slnc 300]] So the two can never quietly drift apart. [[slnc 500]] WireMock is an open-source stub server that answers real web requests. [[slnc 600]] Think of a fire drill run from the building's current floor plan. [[slnc 300]] The builders must update the plan whenever they move a wall. [[slnc 700]] In this video, the domain is an online shop's checkout, calling a payment service run by another team. [[slnc 500]] By the end, you will hear how a hand-written stub let a bug through. [[slnc 300]] How one contract file builds the stub and checks the real service. [[slnc 300]] And where Spring Cloud Contract fits."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Checkout calls payments.', '', 'Its tests used a hand-written stub.', '', 'Payments renamed a field.', 'Tests stayed green.'],
         narration="Here is the scenario. [[slnc 400]] The shop's checkout calls a payment service, run by another team. [[slnc 500]] Checkout's tests used a stub its own team had written. [[slnc 500]] The payment team renamed a field. [[slnc 300]] The tests stayed green. [[slnc 300]] Production broke."),
    dict(key='03-act-1', kind='console', title='Act One — A stub that drifted',
         body='ONE. A stub that drifted.\n  test vs hand stub: order confirmed\n  production vs v2: order stuck',
         narration="First demo: a hand-written stub. [[slnc 400]] The checkout team's stub approves every charge. [[slnc 300]] The checkout test passes. [[slnc 600]] But the payment team released version two. [[slnc 300]] It renamed the result field. [[slnc 500]] In production, checkout cannot find the result. [[slnc 300]] The order is stuck. [[slnc 300]] The stub never knew."),
    dict(key='04-act-2', kind='console', title='Act Two — A stub from the contract',
         body='TWO. A stub from the contract.\n  normal card: confirmed\n  no funds: declined\n  zero amount: rejected',
         narration='Second demo: a stub built from the contract. [[slnc 400]] The two teams share one file, with three agreed interactions. [[slnc 600]] A stub server is built from it. [[slnc 500]] A normal card is confirmed. [[slnc 300]] A card with no funds is declined. [[slnc 300]] A zero amount is rejected.'),
    dict(key='05-act-3', kind='console', title='Act Three — The provider is checked too',
         body='THREE. The provider is checked too.\n  version 1: 3 of 3\n  version 2: 0 of 3, build fails',
         narration="Third demo: the real payment service is checked against the same file. [[slnc 400]] Every interaction is sent to it, over HTTP. [[slnc 600]] Version one matches, three of three. [[slnc 500]] Version two matches none. [[slnc 300]] The payment team's own build fails, before the change reaches anyone."),
    dict(key='06-act-4', kind='console', title='Act Four — A strict stub',
         body='FOUR. A strict stub.\n  hand stub, USD: confirmed\n  contract stub, USD: 404 not matched',
         narration='Fourth demo: the contract stub is strict. [[slnc 400]] Checkout starts charging in US dollars. [[slnc 600]] The hand-written stub confirms it. [[slnc 300]] Nobody asked the payment team. [[slnc 500]] The contract stub answers, request was not matched. [[slnc 300]] And it shows the closest request it knows.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  shared, versioned, run by both',
         narration="Fifth demo: the bill. [[slnc 400]] The contract is shared work. [[slnc 300]] Both teams keep it, version it, and run it in both builds. [[slnc 600]] It covers only what is written in it. [[slnc 500]] And tools such as Spring Cloud Contract automate exactly this. [[slnc 300]] They generate the stubs, and the provider's tests, from the contracts."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, with WireMock',
         body=['One shared contract file.', '', 'Consumer: a WireMock stub', 'built from it.', '', 'Provider: replay it over HTTP.'],
         narration="Let's name the pattern, with WireMock. [[slnc 400]] One shared contract file. [[slnc 500]] The consumer tests against a WireMock stub, built from that file. [[slnc 500]] And the provider's build replays the same file against the real service."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['payments.json: the contract', 'ContractStub: WireMock from it', 'ProviderVerifier: checks the service', 'Checkout: the consumer'],
         narration='Here is who does what. [[slnc 400]] The contract file lists the agreed interactions. [[slnc 500]] The contract stub builds a WireMock server from it. [[slnc 500]] The provider verifier replays it against the real payment service. [[slnc 300]] And checkout is the consumer.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Spring Cloud Contract', 'Pact', 'Shared WireMock mappings'],
         narration="You have probably met this already. [[slnc 400]] Spring Cloud Contract generates WireMock stubs and provider tests from contracts. [[slnc 500]] Pact does the same, starting from the consumer's tests. [[slnc 500]] And teams often share WireMock mapping files in a repository."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Separate teams, separate releases.', '', 'Share and version the contract.', 'Run it in both builds.', 'Let a tool generate both halves.'],
         narration='So, when should you use it? [[slnc 400]] When separate teams release their services separately. [[slnc 500]] Share and version the contract. [[slnc 300]] Run it in both builds. [[slnc 300]] And let a tool generate both halves when the contracts grow.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a', 'USD interaction.'],
         narration="That's the Contract Stub, with WireMock. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Build the stub and check the real service from the same contract. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a US dollar interaction to the contract, and make both sides pass. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Contract Stub with WireMock Pattern  ·  Java 21', 'poster': {'headline': [('CONTRACT STUB', 'text'), ('WITH WIREMOCK', 'text')], 'before': {'code': 'post(anyUrl()) -> APPROVED', 'note': 'tests green, production stuck', 'tag': 'BEFORE'}, 'after': {'code': 'stubs built from payments.json', 'note': 'drift fails the build', 'tag': 'AFTER'}, 'taglines': [('One contract, a real stub server', 'gold')]}, 'highlight': {}}
