"""Scene definitions for the Half-Sync/Half-Async teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Half-Sync/Half-Async',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Half-Sync, Half-Async pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] The work is split in two halves, joined by a queue. [[slnc 300]] A fast half accepts events and only queues them. [[slnc 300]] A slow half of ordinary worker threads takes them from the queue, and does the blocking work, step by step. [[slnc 600]] Think of a busy restaurant. [[slnc 300]] The host at the door writes each order on a ticket, and pins it to the rail. [[slnc 300]] The cooks take tickets from the rail, one at a time. [[slnc 300]] If the host tried to cook as well, the queue at the door would stretch down the street. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Orders arrive in bursts, and each one needs a tenth of a second of slow work: save it, charge the card, and send an email. [[slnc 500]] By the end, you will hear why the receiving thread must never block. [[slnc 300]] How the two halves work. [[slnc 300]] How the queue absorbs a burst. [[slnc 300]] And what a full queue costs.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Orders arrive on an event thread,', 'sometimes 20 at once.', '', 'Each needs 100 ms:', 'save, charge, email.'],
         narration='Here is the scenario. [[slnc 400]] Orders arrive on one event thread. [[slnc 300]] Sometimes twenty at once. [[slnc 600]] Each order needs a tenth of a second of slow, blocking work. [[slnc 300]] Save it to the database. [[slnc 300]] Charge the card. [[slnc 300]] Send the confirmation email.'),
    dict(key='03-act-1', kind='console', title='Act One — Blocking work on the event thread',
         body='ONE. Blocking work on the event thread.\n  20 orders, 100 ms of work each\n  last accepted after over 1.5 s',
         narration="First demo: the event thread does every order's blocking work itself. [[slnc 400]] Twenty orders arrive at once. [[slnc 300]] Each needs a tenth of a second: save it, charge the card, send the email. [[slnc 600]] The event thread takes the first order, and does all its work. [[slnc 300]] Only then can it even accept the second. [[slnc 500]] The last order waits over a second and a half, just to be accepted."),
    dict(key='04-act-2', kind='console', title='Act Two — The async half',
         body='TWO. The async half.\n  every order accepted within 0.1 s\n  the event thread is free at once',
         narration='Second demo: the async half only accepts, and queues. [[slnc 400]] The event thread now does one quick job. [[slnc 300]] It puts each order in a queue. [[slnc 600]] All twenty orders are accepted within a tenth of a second. [[slnc 300]] The event thread is free again, at once.'),
    dict(key='05-act-3', kind='console', title='Act Three — The sync half',
         body='THREE. The sync half.\n  4 workers: save, charge, email\n  all 20 orders done in under 1 s',
         narration='Third demo: the sync half. [[slnc 400]] Four ordinary worker threads each take an order from the queue. [[slnc 300]] Then they save it, charge the card, and send the email, one step after another. [[slnc 600]] Plain, simple, blocking code. [[slnc 300]] Easy to read, easy to debug. [[slnc 500]] All twenty orders are done in under a second.'),
    dict(key='06-act-4', kind='console', title='Act Four — The queue absorbs the burst',
         body='FOUR. The queue absorbs the burst.\n  queue peak: 10 or more orders\n  event thread never waited',
         narration='Fourth demo: the queue in the middle absorbs the burst. [[slnc 400]] At the busiest moment, ten or more orders were waiting in the queue for a worker. [[slnc 600]] That is what the queue is for. [[slnc 300]] The event thread never waited for a card payment. [[slnc 300]] Only the workers did.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  workers stalled, queue of 10\n  10 of 20 orders turned away',
         narration='Fifth demo: the bill. [[slnc 400]] The card provider goes down, and the workers stall. [[slnc 300]] The queue fills up. [[slnc 600]] The queue holds ten orders. [[slnc 300]] Ten of the twenty are turned away. [[slnc 500]] Every queue needs a limit, and a plan for what happens when it is full.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Async half: accept and queue.', 'Never block.', '', 'Queue: bounded, in the middle.', '', 'Sync half: plain worker threads,', 'plain blocking code.'],
         narration="Let's name the pattern. [[slnc 400]] The async half accepts each event and puts it in a queue. [[slnc 300]] It never blocks. [[slnc 500]] The queue sits in the middle, with a limit. [[slnc 500]] The sync half is a few ordinary worker threads. [[slnc 300]] Each takes an event from the queue, and runs plain, step-by-step, blocking code."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['burst(): the async half', 'ArrayBlockingQueue: the rail', 'workLoop(): the sync half', 'OrderWork: save, charge, email', 'EventThreadOnly: the old way'],
         narration='Here is who does what. [[slnc 400]] The burst method is the async half: it only offers orders to the queue. [[slnc 500]] An array blocking queue is the ticket rail, with a limit. [[slnc 500]] The work loop is the sync half: take an order, and process it. [[slnc 300]] Order work holds the three slow steps. [[slnc 500]] And event thread only is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Event loop + worker pool', 'ExecutorService + BlockingQueue', 'API + background job queue', 'Interrupts + kernel threads'],
         narration="You have probably met this pattern already. [[slnc 400]] Web servers often have an event loop that hands requests to a pool of worker threads. [[slnc 500]] Java's executor services are a queue and worker threads. [[slnc 500]] A web A P I that drops jobs onto a queue for background workers is the same shape. [[slnc 300]] So is the way an operating system handles hardware interrupts."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Events on a thread that must', 'stay responsive; blocking work', 'behind them.', '', 'Tiny async half. Bounded queue.', 'Plain workers. A full-queue plan.'],
         narration='So, when should you use it? [[slnc 400]] Whenever events arrive on a thread that must stay responsive, and the work behind them blocks. [[slnc 500]] Keep the async half tiny. [[slnc 300]] Put a limit on the queue. [[slnc 300]] Decide what happens when it is full. [[slnc 300]] And keep the worker code plain.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Save turned-away orders', 'and retry them later.'],
         narration="That's the Half-Sync, Half-Async pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Accept fast, work slowly, and put a queue in between. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Instead of turning orders away, save them, and retry them later. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Half-Sync/Half-Async Pattern  ·  Java 21', 'poster': {'headline': [('HALF-SYNC', 'text'), ('HALF-ASYNC', 'text')], 'before': {'code': 'process(order) on the event thread', 'note': 'last order waited 1.5 s', 'tag': 'BEFORE'}, 'after': {'code': 'queue.offer(order)', 'note': 'accepted in 0.1 s', 'tag': 'AFTER'}, 'taglines': [('Accept fast, work slowly, queue between', 'gold')]}, 'highlight': {}}
