"""Scene definitions for the Input Validation teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Input Validation',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Input Validation pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Nothing that arrives from outside can be trusted. [[slnc 300]] So every field is checked, where it enters the program, against rules for what is allowed. [[slnc 300]] Before anything else uses it. [[slnc 600]] Think of the post room of a large office. [[slnc 300]] Every parcel is checked once, at the door. [[slnc 300]] Parcels that pass get a sticker, and nobody upstairs checks them again. [[slnc 300]] But anything sent back out still has to be packed for its own journey. [[slnc 700]] In this video, the domain is an online shop's checkout form, and its product reviews. [[slnc 500]] By the end, you will hear how unchecked input made a negative total. [[slnc 300]] How to check every field and report every problem. [[slnc 300]] How small types keep data valid. [[slnc 300]] And why valid text must still be made safe on the way out."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Checkout used form text as it arrived.', '', '-5 mugs: a negative total.', '"not-an-email" saved.', '', 'Reviews shown exactly as typed.'],
         narration="Here is the scenario. [[slnc 400]] The shop's checkout used the form's text exactly as it arrived. [[slnc 500]] Minus five mugs gave a negative total. [[slnc 300]] Junk was saved as an email address. [[slnc 500]] And product reviews were shown on the page exactly as typed."),
    dict(key='03-act-1', kind='console', title='Act One — Trusting the form',
         body='ONE. Trusting the form.\n  quantity -5: total -49.95\n  email: not-an-email, saved',
         narration="First demo: the form's text is used as it arrives. [[slnc 400]] Someone orders minus five mugs, at nine ninety-nine each. [[slnc 600]] The total is minus forty-nine ninety-five. [[slnc 300]] The shop would pay the customer. [[slnc 600]] And the words, not an email, are saved as the email address. [[slnc 300]] Nobody checked."),
    dict(key='04-act-2', kind='console', title='Act Two — Check at the boundary',
         body='TWO. Check at the boundary.\n  3 problems, reported together\n  good form: total 19.98',
         narration='Second demo: check every field where it arrives. [[slnc 400]] The product code must look like M U G dash twelve. [[slnc 300]] The quantity must be a whole number, from one to ninety-nine. [[slnc 300]] And the email must look like an email. [[slnc 600]] A bad form gets three problems, reported together. [[slnc 300]] So the customer can fix them all at once. [[slnc 500]] A good form, for two mugs, is accepted. [[slnc 300]] Total, nineteen ninety-eight.'),
    dict(key='05-act-3', kind='console', title='Act Three — Types that cannot be wrong',
         body='THREE. Types that cannot be wrong.\n  new Quantity(-5): refused\n  checkout takes a ValidOrder',
         narration='Third demo: turn text into types that cannot hold bad values. [[slnc 400]] A quantity is its own small type. [[slnc 300]] It checks itself when it is made. [[slnc 600]] Trying to make a quantity of minus five fails, straight away. [[slnc 600]] Checkout only accepts a valid order, built from these types. [[slnc 300]] So it never needs to check again. [[slnc 300]] If it has one, it is valid.'),
    dict(key='06-act-4', kind='console', title='Act Four — Encode on the way out',
         body='FOUR. Encode on the way out.\n  as typed: <script> runs\n  encoded: &lt;script&gt; shown',
         narration='Fourth demo: valid is not the same as safe everywhere. [[slnc 400]] A review says, lovely mug. [[slnc 300]] Followed by a hidden piece of script. [[slnc 600]] Shown on the page exactly as typed, the browser would run that script, for every shopper who reads it. [[slnc 600]] So the text is encoded on the way out. [[slnc 300]] Its angle brackets become harmless symbols. [[slnc 300]] The page shows the text, instead of running it.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body="FIVE. The bill.\n  [A-Za-z ]: Siobhán O'Brien rejected\n  any alphabet: accepted",
         narration="Fifth demo: the bill. [[slnc 400]] Rules must be fair. [[slnc 600]] A rule that allows only plain A to Z letters rejects a real customer, called Siobhán O'Brien. [[slnc 300]] A customer turned away. [[slnc 600]] A rule for letters in any alphabet, with apostrophes and hyphens, accepts the name. [[slnc 600]] And checks in the browser are only a convenience. [[slnc 300]] A request sent without the browser skips them. [[slnc 300]] So the server must always check."),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Check at the boundary.', '', 'Allow-list rules.', 'Report every problem.', 'Parse into safe types.', 'Encode on the way out.'],
         narration="Let's name the pattern. [[slnc 400]] Check all outside input at the boundary. [[slnc 500]] Use rules for what is allowed, and report every problem at once. [[slnc 300]] Turn the text into types that cannot hold bad values. [[slnc 500]] And encode text on its way out, for wherever it is shown."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['OrderParser: checks the whole form', 'Quantity, Email, Sku: check themselves', 'ValidOrder: only checked values', 'Html.escape: safe on the page'],
         narration='Here is who does what. [[slnc 400]] The order parser checks the whole form, and collects every problem. [[slnc 500]] Quantity, email and product code are small types that check themselves when they are made. [[slnc 500]] A valid order holds only checked values. [[slnc 300]] And the escape method makes text safe to show on a web page.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Bean Validation annotations', "Spring's @Valid", 'Value objects', 'Templates that escape by default'],
         narration="You have probably met this pattern already. [[slnc 400]] Java's validation annotations, such as not blank, and minimum. [[slnc 500]] Spring checks them for you, on request bodies. [[slnc 300]] Value objects that check themselves. [[slnc 500]] And web templates that encode text by default."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Always, on the server.', '', 'Strict about harm.', 'Fair to real people.', 'Parse into types.', 'Encode for the output.'],
         narration="So, when should you use it? [[slnc 400]] Always, and always on the server. [[slnc 500]] Be strict about what is harmful. [[slnc 300]] Be fair to real people's names and addresses. [[slnc 300]] Parse into safe types. [[slnc 300]] And encode text for wherever it goes next."),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a', 'postcode type.'],
         narration="That's the Input Validation pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Check everything that comes in, and encode everything that goes out. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a postcode type, with its own rule. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Input Validation Pattern  ·  Java 21', 'poster': {'headline': [('INPUT', 'text'), ('VALIDATION', 'text')], 'before': {'code': 'parseInt(form.quantity())', 'note': '-5 mugs: total -49.95', 'tag': 'BEFORE'}, 'after': {'code': 'Quantity.parse(text)', 'note': 'refused: 1 to 99 only', 'tag': 'AFTER'}, 'taglines': [('Trust no input', 'gold')]}, 'highlight': {}}
