"""Scene definitions for the Single Table Inheritance teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Single Table Inheritance',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Single Table Inheritance pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Single table inheritance stores several related classes in one database table. [[slnc 300]] A type column says which class each row is. [[slnc 300]] And each row leaves empty the columns that belong to other types. [[slnc 600]] Think of one travel expenses form for every kind of trip. [[slnc 300]] A section for car journeys, one for trains, one for flights. [[slnc 300]] You fill in yours and leave the rest blank. [[slnc 300]] And finance keeps one pile of forms. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] It sells books, food, and electronics. [[slnc 300]] Each has a code, a name, and a price, and one field of its own. [[slnc 500]] By the end, you will hear why a table per type makes simple questions slow. [[slnc 300]] How one table fixes it. [[slnc 300]] How each row becomes the right class. [[slnc 300]] And what it costs.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Books: an ISBN.', 'Food: a best-before date.', 'Electronics: a warranty.', '', 'All: a code, a name, a price.', '', 'One table per type.'],
         narration='Here is the scenario. [[slnc 400]] Books have an ISBN. [[slnc 300]] Food has a best-before date. [[slnc 300]] Electronics have a warranty. [[slnc 500]] All of them share a code, a name, and a price. [[slnc 500]] In the database, each type had its own table. [[slnc 300]] In Java, they are classes that share an interface.'),
    dict(key='03-act-1', kind='console', title='Act One — A table per type',
         body='ONE. A table per type.\n  under £10: [breakfast tea, desk lamp]\n  3 queries, one per table',
         narration='First demo: a table for every product type. [[slnc 400]] Books in one table, food in another, electronics in a third. [[slnc 600]] A customer asks for everything under ten pounds. [[slnc 300]] The shop has to ask all three tables. [[slnc 300]] Three queries, to find breakfast tea and a desk lamp. [[slnc 600]] Add a fourth type, and every question about all products needs a fourth query.'),
    dict(key='04-act-2', kind='console', title='Act Two — One table for all',
         body='TWO. One table for all.\n  under £10: [breakfast tea, desk lamp]\n  1 query',
         narration="Second demo: single table inheritance. [[slnc 400]] Every product now lives in one table. [[slnc 500]] It has the shared columns: code, name, and price. [[slnc 300]] A type column, saying book, food, or electronics. [[slnc 300]] And one column for each type's own field. [[slnc 600]] Everything under ten pounds is now one query, on one table."),
    dict(key='05-act-3', kind='console', title='Act Three — Each row becomes its own class',
         body='THREE. Each row becomes its own class.\n  BOOK-1 -> Book: ISBN 978-1-00\n  KETTLE-1 -> Electronics: 2-year warranty\n  TEA-1 -> Food: best before 2027-03-01',
         narration='Third demo: each row comes back as its own class. [[slnc 400]] When a row is loaded, its type column says which class to build. [[slnc 500]] Book one becomes a book, and its packing slip shows its ISBN. [[slnc 300]] The kettle becomes electronics, with a two-year warranty card. [[slnc 300]] The tea becomes food, with its best-before date.'),
    dict(key='06-act-4', kind='console', title='Act Four — A new type',
         body='FOUR. A new type.\n  ADD COLUMN value_pence\n  GIFT-1 -> GiftCard: activate £50',
         narration="Fourth demo: a new type. [[slnc 400]] The shop starts selling gift cards. [[slnc 300]] That needs one new class, and one new column, for the card's value. [[slnc 500]] Existing rows are untouched. [[slnc 300]] They just leave the new column empty. [[slnc 500]] Gift card one loads as a gift card: activate fifty pounds on dispatch."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  15 of 20 type cells are empty\n  a book without an ISBN was saved',
         narration='Fifth demo: the bill. [[slnc 400]] Five products, four type-specific columns. [[slnc 300]] Fifteen of the twenty cells are empty. [[slnc 600]] And the database can no longer keep type rules. [[slnc 300]] The ISBN column cannot be required, because food and kettles leave it empty. [[slnc 300]] So a book with no ISBN is saved, without complaint.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['One table for every type.', '', 'A type column: which class.', 'A column for every field.', '', 'Unused columns stay empty.'],
         narration="Let's name the pattern. [[slnc 400]] Store every type in one table. [[slnc 500]] Add a type column, saying which class each row is. [[slnc 300]] And a column for every field any type has. [[slnc 500]] Each row fills in its own columns, and leaves the rest empty. [[slnc 300]] When loading, the type column decides which class to build."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Product: the shared interface', 'Book, Food, Electronics, GiftCard', 'ProductTable: saves and loads', 'TablePerType: the old way', 'H2: an in-memory database'],
         narration='Here is who does what. [[slnc 400]] Product is the shared interface. [[slnc 300]] Book, food, electronics, and gift card implement it. [[slnc 500]] Product table saves them all into one table, and loads each row back as the right class. [[slnc 500]] Table per type is the old way, kept for comparison. [[slnc 300]] And H2 is a real database, running in memory.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['JPA: SINGLE_TABLE inheritance', '@DiscriminatorColumn', 'Rails: the type column', 'product_type in shop platforms'],
         narration='You have probably met this pattern already. [[slnc 400]] J P A offers single table inheritance, with a discriminator column for the type. [[slnc 500]] Ruby on Rails uses a column called type for the same thing. [[slnc 500]] And many shop platforms keep every product in one table, with a product type column.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Types share most fields and', 'are queried together.', '', 'Few type-specific fields.', 'CHECK constraints for type rules.', '', 'Many empty columns? Switch.'],
         narration='So, when should you use it? [[slnc 400]] When the types share most of their fields, and are often queried together. [[slnc 500]] Keep type-specific fields few. [[slnc 300]] Add check constraints for rules like: a book must have an ISBN. [[slnc 500]] And when the table fills with empty columns, switch to a table per class.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a CHECK that', 'every book has an ISBN.'],
         narration="That's the Single Table Inheritance pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Many classes, one table, and a type column to tell them apart. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline once its libraries are downloaded, with nothing else installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a check constraint, so every book must have an ISBN. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Single Table Inheritance Pattern  ·  Java 21', 'poster': {'headline': [('SINGLE TABLE', 'text'), ('INHERITANCE', 'text')], 'before': {'code': 'book, food, electronics', 'note': '3 queries per question', 'tag': 'BEFORE'}, 'after': {'code': "type = 'BOOK'", 'note': 'one table, one query', 'tag': 'AFTER'}, 'taglines': [('Many classes, one table', 'gold')]}, 'highlight': {}}
