"""Scene definitions for the Message Translator with Apache Camel teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Message Translator with Apache Camel',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Message Translator pattern, built with Apache Camel, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A message translator turns a message from one format into another. [[slnc 300]] So a receiver only ever sees the one format it understands. [[slnc 500]] Apache Camel is an open-source library for moving messages, and it has translators built in. [[slnc 600]] Think of an international post room. [[slnc 300]] A desk sees which language each letter is in, and passes it to that language's translator. [[slnc 300]] Every translator writes the same standard form, for the office upstairs. [[slnc 700]] In this video, the domain is an online shop's warehouse, taking orders from its web form and from marketplaces. [[slnc 500]] By the end, you will hear how Camel refuses a foreign format. [[slnc 300]] How each format becomes a route. [[slnc 300]] How a normalizer picks the right one. [[slnc 300]] And what the framework costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Web form: key=value.', 'Marketplace A: CSV.', 'Marketplace B: JSON.', 'Later, marketplace C: XML.', '', 'The warehouse needs one format.'],
         narration="Here is the scenario. [[slnc 400]] The shop's web form sends key and value text. [[slnc 300]] Marketplace A sends CSV. [[slnc 300]] Marketplace B sends JSON. [[slnc 300]] And later, marketplace C sends XML. [[slnc 600]] The warehouse must only ever see one standard order."),
    dict(key='03-act-1', kind='console', title='Act One — Straight to the warehouse',
         body='ONE. Straight to the warehouse.\n  JSON straight to warehouse\n  no type converter to OrderMessage',
         narration="First demo: send a marketplace's order straight to the warehouse. [[slnc 400]] In Camel, a route is a written description of where messages go. [[slnc 600]] The warehouse route starts by converting each message into the shop's standard order. [[slnc 500]] A raw JSON order cannot be converted. [[slnc 300]] So Camel refuses it, before the warehouse ever sees it."),
    dict(key='04-act-2', kind='console', title='Act Two — A translator route per format',
         body='TWO. A translator route per format.\n  CSV -> 2 x MUG-1 for A-77\n  JSON -> 1 x TEAPOT-1 for B-9\n  web -> 1 x KETTLE-1 for W-1',
         narration="Second demo: one translator route per format. [[slnc 400]] Camel has ready-made readers, called data formats. [[slnc 600]] The CSV route uses Camel's CSV reader. [[slnc 300]] Two mugs, for order A seventy-seven. [[slnc 500]] The JSON route uses Camel's JSON reader. [[slnc 300]] One teapot, for order B nine. [[slnc 500]] The web form route splits the text itself. [[slnc 300]] One kettle, for order W one."),
    dict(key='05-act-3', kind='console', title='Act Three — The normalizer',
         body='THREE. The normalizer.\n  inbox -> CSV, JSON, web: 3 picks\n  routes running: 5',
         narration='Third demo: the normalizer. [[slnc 400]] Every order now arrives at one inbox. [[slnc 600]] The normalizer looks at the text, and decides the format. [[slnc 300]] Curly bracket means JSON. [[slnc 300]] Angle bracket means XML. [[slnc 300]] An equals sign means the web form. [[slnc 300]] Anything else is CSV. [[slnc 600]] It then sends the order to the translator route with that name. [[slnc 500]] All three orders come out as standard picks. [[slnc 300]] Five routes are running.'),
    dict(key='06-act-4', kind='console', title='Act Four — A new format, a new route',
         body='FOUR. A new format, a new route.\n  before: no consumers on translate-xml\n  after one route: 1 x KETTLE-1 for C-5',
         narration='Fourth demo: a new marketplace sends XML. [[slnc 400]] The normalizer recognises it, and sends it on. [[slnc 300]] But no translator route exists yet. [[slnc 600]] Camel says so. [[slnc 300]] No consumers available. [[slnc 600]] One new route is added, while the others keep running. [[slnc 300]] It reads the XML. [[slnc 500]] Now the order is picked. [[slnc 300]] One kettle, for order C five. [[slnc 300]] The normalizer and the warehouse did not change.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  gift note lost\n  more than 20 library files',
         narration='Fifth demo: the bill. [[slnc 400]] The gift note from marketplace B is still lost. [[slnc 300]] The standard order has no room for it. [[slnc 600]] And the program now carries more than twenty library files. [[slnc 300]] The plain version needs none. [[slnc 500]] Plus a new route language, to learn.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Camel',
         body=['A translator is a route.', '', 'A data format reads the text.', '', 'A normalizer route sends each', 'message on by format name.'],
         narration="Let's name the pattern, in Camel's words. [[slnc 400]] Each translator is a route. [[slnc 500]] A data format reads the text into Java objects. [[slnc 500]] And a normalizer route sends each message to the translator whose name matches its format."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShopRoutes: every route', 'Translators: field mapping', 'OrderMessage: the standard order', 'Warehouse: receives only that'],
         narration="Here is who does what. [[slnc 400]] Shop routes holds every route, the normalizer, the translators, and the warehouse. [[slnc 500]] The translators class maps each format's fields to the standard names. [[slnc 500]] Order message is the standard order. [[slnc 300]] And the warehouse receives nothing else."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel in Spring Boot and Quarkus', 'Spring Integration transformers', 'MuleSoft DataWeave'],
         narration="You have probably met this already. [[slnc 400]] Camel routes run inside many Spring Boot and Quarkus services. [[slnc 500]] Spring Integration calls translators, transformers. [[slnc 500]] And MuleSoft's DataWeave is the same idea, in another tool."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Many formats and transports.', 'Translators added over time.', '', 'A few stable formats?', 'The plain version is simpler.'],
         narration='So, when should you use Camel for this? [[slnc 400]] When there are many formats and transports, and translators arrive over time. [[slnc 500]] For a few formats that rarely change, the plain Java version is simpler, and easier to debug.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Send unknown', 'formats to a dead-letter route.'],
         narration="That's the Message Translator, with Apache Camel. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Each format gets its own route, and the receiver only ever sees one shape. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Send orders in an unknown format to a dead-letter route. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Message Translator with Apache Camel Pattern  ·  Java 21', 'poster': {'headline': [('MESSAGE TRANSLATOR', 'text'), ('WITH CAMEL', 'text')], 'before': {'code': 'raw JSON -> warehouse', 'note': 'refused: no type converter', 'tag': 'BEFORE'}, 'after': {'code': 'unmarshal().json(Jackson)', 'note': 'one route per format', 'tag': 'AFTER'}, 'taglines': [('Translators as routes', 'gold')]}, 'highlight': {}}
