"""Scene definitions for the Currying teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Currying',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Currying, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Currying turns a function that takes several arguments into a chain of functions that each take one. [[slnc 300]] So the arguments you know early can be fixed once. [[slnc 300]] Leaving a smaller function, for the part that changes. [[slnc 600]] Think of a coffee shop loyalty card that already knows your usual. [[slnc 300]] Oat milk, large. [[slnc 300]] At the counter you only say which drink. [[slnc 300]] The usual choices were fixed once. [[slnc 700]] In this video, the domain is an online shop's shipping price, which depends on the zone, the service, and the weight. [[slnc 500]] By the end, you will hear how repeated arguments pile up. [[slnc 300]] How a curried function fixes them once. [[slnc 300]] Why argument order matters. [[slnc 300]] And when a plain lambda is clearer."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['price(zone, service, weight).', '', 'The EU warehouse always uses', 'EU and STANDARD.', '', 'Only the weight changes.'],
         narration='Here is the scenario. [[slnc 400]] The shipping price depends on the zone, the service, and the weight. [[slnc 500]] The EU warehouse only ever ships to the EU, by standard post. [[slnc 500]] Yet every call spelled out both, before the weight.'),
    dict(key='03-act-1', kind='console', title='Act One — Repeated arguments',
         body='ONE. Repeated arguments.\n  price(EU, STANDARD, 0.5) = 7.00\n  price(EU, STANDARD, 2.0) = 10.00\n  EU, STANDARD repeated every time',
         narration='First demo: the same arguments, again and again. [[slnc 400]] The shipping price needs a zone, a service, and a weight. [[slnc 600]] The EU warehouse prices three parcels. [[slnc 300]] Half a kilo, seven. [[slnc 300]] Two kilos, ten. [[slnc 300]] Ten kilos, twenty-six. [[slnc 600]] Every call repeats, EU, and standard. [[slnc 300]] Only the weight changes.'),
    dict(key='04-act-2', kind='console', title='Act Two — A curried function',
         body='TWO. A curried function.\n  euStandard = CURRIED(EU)(STANDARD)\n  euStandard(2.0) = 10.00',
         narration='Second demo: a curried function. [[slnc 400]] It takes one argument at a time. [[slnc 600]] Give it the zone, EU. [[slnc 300]] It gives back a function that wants a service. [[slnc 500]] Give that one, standard. [[slnc 300]] It gives back a function that wants only a weight. [[slnc 300]] Call it, EU standard. [[slnc 600]] EU standard, for two kilos. [[slnc 300]] Ten. [[slnc 300]] Exactly the same as before.'),
    dict(key='05-act-3', kind='console', title='Act Three — Ready-made functions',
         body='THREE. Ready-made functions.\n  2 kg: UK 5.00, EU 10.00, WORLD 20.00\n  EU express: [14.00, 20.00, 52.00]',
         narration="Third demo: ready-made functions. [[slnc 400]] At start-up, the shop builds one function per zone, for standard post. [[slnc 600]] A two kilo parcel. [[slnc 300]] UK, five. [[slnc 300]] EU, ten. [[slnc 300]] Rest of the world, twenty. [[slnc 600]] A ready-made function takes just one argument. [[slnc 300]] So it fits straight into map. [[slnc 500]] Checkout's three parcels, EU express. [[slnc 300]] Fourteen, twenty, and fifty-two."),
    dict(key='06-act-4', kind='console', title='Act Four — Argument order matters',
         body='FOUR. Argument order matters.\n  (percent, price): 20% off 45 = 36.00\n  (price, percent): gives 11.00',
         narration='Fourth demo: argument order matters. [[slnc 400]] Currying fixes the first argument first. [[slnc 600]] A discount takes a percentage, then a price. [[slnc 300]] Fix twenty. [[slnc 300]] You have a twenty percent off function. [[slnc 300]] Forty-five becomes thirty-six. [[slnc 600]] Now write it the other way round. [[slnc 300]] Price first, then percentage. [[slnc 300]] Fixing twenty now fixes the price. [[slnc 500]] Apply forty-five, and you get eleven. [[slnc 300]] Nonsense. [[slnc 600]] Put the arguments that change least, first.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  Function<Zone, Function<Service, ...>>\n  kg -> price(EU, STANDARD, kg): 10.00',
         narration='Fifth demo: the bill. [[slnc 400]] Java makes currying noisy. [[slnc 300]] The type is a function, returning a function, returning a function. [[slnc 600]] A plain lambda can do the same job. [[slnc 300]] Weight goes in, and it calls price with EU, and standard. [[slnc 300]] Same answer, ten. [[slnc 500]] And it is often clearer.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['One argument at a time.', '', 'Each step returns a function', 'that wants the next one.', '', 'Fix early arguments once.'],
         narration="Let's name the pattern. [[slnc 400]] The function takes one argument at a time. [[slnc 500]] Each step returns a function that wants the next argument. [[slnc 500]] So the early arguments are fixed once. [[slnc 300]] This fixing is called partial application."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['price: all arguments at once', 'CURRIED: zone, then service, then weight', 'curry: makes any two-argument', 'function curried'],
         narration='Here is who does what. [[slnc 400]] Price takes all three arguments at once. [[slnc 500]] Curried takes a zone, then a service, then a weight, one at a time. [[slnc 500]] And the curry helper turns any two-argument function into a curried one.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Haskell and F#', "Vavr's curried()", 'Factories and configured objects'],
         narration='You have probably met this pattern already. [[slnc 400]] In Haskell and F sharp, every function is curried. [[slnc 500]] The Vavr library adds a curried method to Java functions. [[slnc 500]] And any factory that fixes settings once, then takes the changing part, is doing partial application.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Some arguments known early.', '', 'Least-changing first.', 'Reuse the smaller function.', 'A lambda if clearer.'],
         narration='So, when should you use it? [[slnc 400]] When some arguments are known long before the others. [[slnc 500]] Put the least-changing arguments first. [[slnc 300]] Reuse and pass around the smaller function. [[slnc 300]] And use a plain lambda when it reads better.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Write', 'a curry3 helper.'],
         narration="That's Currying. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Fix the arguments you know now, and pass on a function for the rest. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Write a curry helper for three-argument functions. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Currying Pattern  ·  Java 21', 'poster': {'headline': [('CURRYING', 'text')], 'before': {'code': 'price(EU, STANDARD, kg)', 'note': 'EU, STANDARD every time', 'tag': 'BEFORE'}, 'after': {'code': 'euStandard.apply(kg)', 'note': 'fixed once, weight only', 'tag': 'AFTER'}, 'taglines': [('Fix some arguments now, the rest later', 'gold')]}, 'highlight': {}}
