"""Scene definitions for the Process Manager teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Process Manager',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Process Manager pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A process manager takes charge of a process with several steps. [[slnc 300]] It keeps track of where each case is, sends it to the next step, and decides what happens after every reply. [[slnc 300]] Including when something goes wrong. [[slnc 600]] Think of a wedding planner. [[slnc 300]] The caterer, the florist, and the venue only talk to the planner. [[slnc 300]] When the florist cannot deliver, the planner calls a backup. [[slnc 300]] When the venue cancels, the planner cancels the caterer too. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] Each order must be reserved, paid for, and shipped. [[slnc 500]] By the end, you will hear how a simple chain of steps loses track. [[slnc 300]] How a process manager runs each order. [[slnc 300]] How it handles branches and failures. [[slnc 300]] And what a central brain costs.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Reserve stock -> take payment -> ship.', '', 'Each service passed the order on.', '', 'Cards get declined.', 'Warehouses run out.'],
         narration='Here is the scenario. [[slnc 400]] Each order is fulfilled in three steps. [[slnc 300]] Reserve the stock. [[slnc 300]] Take payment. [[slnc 300]] Ship. [[slnc 600]] Each service simply passed the order on to the next. [[slnc 500]] But cards get declined, and warehouses run out.'),
    dict(key='03-act-1', kind='console', title='Act One — Steps chained together',
         body='ONE. Steps chained together.\n  ORD-3 card declined: stopped at payments\n  stock 1 of 3; only 1 shipped\n  where is ORD-3? nobody knows',
         narration="First demo: each step hands on to the next. [[slnc 400]] The warehouse reserves a kettle, and hands on to payments. [[slnc 300]] Payments charges, and hands on to shipping. [[slnc 600]] Order one ships. [[slnc 500]] Order three's card is declined. [[slnc 300]] The chain stops at payments. [[slnc 300]] But the warehouse never hears, so its kettle stays reserved. [[slnc 500]] Only one kettle shipped, yet two are gone from stock. [[slnc 300]] And where is order three now? [[slnc 300]] Nobody knows."),
    dict(key='04-act-2', kind='console', title='Act Two — A process manager',
         body='TWO. A process manager.\n  ORD-1: main RESERVED, PAID, SHIPPED\n  -> DONE',
         narration="Second demo: a process manager runs each order's journey. [[slnc 400]] The services no longer call each other. [[slnc 300]] They only answer the manager. [[slnc 600]] For order one, the manager asks the main warehouse to reserve. [[slnc 300]] Reserved. [[slnc 300]] It asks payments to charge. [[slnc 300]] Paid. [[slnc 300]] It asks shipping to ship. [[slnc 300]] Shipped. [[slnc 500]] Order one is done."),
    dict(key='05-act-3', kind='console', title='Act Three — A branch',
         body='THREE. A branch.\n  ORD-2: main OUT_OF_STOCK\n  partner RESERVED, PAID, SHIPPED -> DONE',
         narration='Third demo: the manager decides the next step. [[slnc 400]] Order two is a sofa. [[slnc 300]] The main warehouse replies: out of stock. [[slnc 600]] The manager decides: try the partner warehouse. [[slnc 300]] Reserved. [[slnc 500]] The order is paid, shipped, and done.'),
    dict(key='06-act-4', kind='console', title='Act Four — The unhappy path',
         body='FOUR. The unhappy path.\n  ORD-3: RESERVED, DECLINED, RELEASED\n  cancelled; stock 2 of 3\n  email: your card was declined',
         narration="Fourth demo: the unhappy path is part of the process. [[slnc 400]] Order three's card is declined. [[slnc 500]] The manager knows this order reserved a kettle. [[slnc 300]] So it tells the warehouse to release it. [[slnc 300]] And it emails the customer. [[slnc 600]] The order is cancelled, cleanly. [[slnc 300]] The kettle is back in stock."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  ORD-1=DONE, ORD-2=DONE, ORD-3=CANCELLED\n  one class holds every route\n  state in memory: lost on restart',
         narration='Fifth demo: the bill. [[slnc 400]] The manager can say where every order is, in one line. [[slnc 500]] But every route, and every branch, lives in one class. [[slnc 300]] It grows with each new step. [[slnc 500]] And its state is in memory. [[slnc 300]] A restart would forget every order in progress. [[slnc 300]] Real process managers store their state.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['One component owns the process.', '', "It keeps each order's state,", 'sends it to the next step,', 'and decides after every reply.', '', 'Services never call each other.'],
         narration="Let's name the pattern. [[slnc 400]] One component owns the process. [[slnc 500]] It keeps each order's state. [[slnc 300]] It sends the order to the next step. [[slnc 300]] And after every reply, it decides what happens next. [[slnc 500]] The services never call each other. [[slnc 300]] They only answer the process manager."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ProcessManager: state and decisions', 'Warehouse, partner, payments,', 'shipping, emails: one job each', 'Chained: the old way'],
         narration="Here is who does what. [[slnc 400]] The process manager holds each order's state, and decides every next step. [[slnc 500]] The main warehouse, the partner warehouse, payments, shipping, and emails each do one job, and answer. [[slnc 500]] And chained is the old way, kept for comparison."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camunda, Temporal', 'AWS Step Functions', 'Orchestrated sagas', 'Order management systems'],
         narration="You have probably met this pattern already. [[slnc 400]] Workflow engines such as Camunda, Temporal, and Step Functions are process managers you configure. [[slnc 500]] Orchestrated sagas in microservices are the same idea. [[slnc 500]] And every order management system that tracks each order's status is one."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Routes that branch.', 'Failures that must be undone.', '', 'Store the state.', 'Long or many processes?', 'Use a workflow engine.'],
         narration="So, when should you use it? [[slnc 400]] When routes branch, and failures must be undone. [[slnc 500]] Store the manager's state, so a restart forgets nothing. [[slnc 500]] And when processes are long, or many, use a workflow engine rather than writing your own."),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', "are in the repository. Save the manager's", 'state and restart it.'],
         narration="That's the Process Manager pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Let one place own the whole journey, including the unhappy paths. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Save the manager's state to a file, and restart it in the middle of an order. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Process Manager Pattern  ·  Java 21', 'poster': {'headline': [('PROCESS', 'text'), ('MANAGER', 'text')], 'before': {'code': 'reserve -> charge -> ship', 'note': 'declined: stock leaked', 'tag': 'BEFORE'}, 'after': {'code': 'on reply: decide next step', 'note': 'every path handled', 'tag': 'AFTER'}, 'taglines': [('One place that knows the whole journey', 'gold')]}, 'highlight': {}}
