"""Scene definitions for the Routing Slip with Apache Camel teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Routing Slip with Apache Camel',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Routing Slip pattern, built with Apache Camel, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A routing slip is a list of steps, written once, that travels with a message. [[slnc 300]] Each step does its job, and passes the message to the next step on the list. [[slnc 500]] Apache Camel is an open-source library for moving messages, and it follows slips for you. [[slnc 600]] Think of a hospital treatment card. [[slnc 300]] Reception writes down the departments this patient must visit. [[slnc 300]] Each department does its part, and sends the patient to the next name on the card. [[slnc 700]] In this video, the domain is an online shop's order processing. [[slnc 500]] By the end, you will hear how Camel follows each order's slip. [[slnc 300]] How to add a step with one rule. [[slnc 300]] And what to use when the next step must be decided on the way."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Validate, age check, customs,', 'charge, gift wrap, pack.', '', 'Every order visited all six.', '', '24 visits, 15 useful.'],
         narration='Here is the scenario. [[slnc 400]] The shop has six steps. [[slnc 300]] Validate, age check, customs, charge, gift wrap, and pack. [[slnc 500]] Every order visited all six. [[slnc 500]] Four orders made twenty-four visits. [[slnc 300]] Only fifteen did any work.'),
    dict(key='03-act-1', kind='console', title='Act One — One fixed pipeline',
         body='ONE. One fixed pipeline.\n  24 visits, 15 did any work',
         narration='First demo: one fixed pipeline for every order. [[slnc 400]] Every order visits all six steps. [[slnc 600]] Four orders, twenty-four visits. [[slnc 300]] Only fifteen of them did any work. [[slnc 500]] The rest were steps checking whether they applied, and finding they did not.'),
    dict(key='04-act-2', kind='console', title='Act Two — The slip',
         body='TWO. The slip.\n  ORD-2: validate, charge, gift-wrap, pack\n  ORD-4: validate, customs, charge, pack',
         narration='Second demo: the slip. [[slnc 400]] As each order sets off, the slip writer lists the steps it needs. [[slnc 600]] Order one needs validate, charge and pack. [[slnc 300]] Order two is a gift, so it adds gift wrap. [[slnc 300]] Order three is age restricted, so it adds an age check. [[slnc 300]] Order four goes abroad, so it adds customs. [[slnc 600]] The list travels with the order, in a header.'),
    dict(key='05-act-3', kind='console', title='Act Three — Camel follows the slip',
         body='THREE. Camel follows the slip.\n  15 visits, 15 doing work\n  ORD-2: validate, charge, gift-wrap, pack',
         narration='Third demo: Camel follows the slip. [[slnc 400]] The routing slip step reads the header, and sends the order to each step in turn. [[slnc 600]] Fifteen visits in all. [[slnc 300]] Every one doing work. [[slnc 500]] And no step knows which step comes after it.'),
    dict(key='06-act-4', kind='console', title='Act Four — A new step',
         body='FOUR. A new step.\n  ORD-4: ... customs, fraud-check, charge ...',
         narration='Fourth demo: a new step. [[slnc 400]] Orders over five hundred pounds need a fraud check. [[slnc 600]] One rule is added, where slips are written. [[slnc 500]] Order four now goes through the fraud check, before it is charged. [[slnc 300]] No route, and no other step, changed.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill, and a dynamic router',
         body='FIVE. The bill, and a dynamic router.\n  slip stops; still on it: charge, pack\n  dynamicRouter: -> notify-customer',
         narration="Fifth demo: the bill. [[slnc 400]] Order five's customer is too young. [[slnc 300]] The age check fails. [[slnc 600]] The slip just stops. [[slnc 300]] Charge and pack are still on it. [[slnc 300]] A slip cannot change course, because it was written at the start. [[slnc 600]] Camel has a relative, the dynamic router. [[slnc 300]] It decides each next step as it goes. [[slnc 300]] It sends order five to a step that tells the customer why."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Camel',
         body=['Write the steps into a header.', '', 'routingSlip() follows them.', '', 'dynamicRouter() decides', 'on the way.'],
         narration="Let's name the pattern, in Camel's words. [[slnc 400]] Write each order's steps into a header. [[slnc 500]] The routing slip step follows them, one by one. [[slnc 500]] And when the next step depends on what just happened, the dynamic router decides it on the way."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['SlipWriter: lists the steps', 'ShopRoutes: slip and dynamic router', 'Steps: the work', 'Order: what decides the steps'],
         narration="Here is who does what. [[slnc 400]] The slip writer lists each order's steps, once. [[slnc 500]] Shop routes holds the routing slip, and the dynamic router. [[slnc 500]] The steps do the work. [[slnc 300]] And the order's details decide which steps it needs."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel routingSlip()', 'Hospital treatment cards', 'Factory job travellers', 'Document approval chains'],
         narration="You have probably met this already. [[slnc 400]] Camel's routing slip. [[slnc 500]] Hospital treatment cards, and the job travellers that follow parts through a factory. [[slnc 500]] And documents that carry their own chain of approvers."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Different messages need', 'different steps, known at the start.', '', 'Decide on the way?', 'Use dynamicRouter().'],
         narration='So, when should you use it? [[slnc 400]] When different messages need different steps, known at the start. [[slnc 500]] When the next step depends on what just happened, use the dynamic router, or a process manager, instead.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a', 'loyalty-points step.'],
         narration="That's the Routing Slip, with Apache Camel. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Write the route once, and let the message carry it. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a loyalty points step, for registered customers. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Routing Slip with Apache Camel Pattern  ·  Java 21', 'poster': {'headline': [('ROUTING SLIP', 'text'), ('WITH CAMEL', 'text')], 'before': {'code': 'every order, all 6 steps', 'note': '24 visits, 15 useful', 'tag': 'BEFORE'}, 'after': {'code': 'routingSlip(header("slip"))', 'note': '15 visits, all useful', 'tag': 'AFTER'}, 'taglines': [('Each order carries its route', 'gold')]}, 'highlight': {}}
