"""Scene definitions for the Wire Tap with Apache Camel teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Wire Tap with Apache Camel',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Wire Tap pattern, built with Apache Camel, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A wire tap sends a copy of every message to a side channel. [[slnc 300]] The sender and the receiver carry on as if nothing were listening. [[slnc 500]] Apache Camel is an open-source library for moving messages, and it has a wire tap built in. [[slnc 600]] Think of a security camera over a shop till. [[slnc 300]] It records every sale, and the cashier does nothing differently. [[slnc 300]] But the camera must only ever see a copy of the receipt, never change the real one. [[slnc 700]] In this video, the domain is an online shop's payments, and the auditors who want a copy of each one. [[slnc 500]] By the end, you will hear how one step taps every payment. [[slnc 300]] A trap where the tap changes the real message. [[slnc 300]] How to fix it. [[slnc 300]] And what a tap on its own thread costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Logging typed into payments', 'by hand.', '', 'It missed refunds.', 'It showed full card numbers.', '', 'Auditors want a masked copy.'],
         narration='Here is the scenario. [[slnc 400]] Logging had been typed into the payment service by hand. [[slnc 500]] It missed the refunds. [[slnc 300]] And it wrote out full card numbers. [[slnc 500]] Auditors want a masked copy of every payment, without changing checkout, or the payment service.'),
    dict(key='03-act-1', kind='console', title='Act One — A tap on the route',
         body='ONE. A tap on the route.\n  audit: 4 of 4, cards masked\n  payment handled 4',
         narration='First demo: a wire tap on the payments route. [[slnc 400]] One step is added to the route. [[slnc 300]] It sends a copy of every message to the audit. [[slnc 600]] All four payments are copied. [[slnc 300]] The refund too. [[slnc 300]] Card numbers are masked in the audit. [[slnc 500]] The payment service handles all four, as before. [[slnc 300]] It was not changed.'),
    dict(key='04-act-2', kind='console', title='Act Two — Not a copy after all',
         body='TWO. Not a copy after all.\n  ORD-1 now: card **** 1234',
         narration="Second demo: the tap was not handed a copy. [[slnc 400]] Camel gave the audit the very same message object. [[slnc 600]] So when the audit masked the card number, it masked the real one. [[slnc 500]] Checkout's own payment message now shows only the last four digits. [[slnc 300]] A real charge would fail."),
    dict(key='05-act-3', kind='console', title='Act Three — onPrepare: a real copy',
         body='THREE. onPrepare: a real copy.\n  audit lines: 4\n  ORD-1 card unchanged',
         narration="Third demo: give the tap its own copy. [[slnc 400]] Camel has a step for this, called on prepare. [[slnc 300]] It runs just before the copy is sent. [[slnc 600]] There, the message is copied. [[slnc 500]] The audit still gets four masked lines. [[slnc 300]] And checkout's message keeps its full card number."),
    dict(key='06-act-4', kind='console', title='Act Four — The audit stops',
         body='FOUR. The audit stops.\n  audit stopped\n  ORD-4 still charged',
         narration='Fourth demo: the audit stops. [[slnc 400]] The audit route is switched off, for maintenance. [[slnc 600]] Another order is paid. [[slnc 300]] The copy to the audit fails. [[slnc 500]] But the order is still charged. [[slnc 300]] Checkout and the payment service never hear about it.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  4 payments: under 0.3 s\n  audit lags, catches up later',
         narration='Fifth demo: the bill. [[slnc 400]] The audit is made slow. [[slnc 300]] A tenth of a second, for every copy. [[slnc 600]] Four payments still finish quickly. [[slnc 300]] The tap runs on its own thread. [[slnc 500]] But the audit falls behind, and only catches up later. [[slnc 300]] And copies still waiting are only in memory. [[slnc 300]] If the program stops, they are lost. [[slnc 600]] For a real audit, tap to a durable queue.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Camel',
         body=['wireTap(endpoint): a copy,', 'on its own thread.', '', 'onPrepare: make it a real copy.', '', 'The main route carries on.'],
         narration="Let's name the pattern, in Camel's words. [[slnc 400]] The wire tap step sends a copy to another route, on its own thread. [[slnc 500]] On prepare makes sure it really is a copy. [[slnc 500]] And the main route carries on, without waiting."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['ShopRoutes: the routes and tap', 'Audit: masks and records', 'PaymentService: the real work', 'PaymentMessage: the message'],
         narration='Here is who does what. [[slnc 400]] Shop routes holds the payments route, with its tap. [[slnc 500]] The audit masks each card number, and records a line. [[slnc 500]] The payment service does the real work. [[slnc 300]] And the payment message is what flows through.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Camel wireTap()', 'Spring Integration wire-tap', 'Switch port mirroring', 'Audit consumers on Kafka'],
         narration="You have probably met this already. [[slnc 400]] Camel's wire tap, and Spring Integration's. [[slnc 500]] Network switches that mirror a port, so traffic can be watched. [[slnc 500]] And services that read a Kafka topic, only to audit it."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['A copy on the side, for audit', 'or monitoring.', '', 'Always copy the message.', "Watch the tap's errors.", 'Durable queue if none may be lost.'],
         narration="So, when should you use it? [[slnc 400]] When auditors or a dashboard need a copy of traffic, without touching the sender or receiver. [[slnc 500]] Always make the copy independent. [[slnc 300]] Watch the tap's errors separately. [[slnc 300]] And tap to a durable queue, when no copy may be lost."),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Make the', 'message immutable.'],
         narration="That's the Wire Tap, with Apache Camel. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Copy every message to the side, and make sure it really is a copy. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make the payment message immutable, and see why the trap disappears. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Wire Tap with Apache Camel Pattern  ·  Java 21', 'poster': {'headline': [('WIRE TAP', 'text'), ('WITH CAMEL', 'text')], 'before': {'code': 'logging typed by hand', 'note': 'refunds missed, cards shown', 'tag': 'BEFORE'}, 'after': {'code': 'wireTap("direct:audit")', 'note': 'every payment, masked', 'tag': 'AFTER'}, 'taglines': [('A copy on the side', 'gold')]}, 'highlight': {}}
