"""Scene definitions for the Gateway Offloading teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Gateway Offloading',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Gateway Offloading pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] Many services need the same chores done on every request. [[slnc 300]] Checking who the caller is. [[slnc 300]] Stopping callers who send too much. [[slnc 300]] Compressing the answer. [[slnc 500]] Gateway offloading moves those chores into the gateway in front of the services. [[slnc 300]] So they are done once, the same way for everyone. [[slnc 600]] Think of an office building with a reception desk. [[slnc 300]] Visitors sign in once, at the front door. [[slnc 300]] The teams upstairs do not each check passports at their own door. [[slnc 700]] In this video, the domain is an online shop, with three services. [[slnc 300]] Catalog, cart, and orders. [[slnc 500]] By the end, you will hear how three copies of a sign-in check drifted apart. [[slnc 300]] How the gateway takes over sign-in, rate limits and compression. [[slnc 300]] And why there must be no side door.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Catalog, cart and orders.', '', 'Each checks the sign-in token', 'with its own copy of the code.', '', 'Orders forgot to check expiry.'],
         narration="Here is the scenario. [[slnc 400]] The shop has three services. [[slnc 300]] Catalog, cart and orders. [[slnc 500]] Each one checked the customer's sign-in token itself, with its own copy of the code. [[slnc 500]] The orders team's copy forgot to check whether the token had expired."),
    dict(key='03-act-1', kind='console', title='Act One — Every service checks for itself',
         body='ONE. Every service checks for itself.\n  expired -> catalog: 401\n  expired -> cart: 401\n  expired -> orders: 200',
         narration="First demo: every service checks the sign-in token itself. [[slnc 400]] The customer's token expired a minute ago. [[slnc 600]] The catalog service refuses it. [[slnc 300]] The cart service refuses it. [[slnc 300]] But the orders service lets the customer in. [[slnc 600]] The orders team's copy of the check forgot about expiry. [[slnc 300]] Three copies of the same check, and one of them is wrong."),
    dict(key='04-act-2', kind='console', title='Act Two — One check, at the gateway',
         body='TWO. One check, at the gateway.\n  expired -> all three: 401\n  valid -> orders: 200',
         narration='Second demo: the gateway checks the token, once. [[slnc 400]] Every request passes through the gateway first. [[slnc 600]] The expired token is refused for all three services. [[slnc 300]] The same way, every time. [[slnc 500]] A valid token gets through. [[slnc 300]] The gateway tells the orders service who the customer is. [[slnc 500]] The services hold no sign-in code at all.'),
    dict(key='05-act-3', kind='console', title='Act Three — Rate limiting',
         body='THREE. Rate limiting.\n  8 requests: 5 passed, 3 refused (429)\n  orders saw 5',
         narration='Third demo: rate limiting. [[slnc 400]] The gateway allows each customer five requests a second. [[slnc 600]] A customer sends eight requests in one second. [[slnc 300]] Five pass. [[slnc 300]] Three are refused, with too many requests. [[slnc 500]] The orders service only ever sees five. [[slnc 300]] And no service had to write a rate limiter.'),
    dict(key='06-act-4', kind='console', title='Act Four — Compression',
         body='FOUR. Compression.\n  catalog: 10094 bytes plain\n  gzipped: under a fifth',
         narration='Fourth demo: compression. [[slnc 400]] The catalog page is about ten thousand bytes. [[slnc 600]] The gateway compresses it, for every browser that accepts compression. [[slnc 300]] It shrinks to under a fifth of its size. [[slnc 500]] One compressor at the gateway. [[slnc 300]] Not one in every service.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  straight to orders as ben: 200\n  no side doors',
         narration='Fifth demo: the bill. [[slnc 400]] The services now trust whatever the gateway tells them. [[slnc 600]] So a call that skips the gateway, and goes straight to the orders service claiming to be another customer, is accepted. [[slnc 600]] The services must only be reachable through the gateway. [[slnc 500]] And everything goes through one place. [[slnc 300]] If the gateway fails, or slows down, every page does.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Shared chores move to the gateway.', '', 'Sign-in, rate limits, compression.', '', 'Services keep only their business.'],
         narration="Let's name the pattern. [[slnc 400]] The chores every service needs move into the gateway. [[slnc 500]] Checking sign-in. [[slnc 300]] Limiting how often each customer can call. [[slnc 300]] Compressing responses. [[slnc 500]] The services keep only their own business."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Gateway: sign-in, limit, route, compress', 'ShopService: just its own job', 'SelfCheckingService: the old way', "Tokens: the customer's sign-in"],
         narration='Here is who does what. [[slnc 400]] The gateway does four steps, in order. [[slnc 300]] Check sign-in. [[slnc 300]] Check the rate limit. [[slnc 300]] Route the request, saying who the customer is. [[slnc 300]] And compress the answer. [[slnc 500]] The shop services just do their own job. [[slnc 500]] The self-checking service is the old way, with its own copy of the check.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Kong, NGINX, Envoy', 'AWS API Gateway', 'Spring Cloud Gateway', 'TLS at the load balancer'],
         narration='You have probably met this pattern already. [[slnc 400]] Gateways such as Kong, NGINX, and Envoy have plugins for sign-in checks and rate limits. [[slnc 500]] Cloud gateways, and Spring Cloud Gateway, do the same. [[slnc 500]] And a load balancer that handles encryption is offloading too.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Many services need the same chores.', '', 'Keep business rules out.', 'Block every side door.', 'Treat the gateway as critical.'],
         narration='So, when should you use it? [[slnc 400]] When many services need exactly the same chores. [[slnc 500]] Keep business rules out of the gateway. [[slnc 300]] Make sure nobody can reach the services around it. [[slnc 300]] And run the gateway as the critical piece it now is.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Close the side door', 'with a gateway secret.'],
         narration="That's the Gateway Offloading pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Do the shared chores once, at the door. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make the services refuse any call without a secret that only the gateway adds. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Gateway Offloading Pattern  ·  Java 21', 'poster': {'headline': [('GATEWAY', 'text'), ('OFFLOADING', 'text')], 'before': {'code': '3 services, 3 token checks', 'note': 'orders forgot expiry', 'tag': 'BEFORE'}, 'after': {'code': 'one check, at the gateway', 'note': '401 for all three', 'tag': 'AFTER'}, 'taglines': [('Do the shared chores once', 'gold')]}, 'highlight': {}}
