"""Scene definitions for the Guaranteed Delivery teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Guaranteed Delivery',
         body=None,
         narration='Hello, and welcome. [[slnc 400]] This video explains the Guaranteed Delivery pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] With guaranteed delivery, every message is stored safely on disk before it is accepted. [[slnc 300]] It is marked as done only after it has been delivered. [[slnc 300]] And after a crash, everything not marked as done is delivered again. [[slnc 600]] Think of recorded delivery at the post office. [[slnc 300]] Each parcel is written in a ledger before you get your receipt. [[slnc 300]] The recipient signs when it arrives. [[slnc 300]] If a van breaks down, the ledger says exactly what to send out again. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] It sends an order confirmation email for every order, through a queue in front of a slow email provider. [[slnc 500]] By the end, you will hear how messages in memory are lost. [[slnc 300]] How a journal on disk keeps them. [[slnc 300]] How acknowledgements work. [[slnc 300]] And why guaranteed means at least once.'),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A confirmation email per order.', '', 'A queue in front of a slow', 'email provider.', '', 'The queue lived in memory.'],
         narration="Here is the scenario. [[slnc 400]] Every order gets a confirmation email. [[slnc 500]] The emails wait in a queue, because the email provider is slow. [[slnc 500]] And that queue lived only in the server's memory."),
    dict(key='03-act-1', kind='console', title='Act One — Only in memory',
         body='ONE. Only in memory.\n  10 emails queued in memory\n  server restarts: 0 queued',
         narration='First demo: confirmation emails queued in memory. [[slnc 400]] The email provider is slow today. [[slnc 300]] Ten emails are waiting in the queue. [[slnc 600]] The server restarts, for an ordinary update. [[slnc 300]] The queue lived in memory. [[slnc 300]] Now it is empty. [[slnc 500]] Ten customers will never hear that their order was received.'),
    dict(key='04-act-2', kind='console', title='Act Two — Written to disk first',
         body='TWO. Written to disk first.\n  10 accepted: journal has 10 lines\n  after restart: 10 waiting',
         narration='Second demo: every message is written to disk before it is accepted. [[slnc 400]] Each email is written to a journal file. [[slnc 300]] Only when it is safely on the disk is the email accepted. [[slnc 600]] Ten emails, ten lines in the file. [[slnc 500]] The server restarts. [[slnc 300]] It reads the file. [[slnc 300]] Ten emails are still waiting.'),
    dict(key='05-act-3', kind='console', title='Act Three — Acknowledgements',
         body='THREE. Acknowledgements.\n  6 sent and acknowledged; crash\n  waiting: MAIL-7, 8, 9, 10\n  sent: 10 of 10, each once',
         narration='Third demo: delivered messages are acknowledged. [[slnc 400]] When an email is sent, the journal writes a second line: acknowledged. [[slnc 600]] Six emails are sent and acknowledged. [[slnc 300]] Then the server crashes. [[slnc 500]] After the restart, only emails seven to ten are still waiting. [[slnc 300]] They are sent. [[slnc 300]] All ten customers get exactly one email.'),
    dict(key='06-act-4', kind='console', title='Act Four — At least once',
         body='FOUR. At least once.\n  MAIL-11 sent; crash before ACK\n  sent again: duplicates 1',
         narration='Fourth demo: a crash between sending and acknowledging. [[slnc 400]] Email eleven is sent. [[slnc 300]] And the server crashes, before it writes the acknowledgement. [[slnc 600]] After the restart, the journal cannot know it was sent. [[slnc 300]] So it sends it again. [[slnc 300]] The customer gets two emails. [[slnc 600]] Guaranteed delivery means at least once. [[slnc 300]] Not exactly once.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  10 disk writes to accept, 10 to ACK\n  journal grows; duplicates happen',
         narration='Fifth demo: the bill. [[slnc 400]] The disk is now in the path of every message. [[slnc 300]] Ten emails cost ten forced disk writes to accept, and ten more to acknowledge. [[slnc 600]] The journal keeps growing, until someone trims the acknowledged lines. [[slnc 300]] And the receivers must cope with the odd duplicate.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Store it on disk, then say', '"accepted".', '', 'Deliver it, then write', '"acknowledged".', '', 'After a crash: replay the rest.'],
         narration="Let's name the pattern. [[slnc 400]] Write each message to disk, and make sure it has reached the disk. [[slnc 300]] Only then tell the sender: accepted. [[slnc 500]] When it is delivered, write a second line: acknowledged. [[slnc 500]] After a crash, read the file, and deliver every message that was never acknowledged."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Journal: send, acknowledge,', 'unacknowledged', 'EmailSender: the receiver', 'MemoryQueue: the old way'],
         narration='Here is who does what. [[slnc 400]] The journal writes messages and acknowledgements to one file, and finds what is still waiting. [[slnc 500]] The email sender stands in for the slow email provider. [[slnc 500]] And the memory queue is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Durable queues in RabbitMQ', 'Persistent messages in JMS', "Kafka's replicated log", 'Transactional outbox'],
         narration='You have probably met this pattern already. [[slnc 400]] RabbitMQ has durable queues and persistent messages. [[slnc 300]] So does J M S. [[slnc 500]] Kafka writes every message to a log, copied across machines. [[slnc 500]] And the transactional outbox stores messages in the database first, for the same reason.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Messages that must not be lost:', 'orders, payments, confirmations.', '', 'Expect duplicates.', 'Trim what is acknowledged.', '', 'Cheap to lose? Skip it.'],
         narration='So, when should you use it? [[slnc 400]] For messages that must not be lost. [[slnc 300]] Orders, payments, and confirmations. [[slnc 500]] Expect duplicates, and make receivers cope with them. [[slnc 300]] Trim what has been acknowledged. [[slnc 500]] And for messages that are cheap to lose, such as live price updates, skip it.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Make the email sender', 'ignore duplicates.'],
         narration="That's the Guaranteed Delivery pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Write it down before you say yes, and cross it off only when it has arrived. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Make the email sender skip any email it has already sent. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Guaranteed Delivery Pattern  ·  Java 21', 'poster': {'headline': [('GUARANTEED', 'text'), ('DELIVERY', 'text')], 'before': {'code': 'queue in memory', 'note': 'restart: 10 emails lost', 'tag': 'BEFORE'}, 'after': {'code': 'force to disk, then accept', 'note': 'every email delivered', 'tag': 'AFTER'}, 'taglines': [('Write it down before you say yes', 'gold')]}, 'highlight': {}}
