"""Scene definitions for the Remote Facade with Spring MVC teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Remote Facade with Spring MVC',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Remote Facade pattern, with Spring MVC, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A remote facade gives callers across a network a few coarse calls, each doing a lot. [[slnc 300]] Instead of many small calls, each paying for a trip across the network. [[slnc 500]] Spring MVC is the open-source web framework most Java services use. [[slnc 600]] Think of ordering at a restaurant. [[slnc 300]] You give the whole order in one visit, instead of calling the waiter over five times. [[slnc 700]] In this video, the domain is an online shop's phone app, showing and changing an order. [[slnc 500]] By the end, you will hear what five round trips cost. [[slnc 300]] How one call returns a whole screen. [[slnc 300]] How a change becomes all or nothing. [[slnc 300]] And what the facade costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The phone app asked for', 'each fact separately.', '', '80 ms per question.', '', 'A change took two calls.'],
         narration="Here is the scenario. [[slnc 400]] The shop's phone app asked the server for each fact of the order screen separately. [[slnc 500]] On a mobile network, each question took about eighty milliseconds. [[slnc 500]] And changing a delivery took two calls, that could fail halfway."),
    dict(key='03-act-1', kind='console', title='Act One — A call for every fact',
         body='ONE. A call for every fact.\n  5 round trips\n  over 0.4 s',
         narration='First demo: the phone app asks for each fact separately. [[slnc 400]] The customer. [[slnc 300]] The items. [[slnc 300]] The total. [[slnc 300]] The address. [[slnc 300]] The delivery slot. [[slnc 600]] Five trips across a mobile network. [[slnc 300]] Almost half a second, before the screen can be drawn.'),
    dict(key='04-act-2', kind='console', title='Act Two — The whole screen as JSON',
         body='TWO. The whole screen as JSON.\n  GET /order-summary: all six facts\n  1 round trip, under 0.2 s',
         narration='Second demo: a remote facade. [[slnc 400]] One call returns everything the order screen needs, as one JSON document. [[slnc 600]] One trip across the network. [[slnc 300]] Under a fifth of a second.'),
    dict(key='05-act-3', kind='console', title='Act Three — All or nothing',
         body='THREE. All or nothing.\n  small calls: new address, old slot\n  facade, Sunday: 422, unchanged\n  facade, Tuesday: 200, both changed',
         narration='Third demo: a change, all or nothing. [[slnc 400]] With small calls, the address changes first. [[slnc 300]] Then the new slot is refused. [[slnc 500]] The order is left half changed. [[slnc 300]] New address, old slot. [[slnc 600]] The facade takes the whole change in one call. [[slnc 300]] Sunday is refused, and nothing changes. [[slnc 500]] Tuesday is accepted, and both change together.'),
    dict(key='06-act-4', kind='console', title='Act Four — Fine-grained inside',
         body='FOUR. Fine-grained inside.\n  rules stay on Order\n  application/problem+json',
         narration="Fourth demo: inside, the order stays fine-grained. [[slnc 400]] The facade calls the order's small methods, inside the server, where calls are cheap. [[slnc 500]] The rule about valid slots lives on the order. [[slnc 300]] And a refusal comes back as a standard problem report."),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  slot widget: 8 bytes vs 130',
         narration='Fifth demo: the bill. [[slnc 400]] A small widget shows only the delivery slot. [[slnc 300]] The small call sends eight bytes. [[slnc 300]] The summary sends a hundred and thirty. [[slnc 600]] And every new screen may want its own facade method.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Spring MVC',
         body=['A thin controller for remote callers.', '', 'One call per screen, as JSON.', 'One call per change.', '', 'Fine-grained objects inside.'],
         narration="Let's name the pattern, in Spring's words. [[slnc 400]] A thin controller, just for remote callers. [[slnc 500]] One call returns a whole screen, as JSON. [[slnc 300]] One call makes a whole change. [[slnc 500]] And inside, the objects stay fine-grained."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['OrderFacade: summary and delivery', 'Order: small methods, the rules', 'FineGrainedController: the old way', 'MobileNetwork: 80 ms per request'],
         narration='Here is who does what. [[slnc 400]] The order facade offers the summary, and the delivery change. [[slnc 500]] The order keeps its small methods, and the business rules. [[slnc 500]] The fine-grained controller is the old way. [[slnc 300]] And the mobile network filter adds eighty milliseconds to every request.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Summary and details endpoints', 'Backends for frontends', 'GraphQL'],
         narration='You have probably met this already. [[slnc 400]] Web endpoints that return a whole screen at once. [[slnc 500]] Backends for frontends, which give each app its own coarse service. [[slnc 500]] And GraphQL, which lets an app ask for a whole screen in one request.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Callers across a slow network.', '', 'Screen-sized calls.', 'All-or-nothing changes.', 'Rules stay inside.'],
         narration='So, when should you use it? [[slnc 400]] For callers across a network, especially a slow one. [[slnc 500]] Offer screen-sized calls. [[slnc 300]] Make changes all or nothing. [[slnc 300]] And keep the business rules inside, on the objects.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add an ETag', 'to the summary.'],
         narration="That's the Remote Facade, with Spring MVC. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Across a network, ask once for the whole screen, and change it in one step. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add an entity tag to the summary, so an unchanged screen costs almost nothing. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Remote Facade with Spring MVC Pattern  ·  Java 21', 'poster': {'headline': [('REMOTE FACADE', 'text'), ('WITH SPRING MVC', 'text')], 'before': {'code': 'GET /order/customer, /items, ...', 'note': '5 round trips, over 0.4 s', 'tag': 'BEFORE'}, 'after': {'code': 'GET /order-summary', 'note': '1 round trip, JSON', 'tag': 'AFTER'}, 'taglines': [('One call for the screen', 'gold')]}, 'highlight': {}}
