"""Scene definitions for the Higher-Order Functions teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Higher-Order Functions',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains Higher-Order Functions, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A higher-order function is a function that takes another function. [[slnc 300]] Or gives one back. [[slnc 500]] That lets one piece of code serve many questions. [[slnc 300]] And lets small rules be joined into bigger ones. [[slnc 600]] Think of a coffee machine that takes pods. [[slnc 300]] The machine does the hard part once. [[slnc 300]] The pod decides the drink. [[slnc 300]] You do not buy a new machine for each flavour. [[slnc 300]] You pass a different pod in. [[slnc 700]] In this video, the domain is an online shop's catalogue page, and its prices. [[slnc 500]] By the end, you will hear how copied loops pile up. [[slnc 300]] How passing a test in replaces them. [[slnc 300]] How to make and join tests to order. [[slnc 300]] And why the order of price rules matters."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['The catalogue answers questions:', 'under 10, in stock, mugs.', '', 'One method and one loop', 'per question.'],
         narration="Here is the scenario. [[slnc 400]] The shop's catalogue page answers questions. [[slnc 300]] Under ten. [[slnc 300]] In stock. [[slnc 300]] Mugs. [[slnc 500]] Each question had its own method, and its own loop. [[slnc 500]] The loops were identical, except for one test in the middle."),
    dict(key='03-act-1', kind='console', title='Act One — A loop for every question',
         body='ONE. A loop for every question.\n  3 methods, 3 identical loops\n  a new question: a 4th copy',
         narration='First demo: a loop for every question. [[slnc 400]] The catalogue can list products under ten. [[slnc 300]] Products in stock. [[slnc 300]] And mugs. [[slnc 600]] Each question has its own method, with its own loop. [[slnc 300]] The three loops are identical, except for one test in the middle. [[slnc 600]] A new question, like cheap mugs that are in stock, means copying the loop again.'),
    dict(key='04-act-2', kind='console', title='Act Two — Pass the test in',
         body='TWO. Pass the test in.\n  price < 10: Blue mug, Mini lamp, Tea towel\n  same answers, one loop',
         narration='Second demo: one loop, and the test is passed in. [[slnc 400]] There is now one filter method. [[slnc 300]] It takes the list, and a function that says yes or no for each product. [[slnc 600]] Pass in, price below ten. [[slnc 300]] The blue mug, the mini lamp, and the tea towel. [[slnc 300]] The same answer as before. [[slnc 600]] A function that takes another function is called a higher-order function.'),
    dict(key='05-act-3', kind='console', title='Act Three — Functions that make functions',
         body='THREE. Functions that make functions.\n  cheap, mug, in stock: Blue mug\n  under 20, sold out: Travel mug',
         narration='Third demo: functions that make functions. [[slnc 400]] Price below ten returns a test, made to order. [[slnc 300]] So does, in category mug. [[slnc 300]] And, in stock. [[slnc 600]] Tests can be joined with and. [[slnc 300]] Price below ten, and a mug, and in stock. [[slnc 300]] The blue mug. [[slnc 600]] Price below twenty, and not in stock. [[slnc 300]] The travel mug. [[slnc 500]] New questions, built from small parts. [[slnc 300]] And no new loop.'),
    dict(key='06-act-4', kind='console', title='Act Four — Price rules as values',
         body='FOUR. Price rules as values.\n  20% then 5 off: 31.00\n  5 off then 20%: 32.00',
         narration='Fourth demo: price rules are functions too. [[slnc 400]] Twenty percent off is a function. [[slnc 300]] Five off is another. [[slnc 300]] They can be joined, one after the other. [[slnc 600]] The desk lamp costs forty-five. [[slnc 300]] Twenty percent off, then five off. [[slnc 300]] Thirty-one. [[slnc 500]] Five off, then twenty percent off. [[slnc 300]] Thirty-two. [[slnc 600]] The order matters. [[slnc 300]] And the code makes the order plain.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  anonymous lambdas hide rules\n  name them: priceBelow, inStock',
         narration='Fifth demo: the bill. [[slnc 400]] Small functions need good names. [[slnc 600]] A long chain of unnamed functions can hide the rule it implements. [[slnc 300]] And an error inside one shows a made-up name in the error report. [[slnc 600]] So give important functions real names, like price below, and in stock. [[slnc 300]] And keep each one short.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Take a function:', 'pass the behaviour in.', '', 'Return a function:', 'make rules to order.', '', 'Combine them.'],
         narration="Let's name the pattern. [[slnc 400]] A function can take a function. [[slnc 300]] So the part that changes is passed in. [[slnc 500]] A function can return a function. [[slnc 300]] So rules can be made to order. [[slnc 500]] And functions can be joined, into bigger rules."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['filter: one loop, test passed in', 'priceBelow, inStock: make tests', 'percentOff, amountOff: make price rules', 'and, andThen: join them'],
         narration='Here is who does what. [[slnc 400]] Filter has the one loop, and takes the test as a function. [[slnc 500]] Price below, and in stock, make tests to order. [[slnc 300]] Percent off, and amount off, make price rules. [[slnc 500]] And, and and-then, join them together.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['stream().filter and map', 'Comparator.comparing', 'Predicate.and, Function.andThen', 'Callbacks and listeners'],
         narration='You have probably met this pattern already. [[slnc 400]] Java streams take functions in filter and map. [[slnc 500]] Comparators are made by functions, and joined with then-comparing. [[slnc 500]] And every callback or event listener is a function, passed in to be called later.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Code repeats with one', 'small part changing.', '', 'Pass that part in.', 'Name your functions.', 'Mind the order.'],
         narration='So, when should you use it? [[slnc 400]] When the same code repeats, with one small part changing. [[slnc 500]] Pass that part in. [[slnc 300]] Give important functions names. [[slnc 300]] And mind the order when you join them.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Build', 'priceBetween from priceBelow.'],
         narration="That's Higher-Order Functions. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Pass the part that changes in, as a function. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Build a price between test, from price below and negate. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Higher-Order Functions Pattern  ·  Java 21', 'poster': {'headline': [('HIGHER-ORDER', 'text'), ('FUNCTIONS', 'text')], 'before': {'code': '3 methods, 3 copied loops', 'note': 'a 4th for every question', 'tag': 'BEFORE'}, 'after': {'code': 'filter(all, priceBelow(10))', 'note': 'one loop, tests passed in', 'tag': 'AFTER'}, 'taglines': [('Pass behaviour, not copies', 'gold')]}, 'highlight': {}}
