"""Scene definitions for the Polling Consumer with RabbitMQ teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Polling Consumer with RabbitMQ',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Polling Consumer pattern, with a real RabbitMQ broker, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A polling consumer asks for the next message when it is ready. [[slnc 300]] Instead of having messages pushed at it as fast as they arrive. [[slnc 500]] RabbitMQ is an open-source message broker, and it can do both, plus a middle way. [[slnc 600]] Think of a restaurant kitchen. [[slnc 300]] Orders shoved through the hatch as they come, until the rail overflows. [[slnc 300]] Or the chef asking for the next one when ready. [[slnc 300]] Or a few tickets on the rail, topped up as each is finished. [[slnc 700]] In this video, the domain is an online shop's warehouse label printer. [[slnc 500]] By the end, you will hear what unlimited push does. [[slnc 300]] How polling protects the printer. [[slnc 300]] What polling costs. [[slnc 300]] And RabbitMQ's middle way."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A label printer holds 10 jobs.', '', 'A sale: 50 orders at once.', '', 'Paper runs out mid-burst.'],
         narration='Here is the scenario. [[slnc 400]] The warehouse label printer holds ten jobs in its memory. [[slnc 500]] During a sale, fifty orders arrive at once. [[slnc 500]] And sometimes the paper runs out, and no order may be lost.'),
    dict(key='03-act-1', kind='console', title='Act One — Push with no limit',
         body='ONE. Push with no limit.\n  pushed 50 at once\n  after the crash: 50 back on the queue',
         narration="First demo: RabbitMQ pushes orders at the printer, with no limit. [[slnc 400]] A burst of fifty orders arrives. [[slnc 600]] The broker pushes all fifty into the printer's memory, at once. [[slnc 300]] Its buffer holds ten. [[slnc 600]] The printer crashes. [[slnc 300]] All fifty go back on the queue, to be sent again."),
    dict(key='04-act-2', kind='console', title='Act Two — A polling consumer',
         body='TWO. A polling consumer.\n  50 of 50 in 10 ticks\n  never more than 5 in hand',
         narration='Second demo: a polling consumer. [[slnc 400]] Each tick, the printer asks the broker for up to five orders. [[slnc 600]] It prints them, and acknowledges each one. [[slnc 500]] Fifty orders, in ten ticks. [[slnc 300]] Never more than five in hand.'),
    dict(key='05-act-3', kind='console', title='Act Three — Pausing is not polling',
         body='THREE. Pausing is not polling.\n  out of paper: printed 5, waiting 15\n  resumed: 20 of 20',
         narration='Third demo: pausing is simply not polling. [[slnc 400]] Twenty orders arrive. [[slnc 300]] After one tick, the paper runs out. [[slnc 600]] The printer stops asking. [[slnc 300]] Five printed. [[slnc 300]] Fifteen wait safely on the queue. [[slnc 500]] Paper is loaded. [[slnc 300]] Polling resumes. [[slnc 300]] Twenty of twenty, none lost.'),
    dict(key='06-act-4', kind='console', title='Act Four — When nothing is happening',
         body='FOUR. When nothing is happening.\n  600 empty polls in a quiet minute\n  prefetch 5: holds 5, no empty requests',
         narration='Fourth demo: when nothing is happening. [[slnc 400]] A quiet minute, asking every tenth of a second. [[slnc 300]] Six hundred requests to the broker. [[slnc 300]] All empty. [[slnc 600]] RabbitMQ has a middle way. [[slnc 300]] Push, but with a limit, called prefetch. [[slnc 500]] With a limit of five, the printer holds five orders. [[slnc 300]] The broker sends more only as it finishes them. [[slnc 500]] And a quiet queue costs no requests at all.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  waits up to one interval\n  prefer push with prefetch',
         narration="Fifth demo: the bill. [[slnc 400]] With polling, an order that arrives just after a poll waits a whole interval. [[slnc 500]] And every empty poll is a request to the broker. [[slnc 600]] RabbitMQ's own advice is to push with a prefetch limit. [[slnc 300]] Keep polling for when the receiver must decide exactly when to take work."),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in RabbitMQ',
         body=['basicGet: ask for one now.', '', 'basicConsume: be pushed.', '', 'basicQos(n): pushed, but never', 'more than n unacknowledged.'],
         narration="Let's name the pattern, in RabbitMQ's words. [[slnc 400]] Basic get asks for one message, now. [[slnc 300]] That is polling. [[slnc 500]] Basic consume asks the broker to push. [[slnc 500]] And basic Q o S sets a prefetch limit. [[slnc 300]] Pushed, but never more than that many unfinished at once."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['LabelPrinter: polls or subscribes', "Orders: checkout's sender", 'Broker: RabbitMQ in a container', 'Poll: waits for real conditions'],
         narration='Here is who does what. [[slnc 400]] The label printer either polls, or subscribes with a limit. [[slnc 500]] Orders is checkout, putting orders on the queue. [[slnc 500]] The broker class runs RabbitMQ in a container. [[slnc 300]] And poll waits for real conditions.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['RabbitMQ basicGet and prefetch', 'Amazon SQS ReceiveMessage', 'Kafka consumers, which always poll'],
         narration="You have probably met this already. [[slnc 400]] RabbitMQ's basic get, and its prefetch setting. [[slnc 500]] Amazon SQS, where receivers always ask, and can wait for a message to arrive. [[slnc 500]] And Kafka, whose consumers always poll."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['The receiver must choose', 'when to take work: poll.', '', 'Otherwise: push with', 'a prefetch limit.'],
         narration='So, when should you use it? [[slnc 400]] Poll when the receiver must decide exactly when to take work. [[slnc 500]] Otherwise, push with a prefetch limit, sized to what the receiver can hold.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Try prefetch', '1 and 50.'],
         narration="That's the Polling Consumer, with RabbitMQ. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Take work only when you are ready, and never more than you can hold. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It needs Docker running, and starts the broker for you. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Try a prefetch of one, and of fifty, and describe the difference. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Polling Consumer with RabbitMQ Pattern  ·  Java 21', 'poster': {'headline': [('POLLING CONSUMER', 'text'), ('WITH RABBITMQ', 'text')], 'before': {'code': 'basicConsume, no limit', 'note': '50 pushed into a buffer of 10', 'tag': 'BEFORE'}, 'after': {'code': 'basicGet / basicQos(5)', 'note': 'never more than 5 in hand', 'tag': 'AFTER'}, 'taglines': [('Take work when ready', 'gold')]}, 'highlight': {}}
