"""Scene definitions for the Reactor with Netty teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Reactor with Netty',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Reactor pattern, built with Netty, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A reactor is one thread that waits on many connections at once. [[slnc 300]] When something happens on one, it calls that connection's handler. [[slnc 500]] Netty is the open-source networking library underneath much of the Java world, and its event loops are reactors. [[slnc 600]] Think of a restaurant with one fast waiter covering many tables, going wherever a hand is raised. [[slnc 300]] And passing any hour-long dish straight to the kitchen. [[slnc 700]] In this video, the domain is an online shop's tills, asking a stock server short questions. [[slnc 500]] By the end, you will hear how one event loop serves a hundred tills. [[slnc 300]] How the pipeline handles half-sent questions. [[slnc 300]] How to add more loops. [[slnc 300]] And the one rule you must never break."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['100 tills stay connected.', '', 'They ask short questions:', '"stock KETTLE-1".', '', 'A thread per till: 100 threads.'],
         narration='Here is the scenario. [[slnc 400]] A hundred shop tills stay connected to a stock server. [[slnc 500]] They ask short questions, such as, how many kettles are in stock. [[slnc 500]] A thread for every till meant a hundred threads, almost all of them waiting.'),
    dict(key='03-act-1', kind='console', title='Act One — One event loop',
         body='ONE. One event loop.\n  100 tills connected\n  stock KETTLE-1: 4; handler threads: 1',
         narration="First demo: one Netty event loop serves every till. [[slnc 400]] An event loop is a reactor. [[slnc 300]] One thread, waiting on many connections at once. [[slnc 600]] A hundred tills connect. [[slnc 300]] Till one asks for the kettle's stock. [[slnc 300]] Four. [[slnc 500]] Every handler ran on one thread."),
    dict(key='04-act-2', kind='console', title='Act Two — The pipeline',
         body='TWO. The pipeline.\n  "price MU" + "G-1"\n  answer 800',
         narration="Second demo: the pipeline turns bytes into whole questions. [[slnc 400]] Till two sends half a question. [[slnc 300]] Then the other half, separately. [[slnc 600]] Netty's pipeline starts with a line decoder. [[slnc 300]] It waits for the end of the line. [[slnc 500]] So the handler only sees one whole question. [[slnc 300]] The answer: eight hundred pence."),
    dict(key='05-act-3', kind='console', title='Act Three — Everyone at once',
         body='THREE. Everyone at once.\n  100 correct answers\n  handler threads: 1',
         narration='Third demo: every till asks at once. [[slnc 400]] A hundred questions, at the same moment. [[slnc 600]] A hundred correct answers. [[slnc 300]] Still one thread running the handlers.'),
    dict(key='06-act-4', kind='console', title='Act Four — Several event loops',
         body='FOUR. Several event loops.\n  spread over 4 threads',
         narration='Fourth demo: several event loops. [[slnc 400]] Netty can run several reactors, one per thread. [[slnc 600]] With four worker loops, the hundred connections are spread over four threads. [[slnc 500]] And each connection always stays on its own loop. [[slnc 300]] So its handlers never run on two threads at once.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill: never block',
         body='FIVE. The bill: never block.\n  on the loop: waited over 0.2 s\n  own executor group: under 0.2 s',
         narration='Fifth demo: the bill. [[slnc 400]] Till two asks for a slow report. [[slnc 300]] It takes almost a third of a second, and it runs on the event loop. [[slnc 600]] Till three asks a quick question. [[slnc 300]] It waits more than a fifth of a second. [[slnc 600]] Now the handler runs on its own group of threads, away from the event loop. [[slnc 500]] Till three is answered at once. [[slnc 300]] The rule: never block the event loop.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern, in Netty',
         body=['An event loop: one thread,', 'many connections.', '', 'A pipeline of handlers.', '', 'Slow work: an executor group.'],
         narration="Let's name the pattern, in Netty's words. [[slnc 400]] An event loop is one thread, serving many connections. [[slnc 500]] Each connection has a pipeline of handlers. [[slnc 500]] And slow work runs on an executor group, away from the loop."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Boss loop: accepts', 'Worker loops: serve connections', 'Line decoder: whole questions', 'QuestionHandler: answers'],
         narration='Here is who does what. [[slnc 400]] The boss loop accepts new connections. [[slnc 300]] The worker loops serve them. [[slnc 500]] The line decoder turns bytes into whole questions. [[slnc 500]] And the question handler answers each one.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['gRPC, WebFlux and Vert.x on Netty', 'Node.js event loop', 'Nginx worker processes'],
         narration='You have probably met this already. [[slnc 400]] gRPC, Spring WebFlux, and Vert.x all run on Netty. [[slnc 500]] Node.js has an event loop. [[slnc 300]] And Nginx runs a few worker processes, each an event loop.'),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Many connections, mostly idle.', 'Custom protocols.', '', 'Short handlers.', 'Ready-made decoders.', 'Never block the loop.'],
         narration='So, when should you use it? [[slnc 400]] For many connections that are mostly idle, or for your own network protocol. [[slnc 500]] Keep handlers short. [[slnc 300]] Use ready-made decoders. [[slnc 300]] And never block the event loop.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a', 'logging handler.'],
         narration="That's the Reactor, with Netty. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] One thread can serve many connections, as long as nothing it runs ever blocks. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a handler that logs every question before it is answered. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Reactor with Netty Pattern  ·  Java 21', 'poster': {'headline': [('REACTOR', 'text'), ('WITH NETTY', 'text')], 'before': {'code': 'a thread per till', 'note': '100 threads, mostly idle', 'tag': 'BEFORE'}, 'after': {'code': 'group(boss, workers)', 'note': '100 tills, 1 event loop', 'tag': 'AFTER'}, 'taglines': [('Event loops, and never block', 'gold')]}, 'highlight': {}}
