"""Scene definitions for the Copy-on-Write teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Copy-on-Write',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Copy-on-Write pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] With copy-on-write, readers use the current version of the data, with no locks at all. [[slnc 300]] A writer never changes that version. [[slnc 300]] It makes a copy, changes the copy, and swaps it in. [[slnc 600]] Think of a restaurant's printed menus. [[slnc 300]] Diners read them for as long as they like. [[slnc 300]] To change a dish, the manager prints a whole new batch, and swaps them in at the door. [[slnc 300]] Diners already reading finish with the old menu. [[slnc 700]] In this video, the domain is an online shop. [[slnc 300]] When a price changes, it tells a list of listeners: the web page cache, the loyalty service, and the phone app. [[slnc 500]] By the end, you will hear how a plain list crashes when it changes while being read. [[slnc 300]] How copy-on-write fixes it. [[slnc 300]] Why readers never lock. [[slnc 300]] And what every write costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['A price changes: tell every listener.', '', 'Prices change all the time.', 'Listeners rarely change.', '', 'Listeners were in a plain ArrayList.'],
         narration='Here is the scenario. [[slnc 400]] When a price changes, the shop tells every listener on a list. [[slnc 500]] Prices change all the time. [[slnc 300]] The list of listeners rarely changes. [[slnc 300]] But sometimes a listener adds another, while it is being told. [[slnc 500]] The listeners were kept in a plain array list.'),
    dict(key='03-act-1', kind='console', title='Act One — A plain list, changed while read',
         body='ONE. A plain list, changed while read.\n  loyalty subscribes email mid-loop\n  ConcurrentModificationException\n  the phone app never heard',
         narration="First demo: a plain list, changed while it is being read. [[slnc 400]] The kettle's price changes. [[slnc 300]] The shop tells each listener in turn. [[slnc 500]] The web page cache hears it. [[slnc 300]] The loyalty service hears it, and subscribes the email service, adding to the list as it goes. [[slnc 600]] The loop crashes, with a concurrent modification exception. [[slnc 300]] The phone app never hears about the new price."),
    dict(key='04-act-2', kind='console', title='Act Two — A copy-on-write list',
         body='TWO. A copy-on-write list.\n  first change: web cache, loyalty, app\n  next change: + email service',
         narration='Second demo: a copy-on-write list. [[slnc 400]] The same thing happens. [[slnc 300]] The loyalty service subscribes the email service while being told. [[slnc 500]] This time, the loop is reading an array that nobody will ever change. [[slnc 300]] The new subscription copies the array, adds to the copy, and swaps it in. [[slnc 600]] The first change reaches all three listeners. [[slnc 300]] The next change reaches all four.'),
    dict(key='05-act-3', kind='console', title='Act Three — Readers never lock',
         body='THREE. Readers never lock.\n  100,000 passes, 1,000 changes\n  failures: 0; reader locks: 0',
         narration='Third demo: readers never lock, and are never disturbed. [[slnc 400]] One thread tells the listeners about prices, a hundred thousand times. [[slnc 300]] At the same moment, another thread subscribes and unsubscribes, a thousand times. [[slnc 600]] Failures: zero. [[slnc 300]] Locks taken by the readers: zero.'),
    dict(key='06-act-4', kind='console', title='Act Four — Snapshots',
         body='FOUR. Snapshots.\n  reader started with 3 listeners\n  the list now has 4',
         narration='Fourth demo: each reader sees a snapshot. [[slnc 400]] A reader starts going through the list. [[slnc 300]] It has three listeners. [[slnc 500]] Before it finishes, a fourth is added. [[slnc 500]] The reader finishes with the three it started with. [[slnc 300]] Like a diner with the old menu. [[slnc 300]] The next reader sees four.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  10,000 adds: 49,995,000 copies\n  for lists that rarely change',
         narration='Fifth demo: the bill. [[slnc 400]] Every write copies everything. [[slnc 500]] Add ten thousand listeners, one at a time. [[slnc 300]] Nearly fifty million references are copied along the way. [[slnc 600]] That is fine for a list that is read constantly and changed rarely. [[slnc 300]] It is wrong for anything that changes all the time.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Readers: take the current array,', 'no lock.', '', 'Writers: copy it, change the copy,', 'swap it in.', '', 'A published array never changes.'],
         narration="Let's name the pattern. [[slnc 400]] Readers take the current array, and read it with no lock. [[slnc 500]] Writers copy the array, change the copy, and swap it in, in one step. [[slnc 500]] The rule that makes it safe: once an array is published, nobody ever changes it again."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['CowList: the array and the swap', 'PriceListener: who is told', 'The notification loop: a reader', 'Subscribe: a writer', 'ArrayList: the old way'],
         narration='Here is who does what. [[slnc 400]] Cow list holds the array, and swaps in new copies. [[slnc 500]] A price listener is anyone who wants to be told about price changes. [[slnc 500]] The notification loop is a reader. [[slnc 300]] Subscribing is a write. [[slnc 500]] And the plain array list is the old way, kept for comparison.'),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['CopyOnWriteArrayList', 'Listener lists in Swing and Spring', 'fork() in Linux', 'File system snapshots'],
         narration="You have probably met this pattern already. [[slnc 400]] Java's copy on write array list, and copy on write array set. [[slnc 500]] Listener lists in Swing, Spring, and many libraries use them. [[slnc 500]] Linux shares memory between processes until one writes to it. [[slnc 300]] And file systems use the same trick for snapshots."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Small collections, read constantly,', 'changed rarely: listeners.', '', 'Use CopyOnWriteArrayList.', '', 'Changes often? Something else.'],
         narration="So, when should you use it? [[slnc 400]] For small collections that are read constantly, and changed rarely. [[slnc 300]] Lists of listeners are the classic case. [[slnc 500]] Use Java's copy on write array list, rather than writing your own. [[slnc 500]] And for data that changes often, choose a concurrent collection, or a lock."),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Swap in', 'CopyOnWriteArrayList.'],
         narration="That's the Copy-on-Write pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Readers read freely, and writers copy, change, and swap. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Replace the hand-written list with Java's copy on write array list, and run the demo again. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Copy-on-Write Pattern  ·  Java 21', 'poster': {'headline': [('COPY-ON-WRITE', 'text')], 'before': {'code': 'new ArrayList<>()', 'note': 'crashed mid-notification', 'tag': 'BEFORE'}, 'after': {'code': 'CopyOnWriteArrayList', 'note': 'readers never disturbed', 'tag': 'AFTER'}, 'taglines': [('Read freely, copy to change', 'gold')]}, 'highlight': {}}
