"""Scene definitions for the Contract Stub teaching video (generated from pattern.toml)."""

SCENES = [
    dict(key='01-poster', kind='poster', title='Contract Stub',
         body=None,
         narration="Hello, and welcome. [[slnc 400]] This video explains the Contract Stub pattern, in Java. [[slnc 300]] This video is presented by Jayasekhar Konduru. [[slnc 600]] First, a simple definition. [[slnc 300]] A stub is a stand-in for another service, used in tests. [[slnc 300]] A contract stub is made from a written agreement between the two teams. [[slnc 300]] And the real service is checked against that same agreement. [[slnc 300]] So the stub and the real service can never quietly drift apart. [[slnc 600]] Think of a fire drill. [[slnc 300]] If it used an old floor plan, everyone would practise walking to an exit that has since been bricked up. [[slnc 300]] A contract stub is a drill always run from the current plan. [[slnc 700]] In this video, the domain is an online shop's checkout, which calls a payment service run by another team. [[slnc 500]] By the end, you will hear how a hand-written stub let a bug reach production. [[slnc 300]] How a contract feeds both the stub and a check of the real service. [[slnc 300]] Why a strict stub helps. [[slnc 300]] And what the contract costs."),
    dict(key='02-scenario', kind='bullets', title='The Scenario',
         body=['Checkout calls the payment service.', '', 'Tests used a hand-written stub.', '', 'Payments renamed a field.', 'Tests stayed green.'],
         narration="Here is the scenario. [[slnc 400]] The shop's checkout calls a payment service, run by another team. [[slnc 500]] Checkout's tests used a stub the checkout team had written by hand. [[slnc 500]] The payment team renamed a field in its reply. [[slnc 300]] The tests stayed green. [[slnc 300]] And production broke."),
    dict(key='03-act-1', kind='console', title='Act One — A stub that drifted',
         body='ONE. A stub that drifted.\n  test vs hand stub: order confirmed\n  production vs v2: order stuck',
         narration='First demo: a hand-written stub. [[slnc 400]] A stub is a stand-in for another service, used in tests. [[slnc 600]] The checkout team wrote their own stub of the payment service. [[slnc 300]] It replies with a field called result, set to approved. [[slnc 300]] The checkout test passes. [[slnc 600]] But the payment team released version two. [[slnc 300]] They renamed result, to outcome. [[slnc 500]] In production, checkout finds no result in the reply. [[slnc 300]] The order is stuck. [[slnc 300]] And the tests stayed green, because the stub never changed.'),
    dict(key='04-act-2', kind='console', title='Act Two — A stub made from the contract',
         body='TWO. A stub made from the contract.\n  normal card: order confirmed\n  no funds: card declined\n  zero amount: payment rejected',
         narration="Second demo: a stub made from a contract. [[slnc 400]] The two teams write down what they have agreed. [[slnc 300]] Three interactions. [[slnc 300]] Each one is a request, and the reply it gets. [[slnc 600]] A normal charge is approved. [[slnc 300]] A card with no funds is declined. [[slnc 300]] A zero amount is rejected. [[slnc 600]] Checkout's tests use a stub built from that contract. [[slnc 300]] And they get exactly those three replies."),
    dict(key='05-act-3', kind='console', title='Act Three — The provider is checked too',
         body='THREE. The provider is checked too.\n  version 1: 3 of 3 match\n  version 2: 0 of 3, build fails',
         narration="Third demo: the real payment service is checked against the same contract. [[slnc 400]] The payment team's build replays all three interactions. [[slnc 600]] Version one matches, three of three. [[slnc 500]] Version two, with the rename, matches zero of three. [[slnc 300]] So the payment team's own build fails. [[slnc 300]] Before the change reaches anyone. [[slnc 600]] The stub and the real service can never quietly drift apart."),
    dict(key='06-act-4', kind='console', title='Act Four — A strict stub',
         body='FOUR. A strict stub.\n  hand stub, USD: order confirmed\n  contract stub, USD: no interaction',
         narration='Fourth demo: the contract stub is strict. [[slnc 400]] Checkout starts charging in US dollars. [[slnc 600]] The hand-written stub approves it. [[slnc 300]] Nobody asked the payment team. [[slnc 500]] The contract stub refuses. [[slnc 300]] There is no interaction in the contract for that request. [[slnc 600]] So checkout must agree it with the payment team first.'),
    dict(key='07-act-5', kind='console', title='Act Five — The bill',
         body='FIVE. The bill.\n  shared, versioned, run by both\n  only the listed interactions',
         narration='Fifth demo: the bill. [[slnc 400]] The contract is shared work. [[slnc 300]] Both teams must keep it, version it, and run it in both builds. [[slnc 600]] And it only covers what is written in it. [[slnc 300]] It says nothing about speed. [[slnc 300]] Or about the real network.'),
    dict(key='08-pattern', kind='bullets', title='The Pattern',
         body=['Write the contract down.', '', 'Consumer: test against a stub', 'made from it.', '', 'Provider: check against it.'],
         narration="Let's name the pattern. [[slnc 400]] Write the contract down, as requests and the replies they get. [[slnc 500]] The consumer tests against a stub made from that contract. [[slnc 500]] The provider's build checks the real service against the same contract."),
    dict(key='09-roles', kind='bullets', title='Who Does What',
         body=['Contract: the agreed interactions', 'ContractStub: answers from it', 'ProviderVerifier: checks the real service', 'Checkout: the consumer'],
         narration="Here is who does what. [[slnc 400]] The contract holds the agreed interactions. [[slnc 500]] The contract stub answers checkout's tests from it, and refuses anything else. [[slnc 500]] The provider verifier replays it against the real payment service. [[slnc 300]] And checkout is the consumer being tested."),
    dict(key='10-recognise', kind='bullets', title='Where You Have Seen It',
         body=['Spring Cloud Contract', 'Pact', 'OpenAPI mock servers'],
         narration="You have probably met this pattern already. [[slnc 400]] Spring Cloud Contract turns contracts into stubs, and tests for the provider. [[slnc 500]] Pact does the same, starting from the consumer's tests. [[slnc 500]] And mock servers built from an interface description work the same way."),
    dict(key='11-verdict', kind='bullets', title='When To Use It',
         body=['Separate teams, separate releases.', '', 'Share and version the contract.', 'Run it in both builds.', 'A refusal means: talk.'],
         narration='So, when should you use it? [[slnc 400]] When separate teams release their services separately. [[slnc 500]] Share and version the contract. [[slnc 300]] Run it in both builds. [[slnc 300]] And when the stub refuses a request, treat it as a prompt to talk to the other team.'),
    dict(key='12-outro', kind='outro', title='Thanks for Watching',
         body=['Full source, notes, diagrams and an animated walkthrough', 'are in the repository. Add a US dollar', 'interaction to the contract.'],
         narration="That's the Contract Stub pattern. [[slnc 400]] If you remember one sentence, make it this one. [[slnc 300]] Build the stub and check the real service from the same contract. [[slnc 500]] The full source code, written notes, diagrams, and an animated walkthrough are all in the repository. [[slnc 300]] It runs offline, with nothing installed except a Java development kit. [[slnc 500]] Here is one exercise to try. [[slnc 300]] Add a US dollar interaction to the contract, and make both sides pass. [[slnc 500]] If this helped, a like really does help other people find it. [[slnc 300]] And subscribe, if you'd like the rest of the series. [[slnc 400]] Thanks for watching."),
]

VIDEO = {'footer': 'Contract Stub Pattern  ·  Java 21', 'poster': {'headline': [('CONTRACT', 'text'), ('STUB', 'text')], 'before': {'code': 'new HandWrittenStub()', 'note': 'tests green, production broken', 'tag': 'BEFORE'}, 'after': {'code': 'new ContractStub(contract)', 'note': 'drift fails the build', 'tag': 'AFTER'}, 'taglines': [('A stub that cannot lie', 'gold')]}, 'highlight': {}}
